### ISSUE TITLE
[EPIC]: Improve the release process

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10651]
**Description**

Right now we have often several issues with our release process and the related automation. This should be seen as an attempt to improve the situation.

See related proposal https://docs.google.com/document/d/10Hi5UIKGvasx85BOylKp_YFvDeTRN-VZlLERNFmnLj0/edit#

Todos:

- [x] [Migrate CI release pipeline to GHA](https://github.com/camunda/zeebe/issues/10992) @megglos 
- [x] ~Run dry releases as medic (may require changes, thus depends on GHA migration)~
  - [x] https://github.com/camunda/zeebe/issues/11361
- [x] Merge Medic and Release Repositories (related [discussion](https://camunda.slack.com/archives/CSQ2E3BT4/p1668434925679279)) @remcowesterhoud 
  - [x] https://github.com/camunda/zeebe/issues/11054
- [ ] General improvements
  - [x] https://github.com/zeebe-io/zeebe-medic-process/issues/229 
  - [x] https://github.com/zeebe-io/zeebe-medic-process/issues/227 
  - [x] https://github.com/zeebe-io/zeebe-medic-process/issues/230 
  - [x] https://github.com/zeebe-io/zeebe-medic-process/issues/231 
  - [x] https://github.com/zeebe-io/zeebe-medic-process/issues/232 
  - [x] https://github.com/zeebe-io/zeebe-medic-process/issues/233 
  - [x] https://github.com/zeebe-io/zeebe-medic-process/issues/228 
  - [x] https://github.com/zeebe-io/zeebe-medic-process/issues/236 
  - [x] https://github.com/zeebe-io/zeebe-medic-process/issues/237 
  - [x] https://github.com/zeebe-io/zeebe-medic-process/issues/234 
  - [x] https://github.com/zeebe-io/zeebe-medic-process/issues/235 
  - [x] https://github.com/zeebe-io/zeebe-medic-process/issues/238 
  - [ ] https://github.com/zeebe-io/zeebe-medic-process/issues/239

**Comment by megglos** [comment]
@megglos sync with Menski and ZPA

**Comment by remcowesterhoud** [comment]
I have created #11054 as an epic te merge the medic and release repositories.

@Zelldon I notice you have a category to "Merge Medic and Release Zeebe Clusters". The merge of the clusters has already been completed. What's left is really about the repositories itself.

**Comment by Zelldon** [comment]
Thanks @remcowesterhoud I will update that accordingly

**Comment by Zelldon** [comment]
I worked last week extensively on improving our release process automation. This includes restructuring the process models, replacing certain tasks for new REST connectors, automating more, and improving our current user task forms.

This completes the general improvements section.

**Details on what I did:**

[Rework post release process](https://github.com/zeebe-io/zeebe-engineering-processes/pull/264)
![post_release](https://user-images.githubusercontent.com/2758593/210203589-eb7991da-3739-4c9c-8ff0-48aac1aacf16.png)

[Updated all timers, such they trigger always at the same time at the certain day (4 am UTC)](https://github.com/zeebe-io/zeebe-engineering-processes/pull/265)

[Introduce new process to collect data, which can be reused by other models](https://github.com/zeebe-io/zeebe-engineering-processes/pull/266)

![collect_release_data](https://user-images.githubusercontent.com/2758593/210203740-7a511bf5-afea-4597-890f-2373dd727b5e.png)

[Introduce new process to run release, allows to build release candidates during the release as well.
](https://github.com/zeebe-io/zeebe-engineering-processes/pull/267)

[Replace merging to main user task, with REST connector](https://github.com/zeebe-io/zeebe-engineering-processes/pull/269)

[Improve the QA automation, improve forms, process structure and automate more.](https://github.com/zeebe-io/zeebe-engineering-processes/pull/261)

![qa](https://user-images.githubusercontent.com/2758593/210204044-0c6fcdcf-b201-40b9-8147-550146e22986.png)


[Improve zeebe release process, add new REST connectors (replace user tasks), improve forms etc.](https://github.com/zeebe-io/zeebe-engineering-processes/pull/263)

![zeebe_release](https://user-images.githubusercontent.com/2758593/210204169-06c898b4-1cb5-42e3-bc66-aa9dcb119586.png)

**Comment by megglos** [comment]
@Zelldon as agreed let's extract `Run dry releases as medic ` into a separate epic

**Comment by Zelldon** [comment]
Further improvements:

**Comment by Zelldon** [comment]
@megglos I created https://github.com/camunda/zeebe/issues/11361 as separate epic

**Comment by Zelldon** [comment]
I will close this, as most of the improvements are done. One missing part is https://github.com/zeebe-io/zeebe-engineering-processes/issues/239 which is not 100% clear whether we have control over it. 

@koevskinikola maybe you can give feedback whether you encountered this issue https://github.com/zeebe-io/zeebe-engineering-processes/issues/239 if not that is great and we can close it as well.

**Comment by koevskinikola** [comment]
@Zelldon I encountered the issue with the last Zeebe Process Test patch releases, but I belive the issue has been fixed and we just need to confirm with the upcoming patch release.

**Comment by remcowesterhoud** [comment]
It wasn't backported back then so it makes sense it happened in the patches. What I'm wondering is if we still need to click "release" manually or if this happens automatically as well.
