### ISSUE TITLE
[Epic] Support escalation events 

### ISSUE THREAD

**Issue by lzgabel** [camunda/zeebe#10682]
## Description
As a user I want to use escalation events in my process to communicate between parent and sub-processes.

**Describe the solution you'd like**
I can deploy a process that contains escalation throw or end events.

<img width="599" alt="image" src="https://user-images.githubusercontent.com/24605947/195334786-244251bc-6f17-4a52-af49-d786aec3afe8.png">

**Additional context**
The escalation event should behave similarly to Camunda Platform 7. See the related documentation [here](https://docs.camunda.org/manual/7.18/reference/bpmn20/events/escalation-events/).

(BPMN 2.0, chapter 8.4.4, page 81)
<img width="915" alt="image" src="https://user-images.githubusercontent.com/24605947/195336502-1f84d68b-5225-4e8d-a65a-633bb54abbfa.png">

(BPMN 2.0, chapter 10.5.2, page 242)
<img width="896" alt="image" src="https://user-images.githubusercontent.com/24605947/195335760-8b753555-1abe-4e59-9071-95971bd64567.png">

(BPMN 2.0, chapter 10.5.3, page 247)
<img width="921" alt="image" src="https://user-images.githubusercontent.com/24605947/195336859-f7542641-cf77-4fba-9dcf-99faedb47586.png">

(BPMN 2.0, chapter 10.5.4, page 253)
<img width="948" alt="image" src="https://user-images.githubusercontent.com/24605947/195337182-9e6d2423-2d31-404c-b6bb-c804b436e132.png">

**Other Resources**
- [Product Hub](https://github.com/camunda/product-hub/issues/198#issuecomment-1278944197) (internal)
- [C7 docs](https://docs.camunda.org/manual/7.18/reference/bpmn20/events/escalation-events/)

### Broker
* [x] #10688 
* [x] #10762
* [x] #10686
* [x] #10685
* [x] #10684
* [x] #10763
* [x] #10690
* [x] #10890
* [x] #10973

**Not necessary for 1st iteration**
* [ ] #10766

### Exporters/Metrics

- [x] #10767

### Testing

- [x] #10768
- [ ] Add Escalation assertions to Zeebe Process Test

### Documentation
* [x] https://github.com/camunda/camunda-platform-docs/issues/1531

### Modeling

* [x] https://github.com/camunda/camunda-modeler/issues/3318

**Comment by remcowesterhoud** [comment]
Hi @lzgabel! I just want to inform that I will try to help you with this topic. This means that I will also have a look at the preparation and expand on it where necessary. So don't be alarmed when some changes happen to this epic 🙂

**Comment by remcowesterhoud** [comment]
Hey @lzgabel! I wanted to give you a quick update. I am currently still working on the preparation of this topic from our side. It's great that you'd like to contribute to this topic and we are happy to assist you where needed.

As a team hacktoberfest is keeping us pretty busy. As this is a topic that requires more effort from us we do not consider this to be a part of hacktoberfest. This allows us to have focus on the other (smaller) hacktoberfest contributions as well as our other everyday tasks that need to happen.

I will still continue working on the preparation for this topic but I wanted to make you aware of what's going on. I'd still be very happy to continue supporting you on this and get it ready for the 8.2 release 🚀 Just know that it will be a longer process and it will not be something that will be completed before the end of October 😄 

I'm not sure if you already have completed the hacktoberfest challenge (I feel like you do 😛). If not and you want to complete it please make sure you contribute to the issues that are currently labelled with hacktoberfest!

Let me know if you have any questions about this 🙂

**Comment by lzgabel** [comment]
Hi @remcowesterhoud. No need to hurry. Thanks for such a quick status update. ❤️

**Comment by lzgabel** [comment]
Hi @remcowesterhoud. The communication with @skayliu reminded me that do you think we need to add the `escalation` element for the `ProcessInstanceCreation` command with `startInstructions` for this iteration?  Related #9408

**Comment by remcowesterhoud** [comment]
I don't feel the need to add these tests. These tests are supposed to test the concept of activating/terminating the elements. We don't cover each and every element + event type combination we have here. The tests currently verify that we send the activate command for an element. We have other tests making sure the activate command of an escalation is handled properly.

**Comment by nikku** [comment]
@remcowesterhoud As we're planning to support this in our modeling tools could you help us to turn our issue into something meaningful: https://github.com/camunda/camunda-modeler/issues/3318#issuecomment-1330216935.

**Comment by remcowesterhoud** [comment]
Closing this epic as we've completed all the tasks for the 1st iteration. The items that are still open can be handled as separate issues.
