### ISSUE TITLE
Stable hot backup API

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#10809]
This issue is to consolidate the followup tasks from #9606 to make hot backup a stable api

### Feature
- [x] Delete backup API
  - [x] #10208 
  - [x] #9808 
  - [x] #10209
- [x] #10712 
  - [x] #10847
  - [x] #10848
  - [x] #10849
- [x] Improve existing take backup and get backup status api
   - Add specific actionable error codes and detailed failure messages.
   - Ensure apis are aligned to the spec
   - [x] #10967
      - [ ] Add state `INCOMPLETE` to get backup status response
      - [ ] Rename status to state in get backup status response
      - [ ] Return 404 if backup does not exists
      - [ ] Return connection error (code to be defined) if gateway cannot reach one or more brokers
   - [x] #11124
- [x] Publish OpenAPI spec for backup management api
- [x] Update docs
   - https://github.com/camunda/camunda-platform-docs/pull/1568 
- [x] #10846

### Optional improvements
- [ ] #10206
- [ ] #11243
- [ ] #11244

Related to https://github.com/camunda/product-hub/issues/484

**Comment by deepthidevaki** [comment]
Main tasks for this issue is done. Optional improvements will be done adhoc. 

Marking this epic as done :tada:
