### ISSUE TITLE
Breakdown signal event epic into tasks

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#10851]
**Description**

We need to breakdown the signal event epic into technical tasks
- #10777 

This issue mainly exists to be moved around on the [team's project board](https://github.com/orgs/camunda/projects/29/views/1).

**Comment by korthout** [comment]
## Task breakdown
The task breakdown has not yet been completed. This is a work in progress. The tasks may still change.

The tasks are split into 4 different stages, each allowing users to gradually use more of the functionality. This allows us to release the feature even if not all stages are completed.

1. Start new process instances for top-level signal start events
2. Continue processes instances that are awaiting signals
3. Broadcast signal event using throw signal event
4. Broadcast signal with variables payload

### Stage 0: What is already available today
This is the status quo in `8.1.3`:
- I still need to determine this, but I can easily:
  - [ ] Run 8.1.3 locally and use log exporter
  - [ ] Model the scenarios mentioned in the block below and test them by deploying and creating instances for them

This is the status quo in `8.2.0-alpha1`:
- Processes with signal events can already be deployed
  - Top-level signal start events act as top-level none start events
  - Signal event sub-process (interrupting / non-interrupting), is ignored because it can't be activated
  - Signal boundary event (interrupting / non-interrupting), is ignored because it can't be activated
  - Signal intermediate catch events activate, but wait there until terminated (signals cannot be broadcasted yet and the event is not yet subscribed to a signal either)
  - Signal intermediate catch event connected to event based gateway is rejected with message:
	  - Event-based gateway must not have an outgoing sequence flow to other elements than message/timer intermediate catch events.
  - Signal intermediate throw events act as none intermediate throw events
  - Signal end events acts as none end event

**On forwards-compatibility**: It is possible that users have already deployed processes with signal events, and it is also possible that process instances are awaiting signals at intermediate catch events, boundary events and/or event sub-processes. We should consider whether these existing processes and process instances need to subscribe to signals as well. This would cost additional effort, but may be expected by users. However, we can ignore it, because this is likely only possible on the latest alpha, and we don't support upgrading from alpha versions.

:question: **About not yet implemented stages** Should signal throw event raise an incident while stage 3 has not yet been implemented? Currently, it runs straight-through (like an intermediate none throw event). This might be unexpected to users. An incident may help stop the processing at this throw event, and allow it to be retried once stage 3 is available in a future version.

### Stage 1: Start new process instances for top-level signal start events
Next, we'll allow users to broadcast signals using the gRPC API, to start new process instances for the processes that have top-level signal start events.

This may require a migration of all deployed processes with a signal event to subscribe to the signal. We might be able do this on startup as part of loading the process into memory.

- Subscribe processes with top-level signal start events to signals
	- [ ] Introduce new `SignalStartEventSubscription` records, with intents: `CREATED`, `DELETED`
		- Only used to subscribe to signals, not used to track signal receiving
		- The signal subscription record value should consists of:
			- `signalName`
			- `bpmnProcessId`
			- `startEventId`
		- Like any other records, these should be exported. Please follow our handbook.
	- [ ] Adjust the `DeploymentCreateProcessor` to subscribe to new top-level signal start events
		- If process contains top-level signal start event:
			- Write `SignalStartEventSubscription:CREATED`
				- Event applier for `SignalStartEventSubscription:CREATED` puts subscription in DbSignalStartEventSubscriptionState
				- DbSignalStartEventSubscriptionState should have methods:
					- `visitBySignalName`
					- `visitByProcessDefinitionKey`
	- [ ] Don't allow top-level signal start events to act as none start event
		- Change `ExecutableCatchEvent.isNone()` implementation
			- Requires adjustment of `CatchEventTransformer` to transform signal catch events
- Throw a signal using the gRPC API
	- [ ] Introduce new `Signal` records, with intents: `Broadcast`, `Broadcasted`
		- The signal record value should consists of:
			- `signalName`
			- `relaying` (boolean flag)
				- if true, the signal is received on this partition first and needs to be relayed to other partitions
				- if false, the signal was relayed by another partition and should not be relayed to other partitions
			- optionally `variables`
	- [ ] Introduce new `Signal:Broadcast` command processor
		- Writes a `Signal:Broadcasted` event indicating that the command was processed successfully, otherwise the command is rejected. No event applier is needed for it.
		- If `relaying` is `true`:
			- Write `Signal:Broadcast` command on other partitions, with `relaying` is `false`
			- For each `SignalStartEventSubscription` matching the `signalName`, uses `DbSignalStartEventSubscriptionState.visitBySignalName`:
				- Starts an instance of the latest version of the process defined by `bpmnProcessId`, at start event `startEventId` 
	- [ ] Introduce new broadcast signal RPC in gateway-protocol
		- The RPC takes a message containing:
			- `signalName`
			- optionally `variables`
		- Implementation should write a `Signal:Broadcast` command with `relaying` is `true` to a partition leader
			- Can start with deployment partition
			- Round-robin signal broadcasts from gateway (optimization, stretch goal)
	- [ ] Introduce java-client and go-client implementation of new RPC
		- Should be straightforward
- Unsubscribe older versions of processes from signals when a new version is deployed
	- [ ] Adjust the `DeploymentCreateProcessor` to unsubscribe for signals of previous version of process
		- uses `DbSignalStartEventSubscriptionState.visitByProcessDefinitionKey` to find these subscriptions
		- Write `SignalStartEventSubscription:DELETED`
			- Event applier for `SignalStartEventSubscription:DELETED` removes subscription from DbSignalStartEventSubscriptionState

Alternatively, a `Received` intent could be added to the `Signal` records that would be written for the signal catch events that receive the signal. However, I've chosen to not include this, because there are a few issues with this:
- This record value should contain a list of element instance keys that received the signal, but for top-level signal start event we would have to await the start event to be activated before we have a key available. This is currently not possible unless we pre-fill the key for the start event which is a lot of extra code
- we can already find the affected instances through the source record positions of the follow-up commands, so I don't see a direct need for it
- it might be a lot of data to write in a record, further filling up the record batch. This is especially true if the variables are written in this record again, or if this record is written for each matching subscription

**On relaying and process distribution**: The `SignalSubscription` does not have to be distributed over the partitions. The process that it belongs to is already distributed because of deployment distribution. If the process hasn't been distributed to a partition receiving a signal that must be relayed, then the partition can relay the signal to other partitions but it simply won't start a new process instance. Note that the relayed signals don't start new instances for top-level signal start events.

### Stage 2: Continue processes instances that are awaiting signals

- ... TBD

### Stage 3: Broadcast signal event using throw signal event

- ... TBD

### Stage 4: Broadcasting signals with variables payload (stretch goal)

- ... TBD

### Other

- Documentation
- Testing
- Exporters and Metrics

### Out of scope

- Throwing a signal using a Job Worker. This was discussed, but we think we don't need it if we support signal throw events (stage 3). It does not make sense to put effort into an additional stage, before stage 3 is completed.

**Comment by korthout** [comment]
Initial feedback from team on task breakdown:
- The stages make sense. Ee should focus on the breakdown of stage 1 first.
- We do not need 2 different subscription records for different signal catch events: `SignalStartEventSubscription` and `SignalSubscription` could be merged into a single `SignalSubscription`.
  - Note that this means that the SignalSubscription record value will contain a combination of the data
  - Note that this means that the DbSignalSubscriptionState needs to provide methods to visit signal by signalName in 2 different ways (for top-level signal start events, and for other signal catch events)
- We need a way to acknowledge the relaying of signal
  - If the relay does not get acknowledged, we need to retry relaying it. This will require a revamp of the Signal record.
- (stretch goal) We should try to find a way to make signal relaying idempotent
  - this may be hard
- (stretch goal) We should check if the performance is impacted if we introduce signal subscription `CORRELATED` or `TRIGGERED` intents. This would improve the visibility/traceability of signals.

**Comment by korthout** [comment]
>(stretch goal) We should try to find a way to make signal relaying idempotent

What follows is an attempt to make the processing of `Signal:Distribute` commands idempotent 

To detect that the command is being retried (and that we've already processed a copy of this command before), we'll need to do some additional bookkeeping: keep track of the specific signals that have been distributed to this partition before. For example, we could store each unique signal key that has been broadcasted/distributed.

The problem with this approach is that it would require an ever-growing list of keys of signals. Which means an ever-growing storage need.

An alternative is to keep track of only the latest distributed signal for each signal name and each partition id. 

For example, a signal is distributed to partition 3. Partition 3 stores the signal key in a table entry for the partition id (encoded in the key) and the signal name. Then, another signal is distributed from the same partition but with a different signal name. Then another signal is distributed from another partition, but with the same signal name. 

On partition 3:
| partition id | signal name | signal key | 
|--|---|----------------|
| 1 | my-signal | 10000000 |
| 1 | another-signal | 10000001 |
| 2 | my-signal | 10000000 |

Then finally, the distribution of the secondary signal (`another-signal` from partition 1 with key 10000001) is retried. But, partition 3 can detect that this is a duplicate and can reject the command. In addition to its rejection, it should tell partition 1 that it has already succeeded, so it should also send a `Signal:Complete` command to partition 1.

We're only interested in storing a single key per partition and per signal name, because for that specific signal name that partition may be retrying the distribution. Due to the asynchronous nature of the streamprocessors, it can successfully distribute signals of other names. But when a specific signal is broadcasted twice (twice the same name), then it's enough to distribute the last one of those signals. There is no need to continue the awaiting instances twice, because they will all have been continued already.

**Comment by korthout** [comment]
@saig0, @remcowesterhoud, @koevskinikola I've assigned you to this topic to clarify the review of this breakdown

**Comment by korthout** [comment]
Feedback from the last review round:
- Stage 1 is ready
- [x] Adjust versions in stage 0 (they didn't change)
- [ ] Check whether the hot backups solution interferes with the idea of distributing the signal from random partitions
- [x] Document that only the latest version of a process is subscribed to the top level signal start event
- Do we want to deprecate DeploymentDistribution records and generalize the concept?
  - this may be needed if we add more concepts that need to be distributed
  - a follow-up question: can we remove the DeploymentDistribution records after deprecating them?
    - we could keep track of versions reaching end of log, to make sure there are no unprocessed DeploymentDistribution records on the log
- [x] Add write fully_distributed to broadcast command processor
- [x] Add write Distributed event to distribute command processor
- [x] Add event appliers to stage 2 step 1
- [ ] The idea was raised to write Signal:Broadcast in response to Signal:Distrbute command. We should consider this.

**Comment by korthout** [comment]
Regarding whether the hot backups solution might interfere with the idea of distributing the signal from random partitions: No, this won't interfere.

Hot backups are designed to fundamentally solve the consistent checkpoints problem, and it does not treat partition 1 in any special way.

However, we should consider versioning of a distributed entity (e.g. versioning of processes). Only a single partition should control the versioning of a unique entity. Otherwise, 2 partitions might hand out the same version for two different versions of the same entity. For example, we can hash the BPMN Process ID to a specific partition id and allow that partition to control the versioning of the process with that BPMN Process ID.

**Comment by korthout** [comment]
>The idea was raised to write Signal:Broadcast in response to Signal:Distrbute command. We should consider this.

With #11456 we will directly write the `Signal:Broadcast` command to the other partition. No `Signal:Distribute` command will exist.

**Comment by korthout** [comment]
Now that #11456 is resolved, I've finally taken the time to continue this breakdown.
