### ISSUE TITLE
Replace Dispatcher

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10906]
We have explored a POC for replacing the dispatcher in #10691. Since we were happy with the results, here's the plan to get a production ready dispatcher replacement.

# API changes

All log stream writers (think `ProcessingStateMachine`, `CommandApiRequestHandler`, and `InterPartitionCommandReceiver`) use something like the following interface:
 
```java
interface LogStreamWriter {
  ActorFuture<Position> tryWrite(RecordBatch batch);
  ActorFuture<Position> tryWrite(Record record);
}
```

# Implementation

We start by introducing this interface and changing writers accordingly. At first, this interface is implemented by writing to the dispatcher.
Then we swap out the implementation by replacing the dispatcher with a much simpler system, consisting of a `Sequencer`, `Serializer` and `Appender`.

`Sequencer` is an actor that implements a many-to-one queue that assigns and returns the position of written records.
`Serializer` serializes records, for now including the old dispatcher framing
`Appender` reads from the `Sequencer`, serializes using the `Serializer` and then writes to the journal.

We may want to introduce more components later on, such as a dedicated component that takes care of flow control.

# Breakdown
## Replacing the dispatcher
- [x] #10918
- [x] Refactor `LogStreamWriter`
  - [x] #10923
  - [x] #10924
- [x] #10919
- [x] #10920
- [x] #10921

## Cleanup
- [x] Error handling when writing batches larger than the segment size
- [x] #10922
- [x] Don't peek from sequencer
- [x] #11128
- [x] #11129

## Explore
- [ ] #11167
- [ ] Batch entries before appending
- [x] #11264
- [ ] Lock-free sequencer

**Comment by npepinpe** [comment]
I would add another thing: push down serialization even further, all the way to the journal. With @megglos's changes to the Raft log append API, we can now just pass `BufferWriter`, so the sequenced batch could be a `BufferWriter` itself, so we only serialize directly to the mapped buffer, no more intermediate serialization anywhere.

**Comment by oleschoenburg** [comment]
@npepinpe Yep, @deepthidevaki suggested the same. I've put it in the explore section  as "Remove copy during batch serialization" already.

**Comment by npepinpe** [comment]
Another to explore:

- Get rid of the lock + thread-safe data structure: either use a single thread safe data structure, or a lock + non-thread safe data structure
