### ISSUE TITLE
Multi-arch docker images (arm64/amd64)

### ISSUE THREAD

**Issue by megglos** [camunda/zeebe#10986]
**Is your feature request related to a problem? Please describe.**
See product epic [ARM docker images for Camunda 8 - development purposes](https://github.com/camunda/product-hub/issues/222) 

**Describe the solution you'd like**
MUST build & publish arm64 docker images of zeebe using a [multi-arch build](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) producing `linux/amd64` and `linux/arm64`.
SHOULD images for each architecture are at least smoke tested to ensure they are operational

**Describe alternatives you've considered**
none

**Breakdown**
- [x] [add build support of multi-arch images for amd64 and arm64](https://github.com/camunda/zeebe/issues/11000) 
- [x] [extend the GHA ci workflow with docker multi-arch smoke tests](https://github.com/camunda/zeebe/issues/11020)
- [x] [extend the GHA ci workflow job `deploy-docker-snapshot` to build and deploy multi-arch images for amd64 and arm64](https://github.com/camunda/zeebe/issues/11079)
- [x] #11286
- [x] #11189
- [x] #11318

**Additional context**
- [product epic - ARM docker images for Camunda 8 - development purposes](https://github.com/camunda/product-hub/issues/222)
- [POC for multi-arch build and test by @npepinpe](https://github.com/camunda/zeebe/pull/10069)
- [Community PR to make it easier to build arm64 images locally](https://github.com/camunda/zeebe/pull/10725)
- [feature request from community](https://github.com/camunda/zeebe/issues/6155)
- [PR Draft on adding an ARM runner pool](https://github.com/zeebe-io/infra/pull/6/files)

**Comment by npepinpe** [comment]
Prototype PR to have ARM64 runners for CI: https://github.com/zeebe-io/infra/pull/6. This would simplify building and testing the images, as the prototype above is quite slow when running everything through qemu (and, I would say, more complex).

Additionally, you could then extend the existing smoke-test job matrix to include running smoke tests on these. This is slightly out of scope here, since this is testing the local bare metal build, but still has value for macOS contributors. Perhaps a stretch goal, though it's a pretty low hanging fruit, I think.

**Comment by akkie** [comment]
Maybe not the right place to ask here, but is it also considered to release ARM images for the ui applications like Operate and Optimize?

**Comment by megglos** [comment]
Hey @akkie, yes that's considered issues for each of those applications are getting created on each of the repos, e.g. https://github.com/camunda/operate/issues/3674 for operate

**Comment by namero999** [comment]
Seems like the only open subtask for this ticket is documentation. Is there any way we can preview the arm images while we wait for this ticket to be closed?

**Comment by npepinpe** [comment]
The SNAPSHOT images already support both architectures. The next release (8.2.0), scheduled around April, will also have both architectures. I'm not aware of any plans to backport this, but I could be wrong (@megglos will know better)

**Comment by namero999** [comment]
Thanks for the info!

I've modified my `docker-compose.yml` file to point to `image: camunda/zeebe:SNAPSHOT` (both zeebe and operate)... will test, but the containers seems to fire up without any warning.

**Comment by megglos** [comment]
> The SNAPSHOT images already support both architectures. The next release (8.2.0), scheduled around April, will also have both architectures. I'm not aware of any plans to backport this, but I could be wrong (@megglos will know better)

@namero999 the upcoming 8.2.0-alpha2 release (Jan 9th) already offers arm64 images.
We have no plans of back-porting this yet.
