### ISSUE TITLE
[EPIC] Merge medic and release repositories

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#11054]
## Description
In order to improve reusability between our internal processes we have decided to merge out [medic repo](https://github.com/zeebe-io/zeebe-medic-process) and [release repo](https://github.com/zeebe-io/zeebe-releaser) into a single repository containing all of our internal processes. For reasons why and more information please refer to the related [slack discussion](https://camunda.slack.com/archives/CSQ2E3BT4/p1668434925679279)

### Breakdown
In order to achieve this we need to take a few steps. My suggestion here is that we keep the medic repo and merge the release repo into this. Afterwards we will rename the repo to a more suiting generic name.

**Moving of files**
Before each of these tasks we should announce a code freeze in the release repo and make sure changes to the relevant files have been merged. Otherwise we could lose changes during copying.

- [x] https://github.com/zeebe-io/zeebe-releaser/issues/152
- [x] https://github.com/zeebe-io/zeebe-releaser/issues/153
- [x] https://github.com/zeebe-io/zeebe-releaser/issues/154
- [x] https://github.com/zeebe-io/zeebe-releaser/issues/155
- [x] https://github.com/zeebe-io/zeebe-releaser/issues/156

**Making it whole**
- [x] https://github.com/zeebe-io/zeebe-medic-process/issues/204
- [x] https://github.com/zeebe-io/zeebe-medic-process/issues/205
- [x] https://github.com/zeebe-io/zeebe-medic-process/issues/206
- [x] https://github.com/zeebe-io/zeebe-releaser/issues/157

**Cleanup**
- [ ] Remove duplicate slack id DMN (I will create an issue later. I feel like it would be confusing to have at this time)
- [x] https://github.com/zeebe-io/zeebe-releaser/issues/158

**Finally**
- [ ] Move shared repo to Camunda organisation (this makes it easier to add issues from these project to our board)

**Comment by remcowesterhoud** [comment]
We need to make sure we don't cause trouble doing this when changes in #10651 are in progress.

**Comment by remcowesterhoud** [comment]
@remcowesterhoud Follow-up as an extra task: consider moving the internal process to the Camunda org

**Comment by remcowesterhoud** [comment]
Closing this as merge is completed and any open issues are ready to be picked up.
