### ISSUE TITLE
Start new process instances for top-level signal start events

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#11194]
This is stage 1 of the umbrella epic:
- #10777 

## Stage 1: Start new process instances for top-level signal start events
In the first stage, it will be possible for users to broadcast signals using the gRPC API, starting new process instances for the processes that have top-level signal start events.

<img width="815" alt="Model highlighting that only the top-level signal start event will be supported at this stage, the other signal events are marked as not yet supported" src="https://user-images.githubusercontent.com/3511026/200788671-3e6faaa3-0877-458a-aabe-c977bc965697.png">

Signal broadcasts arriving in the gateway must be written to a partition leader. The partition leader needs to start instances for each top-level signal start event that match the name of the broadcasted signal. The signal does not yet have to be distributed to the other partitions.

A process is subscribed to a signal using a new `SignalSubscription` record.

<details>
<summary>Subscribe processes with top-level signal start events to signals</summary>
<p>

- [ ] Introduce new `SignalSubscription` records, with intents: `CREATED`, `DELETED`
	- Only used to subscribe to signals, not used to track signal receiving
	- The signal subscription record value should consist of:
		- `bpmnProcessId` - The id of the process in the bpmn model
		- `processDefinitionKey` - The key of the deployed process
		- `catchEventId` - The id of the signal catch event
		- `signalName` - The name of the signal (taken from the name of the signal in the BPMN model)
	- Like any other records, these should be exported. Please follow our [developer handbook entry on adding new records](https://github.com/camunda/zeebe/blob/main/docs/developer_handbook.md#how-to-create-a-new-record)
- [ ] Adjust the `DeploymentCreateProcessor` to subscribe to new top-level signal start events
	- If the deployed process contains a top-level signal start event:
		- Write `SignalSubscription:CREATED`
			- Event applier for `SignalSubscription:CREATED` puts subscription in `DbSignalSubscriptionState`
			- `DbSignalSubscriptionState` should have methods:
				- `visitBySignalName` (should provide parameter that informs whether this is a top-level start event or not)
				- `visitStartEventSubscriptionsByProcessDefinitionKey` (only visits the subscriptions for top-level start events)
				- `visitByElementInstanceKey` (only visits the subscriptions for catch events existing in process instances; won't be used in this stage yet)
- [ ] Don't allow top-level signal start events to act as none start event
	- Change `ExecutableCatchEvent.isNone()` implementation
		- Requires adjustment of `CatchEventTransformer` to transform signal catch events

</p>
</details>

<details>
<summary>Broadcast a signal using the gRPC API</summary>
<p>

- [ ] Introduce new `Signal` records, with intents: `Broadcast`, `Broadcasted`
	- The signal record value should consist of:
		- `signalName`
		- optionally `variables`
		- Like any other records, these should be exported. Please follow our [developer handbook entry on adding new records](https://github.com/camunda/zeebe/blob/main/docs/developer_handbook.md#how-to-create-a-new-record)
- [ ] Introduce new `Signal:Broadcast` command processor
	- Writes a `Signal:Broadcasted` event indicating that the command was processed successfully, otherwise the command is rejected. No event applier is needed for it.
	- For each `SignalSubscription` matching the `signalName`, uses `DbSignalSubscriptionState.visitBySignalName`:
		- If related catch event is a top-level start event:
			- Start an instance of the latest version of the process defined by `bpmnProcessId`, at start event `catchEventId` 
- [ ] Introduce new broadcast signal RPC in gateway-protocol
	- The RPC takes a message containing:
		- `signalName`
		- optionally `variables`
	- Implementation should write a `Signal:Broadcast` command to a partition leader
		- Can start with deployment partition
		- Round-robin signal broadcasts from the gateway (optimization, stretch goal)
- [ ] Introduce java-client and go-client implementation of new RPC
	- Should be straightforward

</p>
</details>

<details>
<summary>Unsubscribe older versions of processes from signals when a new version is deployed</summary>
<p>

- [ ] Adjust the `DeploymentCreateProcessor` to unsubscribe for signals of the previous version of the deployed process
	- uses `DbSignalSubscriptionState.visitStartEventSubscriptionsByProcessDefinitionKey ` to find these subscriptions (only the ones for top-level start events should be used)
	- Write `SignalSubscription:DELETED`
		- Event applier for `SignalStartEventSubscription:DELETED` removes the subscription from DbSignalSubscriptionState

</p>
</details>

<details>
<summary>Documentation</summary>
<p>

The feature needs to be documented:
- [ ] Document the concept of signals
- [ ] Document Signal Start Events under `Components > Modeler > BPMN > Events > Signal Events`
  - Make sure to note that only the latest version of a process is subscribed to the top level signal start event
- [ ] Mark the Normal Signal Start Event as covered in the BPMN-coverage
- [ ] Document the new RPC in the [Zeebe API](https://docs.camunda.io/docs/apis-clients/grpc/)

</p>
</details>

#### Discussions

<details>
<summary>We won't add a `Received` intent to `Signal` records</summary>
<p>

Alternatively, a `Received` intent could be added to the `Signal` records that would be written for the signal catch events that receive the signal. However, I've chosen not to include this because there are a few issues with this:
- this record value should contain a list of element instance keys that received the signal, but for top-level signal start events, we would have to await the start event to be activated before we have a key available. This is currently not possible unless we pre-fill the key for the start event, which is a lot of extra code
- we can already find the affected instances through the source record positions of the follow-up commands, so I don't see a direct need for it
- it might be a lot of data to write in a record, further filling up the record batch. This is especially true if the variables are written in this record again or if this record is written for each matching subscription

</p>
</details>

<details>
<summary>The `SignalSubscription` does not have to be distributed over partitions</summary>
<p>

The `SignalSubscription` does not have to be distributed over the partitions. The process that it belongs to is already distributed because of deployment distribution. If the process hasn't been distributed to a partition receiving a signal that must be relayed, then the partition can relay the signal to other partitions, but it simply won't start a new process instance. Note that the relayed signals don't start new instances for top-level signal start events.

</p>
</details>

<details>
<summary>Signal name as an expression is a stretch goal</summary>
<p>

By default, the signal name is a static value. This adds value to most users. Expression support for the signal name can be added later. As in other places, this would simply require the value to be prefixed with the expression marker `=`. See stage 4.

</p>
</details>

<details>
<summary>Broadcasting signals with variables payload is a stretch goal</summary>
<p>

The `Signal` record value will already be made ready to receive variables, but we'll leave them out of the gRPC message. This way, it will not yet be possible to pass variables along with the signal, but we'll be able to extend this in the future. Variables are useful but do not have to be part of the first iteration of this feature. See stage 4.

</p>
</details>

**Comment by korthout** [comment]
Closing this as completed, only documentation is leftover on Zeebe's side:
- https://github.com/camunda/zeebe/issues/11198
