### ISSUE TITLE
Prototype push-based job activation pipeline

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#11233]
**Description**

In order to get feedback as early as possible on the performance gains, we will create a prototype of the push-based job activation pipeline described in #11232.

Comparison between the pull and push approach will be based on:

- Ignoring failure modes (e.g. leader changes, no crashes, etc.)
- Ignoring edge cases (e.g. network issues if possible)
- Ignoring backfilling (the workers are always there)

Essentially, we want to compare the best case scenario for the first step, i.e. the happy path.

**Comment by npepinpe** [comment]
Let's close the year with a short visual update. I'm currently running two types of load tests. For each, I run two clusters: one using my prototype (the push approach), and one using our current SNAPSHOT (the poll approach).

For each cluster, the set up is our usual benchmark set up:

- 3 brokers
- 3 partitions, replication factor 3
- 2 gateways
- 4 workers/job processors

Each broker gets 1.3 CPU, and up to 4Gi memory. Each gateway gets 1 CPU. I increased the number of management threads for the push approach to 2, since it now does more things in parallel, but I don't expect this would affect comparison.

Each worker completes jobs after an artificial delay of 50ms. Brokers run on isolated VMs to avoid interference from other pods and simplify comparison. All nodes run in the same k8s namespace and cluster, meaning network latency is quite small. In each case, the leaders were rebalanced so they would be evenly distributed across nodes.


# Single task workload
The first type of workload is the single task process, which is simply:

```mermaid
stateDiagram-v2
  direction LR
  [*] --> Task
  Task --> [*]
```

We start 75 PI/s.

| | Push | Poll |
|-|------|------|
| |![job-push-single-task-latency](https://user-images.githubusercontent.com/43373/208741346-4b7bc774-68fe-4897-9578-a4f1a5d361ed.png)|
![job-poll-single-task-latency](https://user-images.githubusercontent.com/43373/208741401-a66755bf-7035-4a4d-ab3b-c7352186f9df.png)
|

As you can see, the job push latency is around 100-200ms, with a p99 between 500ms to 1s. The poll latency is on average 2.5s, with a p99 around 5s. **The average latency of the push approach is then about 10 times smaller than that of the poll**.

I did not test if we could push throughput past 75 PI/s. I didn't observe any outstanding memory or CPU usage when comparing approaches.


# Task chain workload
The second type of workload is a 10-tasks sequential chain process, which is:

```mermaid
stateDiagram-v2
  direction LR
  [*] --> Task1
  Task1 --> Task2
  Task2 --> Task3
  Task3 --> Task4
  Task4 --> Task5
  Task5 --> Task6
  Task6 --> Task7
  Task7 --> Task8
  Task9 --> Task10
  Task10 --> [*]
```

We start 20 PI/s. Going higher would trigger both clusters to degrade exponentially, which I think points to different issues.

| | Push | Poll |
|-|------|------|
| |![job-push-task-chain-latency](https://user-images.githubusercontent.com/43373/208746486-03820fd0-6820-444e-a450-36fce9e90c0c.png)|![job-poll-task-chain-latency](https://user-images.githubusercontent.com/43373/208746536-ae382ac5-b52f-4a8a-86e5-55e811bf4d0d.png)|

As you can see, the job push latency is around 100-200ms, with a p99 between 500ms to 1s. The poll latency is on average 2.5s, with a p99 around 5s. **The average latency of the push approach is then about 10 times smaller than that of the poll**.


# Job push metrics

I added a new dashboard with many job push metrics. You can check it out [here](https://grafana.dev.zeebe.io/d/a13i-2cVz/job-push?orgId=1&var-cluster=zeebe-long-running&var-namespace=all&var-pod=All&refresh=5s)

There's help text for all metrics, I hope it's understandable. Interestingly enough, we now see that with job push, even with the sequential chain, the lifetime is mostly just the artificial completion time plus processing the complete command.

# Learnings

So far, there have been a few learnings:

- The transport layer (NettyMessagingService) is poorly optimized. My initial approach, where I used the common messaging service, caused extremely poor performance by tripling the Raft commit latency. Using separate messaging services solved this. **This is not an ideal solution long term, as it increases how much management around ports we have to do, and it's not clear that our transport layer couldn't be optimized**.
- The benchmark application/worker is not optimized, and there's additional time spent in there that is not the artificial completion delay (up to a third of the job lifetime!), so it skews benchmarks to some extent.
- Actual network speed has not been an issue at all, but everything is deployed in the same cluster. So far, pushing is negligible on the system.
- Possibly reactivating the job will be non-negligible, as we've seen under high load it adds up. We should explore ways to optimize activating a job and fetching its variables.
- Gossip is a nice way to detect nodes and failures, but a poor way to maintain state about open streams, as it requires too much data to be transferred (which is all plaintext for now). It's good for the prototype, not for long term.
- Long living gRPC streams seemed pretty solid, running for hours on end. Note however that there is no ingress in our tests, so it may be that some configuration is needed. 
- The Zeebe client is not architectured to deal with long living streams, but rather with request/response style of commands, and it's awkward to implement a stream API.

**Comment by npepinpe** [comment]
So next steps would be to evaluate the following issues/answer open questions:

- [ ] Figure out how we can use only a single messaging port to avoid the management overhead of adding ports
- [ ] Decide on when jobs should be pushed: immediately on processing, or after once the follow up events have been committed.
- [ ] How will pushing behave on a slow/poor network with a naive approach?
- [ ] How to adapt the Zeebe client API to long living streams?
- [ ] Could we hide the new API behind the existing worker API (with a feature flag toggle), making the transition seamless?

**Comment by npepinpe** [comment]
Regarding slow networks, I think this is something we can look into a second iteration, as that would cover the transport part, but I don't think it would change the overall approach much.

I will wait to discuss with the ZPA team regarding the client adaptations.

We'll deal with the sensitivity to leader changes when we tackle failure handling.
