### ISSUE TITLE
[EPIC] Implement Batch processing

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11416]
## Description

Implement batch processing to reduce the influence of commit latency on processing execution latency.

### Situation:

In Zeebe we use something called [stream processing](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md) to drive the process execution. This means we have divided our process execution into several commands our Engine can understand, the commands are requests to change a certain state (e.g. of a process instance). When these commands are processed the resulting state changes are reflected as events. In order to drive further the process execution there are also follow-up commands produced.

![theory1](https://user-images.githubusercontent.com/2758593/212688721-83f108bc-381c-4720-9a44-500c9cb6c26f.png)

### Problem:

Right now the stream processing is really fine granular. This means we have for each element and state in a BPMN process model command to change the state. If we start a process instance, we first create the "ground construct" and produce a follow-up command to drive the execution later further. This of course allows us to run many instances in "parallel" since we can continue each of them in small steps. This allows a higher throughput at cost of process execution latency, which might be in some cases problematic. Especially if the network latency is high.

To be more specific each small batch (of commands and events) has a certain overhead since we have to wait for replication and commit until we can process the next command.  Right now the commit latency has a high impact on the process execution time.

As you can see in the picture below, each command before it can be processed needs to be replicated (and committed).

The following picture tries to show (in a naive way) that each command needs to be replicated (and committed) before it can be processed. This includes follow-up commands.
![theory2](https://user-images.githubusercontent.com/2758593/212688999-6d3b04f5-f5ea-4ddd-aecf-432c6d93134f.png)

### Idea:

Instead, to produce small batches of commands and events, every time we process a command, we want to process a process instance until we reach a wait state. Wait state can be defined as no further commands being produced to further drive the execution. This means we process all follow-up commands directly, collect all results, and write them as batches to the log.

With direct processing, the commit latency impact will be reduced. 

### Break down

- [x] https://github.com/camunda/zeebe/pull/11502 (Iterate over Side effects handling, is problematic for batch processing right now) 
- [x] https://github.com/camunda/zeebe/issues/11504
- [x] https://github.com/camunda/zeebe/issues/11505
- [x] https://github.com/camunda/zeebe/pull/11527
- [x] https://github.com/camunda/zeebe/pull/11528
- [x] https://github.com/camunda/zeebe/pull/11530
- [x] https://github.com/camunda/zeebe/pull/11531 (Increase default loop count to 100, involves fixing failing tests)
- [x] https://github.com/camunda/zeebe/issues/11545
  - [x] Add configuration, allows users to turn it off and testing with different values
- [x] Add metrics for record batches
  - [x] https://github.com/camunda/zeebe/issues/11546
- [x] https://github.com/camunda/zeebe/issues/11539

### POC

We have implemented successfully an POC https://github.com/camunda/zeebe/pull/11368 and measured the improvements in our recent hackweeks. The results were quite promising.

In the POC we saw that for example a simple workflow like:

![diagram_1](https://user-images.githubusercontent.com/2758593/212690122-4d2d7c5f-b421-4f7a-b2fd-373b57a370d2.png)

Can be executed in 2-3 batches (3 if you include the job activation), before it was 8-9 commands (= commits).

```
C CREA      CREATE            - #05-> -1  -1 - new <process "process"> (default start)  (no vars)
C PI        ACTIVATE          - #06->#05 K03 - PROCESS "process" in <process "process"[K03]>
E CREA      CREATED           - #07->#05 K04 - new <process "process"> (default start)  (no vars)
E PI        ACTIVATING        - #08->#05 K03 - PROCESS "process" in <process "process"[K03]>
E PI        ACTIVATED         - #09->#05 K03 - PROCESS "process" in <process "process"[K03]>
C PI        ACTIVATE          - #10->#05  -1 - START_EVENT "start" in <process "process"[K03]>
E PI        ACTIVATING        - #11->#05 K05 - START_EVENT "start" in <process "process"[K03]>
E PI        ACTIVATED         - #12->#05 K05 - START_EVENT "start" in <process "process"[K03]>
C PI        COMPLETE          - #13->#05 K05 - START_EVENT "start" in <process "process"[K03]>
E PI        COMPLETING        - #14->#05 K05 - START_EVENT "start" in <process "process"[K03]>
E PI        COMPLETED         - #15->#05 K05 - START_EVENT "start" in <process "process"[K03]>
E PI        SEQ_FLOW_TAKEN    - #16->#05 K06 - SEQUENCE_FLOW "sequenc..2029048" in <process "process"[K03]>
C PI        ACTIVATE          - #17->#05 K07 - SERVICE_TASK "task" in <process "process"[K03]>
E PI        ACTIVATING        - #18->#05 K07 - SERVICE_TASK "task" in <process "process"[K03]>
E JOB       CREATED           - #19->#05 K08 - K08 "id-5942aa87-26c8-4bac-b937-ee74bb9aa928" @"task"[K07] 3 retries, in <process "process"[K03]> (no vars)
E PI        ACTIVATED         - #20->#05 K07 - SERVICE_TASK "task" in <process "process"[K03]>

C JOB_BATCH ACTIVATE          - #21-> -1  -1 - "id-5942aa87-26c8-4bac-b937-ee74bb9aa928" max: 10
E JOB_BATCH ACTIVATED         - #22->#21 K09 - "id-5942aa87-26c8-4bac-b937-ee74bb9aa928" 1/10
                K08 "id-5942aa87-26c8-4bac-b937-ee74bb9aa928" @"task"[K07] 3 retries, in <process "process"[K03]> (no vars)

C JOB       COMPLETE          - #23-> -1 K08 - K08 -1 retries, in <process ?[?]> (no vars)
E JOB       COMPLETED         - #24->#23 K08 - K08 "id-5942aa87-26c8-4bac-b937-ee74bb9aa928" @"task"[K07] 3 retries, in <process "process"[K03]> (no vars)
E PROC_EVNT TRIGGERING        - #25->#23 K10 -  @"task"[K07] in <process K01[K03]> (no vars)
C PI        COMPLETE          - #26->#23 K07 - SERVICE_TASK "task" in <process "process"[K03]>
E PI        COMPLETING        - #27->#23 K07 - SERVICE_TASK "task" in <process "process"[K03]>
E PI        COMPLETED         - #28->#23 K07 - SERVICE_TASK "task" in <process "process"[K03]>
E PI        SEQ_FLOW_TAKEN    - #29->#23 K11 - SEQUENCE_FLOW "sequenc..1573237" in <process "process"[K03]>
C PI        ACTIVATE          - #30->#23 K12 - END_EVENT "end" in <process "process"[K03]>
E PI        ACTIVATING        - #31->#23 K12 - END_EVENT "end" in <process "process"[K03]>
E PI        ACTIVATED         - #32->#23 K12 - END_EVENT "end" in <process "process"[K03]>
E PI        COMPLETING        - #33->#23 K12 - END_EVENT "end" in <process "process"[K03]>
E PI        COMPLETED         - #34->#23 K12 - END_EVENT "end" in <process "process"[K03]>
C PI        COMPLETE          - #35->#23 K03 - PROCESS "process" in <process "process"[K03]>
E PI        COMPLETING        - #36->#23 K03 - PROCESS "process" in <process "process"[K03]>
E PI        COMPLETED         - #37->#23 K03 - PROCESS "process" in <process "process"[K03]>

```

#### POC-Benchmarking

We have run several benchmarks with our POC, for example, one where we had a high network latency (35 ms one-way) and a more or less complex workflow. With our current snapshot, we were able to execute a process instance from start to end in ~5second (p99) with batch processing in ~2.5 seconds (p99).

![result](https://user-images.githubusercontent.com/2758593/212690849-2140f050-1eab-433c-9a39-39efeca4e76f.png)

#### POC - Hack week learnings

We documented the hack week and POC in this [document](https://docs.google.com/document/d/1fZh5tDjYkHYm0dz918vEg1GTcEhjDaTyPVLp5RDTLRk/edit#heading=h.4m9xavxj77wu) and [here based on investigating the test](https://camunda.slack.com/archives/C04K3GJEZU2/p1674044857765239).

##### What to do when we reach the `maxMessageSize` limit

When we process a lot of follow-up commands and produce more and more content, we might get into a situation where we reach our maximum batch size (=maxMessageSize). This can happen because of using a big multi-instance collection, or fork bombs, or something else.

During a discussion with @oleschoenburg, he had a good idea that we can write at the end of the batch a command which we mark as not processed yet (maybe not setting the source position or using a different flag). Right now we use the source-position as indicate of not processing commands twice. We can write the batch with the command at the end (still in the limits) and later can continue with the execution of the process instance. 

BTW similarly we can handle multi-instance (but this needs to be done on the engine side) to mark the multi-instance as not completely processed, and mark for example 100/500 instances created via a command. On the next processing, we continue.

**Update:**

@oleschoenburg run a POC https://github.com/camunda/zeebe/pull/11469 where we limit the processing to a specific count. We mark records as needs processing per default and can set the value to false. The value is set in the log entry descriptor on an unused field. 

If we still reach the batch limit we rollback and process before that failing command, commit everything and write the command as follow up. This allows us to handle the command separately in a batch.

##### Do we need to write commands?

This is something we have discussed in the hack week as well, and afaik it is not really used by any web apps. Still the current exporters can rely on commands. This would be a breaking change. But theoretically, we could remove the follow-up commands from the results, after being processed and only write follow-up commands to further continue processing later.

##### Can processing on process instance block others?

Normally this shouldn't be the case, since we expect to have wait states quite early and often. WaitStates can be several things, service tasks, user tasks, intermediate catch events etc. 

If it happens that we have no wait states or a loop, then we are still limited by the batch size, see above. Later we can investigate also to limit processing via time.

##### Can it be turned off?

Yes, we should build it in a way that we can enable/disable it via a configuration. In the POC https://github.com/camunda/zeebe/pull/11368 we have seen that the implementation is rather simple which should make it easy to separate it.

##### What is the last processed position?

:warning: The last process position needs to be set to the command position which initiates the batch processing. This is likely a user command. Later, when batch limit handling is implemented it might be also an follow-up command.

During batch processing we have no knowledge about the next positions, so we can't calculate the values by hand. Any calculation can and will be invalidated by the Dispatcher/Sequencer which is responsible for the position. The position calculation needs to consider any concurrent user commands which are coming in. 

If we set this to a different position than the starting command position, this might lead to issues as we have seen in the [POC](https://camunda.slack.com/archives/C04K3GJEZU2/p1674129243060049?thread_ts=1674117198.881639&cid=C04K3GJEZU2). 

##### What about error handling?

When an exception occurs during the processing, the current transaction will be rolled back and all records which have been collected during the batch processing will be thrown away. A rejection will be written and also send to the client, if a user commands was processed. The last part is likely the case with batch processing. In general it is quite similar to before, except we will see less blacklisting and more rejections of executions. This might help us later to send better feedback to the user.

Blacklisting handling will only start to happen when we have batch size limitation handling implemented, since then we will process also non-user commands. In such cases we need to blacklist the current executed process instance, in other cases we can send just a rejection to the user, so the user might be able to try it again with different input/variables etc. 

##### Are commands processed in the same order?

It depends what we mean with this. In general yes we just increased the "step-size", we will start to process a command and all follow-up commands are directly applied and processed by the engine as well. After reaching an point were no more commands are produced, we commit the transaction and write the resulting batch of records, which then point to the start command. 

It is likely that commands which target the same process instance have a different effect with this solution, whereas before we might interrupt a process instance during reaching or leaving an activity, we can only do that when reaching the next wait state. Right now we don't consider this as an issue, since this also reduce also the potential failure cases.

_In our POC we had a small issue with using an queue, and not considering the right order for multiple follow up commands, we should keep this in mind._

##### What about side-effects?

We need to collect the side-effects and execute them at the end of the batch processing.

:warning: The current implementation has some issues with reusing queues and clearing them in between.

_Important is here to reconsider the current side-effects implementation since it showed some potential for refactoring. Right now it is hard to reason about when and how side-effects are added and what is at the end actually executed. This made this POC and another POC #11424 harder then necessary._

Potential improvements might be also to directly process certain actions, like correlating messages if we know we are on the same partition.

##### Engine and positions

The engine shouldn't care about positions nor source record positions, we should remove the old remains. This is a concept from the stream platform and persisting + replaying the state.

#### Further Opportunities

* we could provide better insights in the process execution, from user/client perspective
  * When we create a process instance which runs until the job creation, we could send directly the corresponding job details
  * When we encounter during processing any issue / any error we could either return incidents details or an rejection with details to overcome this like reducing payload etc.
 * less Intermediate cancellation: the universe of possibilities to interrupt or terminate a process instance has highly reduced since we process now until a wait-state. We have several tests right now which test what happens when Task X is complete and boundary Y triggers, these cases are no longer possible or event less likely to happen. Would be interesting whether there are still necessary to test and verify.
 * Message correlation:
   * In order to further reduce the process execution latency we could think of correlating messages on the same partition directly in the same batch, when reaching an catch event. [See related POC](https://github.com/camunda/zeebe/pull/11408).

**Comment by npepinpe** [comment]
I think generally if you find a solution to write down a kind of continuation of the processing (in the [computer science sense of the word](https://en.wikipedia.org/wiki/Continuation)), that probably works for any kind of limits we want to put, size or otherwise. Writing a follow up record which represents that (e.g. "continue processing X from this point on") is a great idea, though I'm not sure how that could be generalized :thinking: Very curious to see the outcome :smile:

**Comment by Zelldon** [comment]
Just to add this also here, we completed this EPIC for 8.2 and also backported this to 8.1, see https://github.com/camunda/zeebe/issues/11539.

We have run Benchmarks which show a clear improvement in Latency and in consequence also Throughput.

For 8.1
![Batch processing throughput 8 1 (1)](https://user-images.githubusercontent.com/2758593/222235277-ac5f9058-4a01-4ddf-b96d-439ad0f01347.png)
![Batch processing latency 8 1 (1)](https://user-images.githubusercontent.com/2758593/222235282-664cc74b-56fb-469e-9d69-da7839b5377d.png)

For 8.2

![Benchmark Batch processing - General (1)](https://user-images.githubusercontent.com/2758593/222235556-69b69c72-9971-4dd0-a963-89076a5ffeb1.png)
![Benchmark Batch processing Latency (1)](https://user-images.githubusercontent.com/2758593/222235559-0ae1931d-c54e-4beb-b916-9b91dd62e949.png)
