### ISSUE TITLE
Activate and push jobs to external job activator

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#11711]
**Description**

When the external job activator returns an available worker, the job should be activated in the state and on the log, using the given worker and deadline. 

Before it's handed over to the consumer, its variables should be collected according to the activation properties as well.

We should add some metrics here to measure the impact of doing this while processing.

It's important that these changes are reflected on the log so that followers can also mark the job as activated to reduce the number of duplicate activation of the same job on leader change or the likes.

As far as the engine is concerned however, there is no flow control or commit barrier or the likes. Just hand off the job to the consumer.

```[tasklist]
### Tasks - WIP
- [ ] https://github.com/camunda/zeebe/issues/12082
- [ ] https://github.com/camunda/zeebe/issues/12083
- [ ] https://github.com/camunda/zeebe/issues/12084
- [ ] https://github.com/camunda/zeebe/issues/12086
- [ ] https://github.com/camunda/zeebe/issues/12087
- [ ] https://github.com/camunda/zeebe/issues/12088
- [ ] https://github.com/camunda/zeebe/issues/12089
- [ ] https://github.com/camunda/zeebe/issues/12541
- [ ] https://github.com/camunda/zeebe/issues/12085
- [ ] https://github.com/camunda/zeebe/issues/12695
- [ ] https://github.com/camunda/zeebe/issues/12796
```

### Additional context
* ZPA [kickoff document](https://docs.google.com/document/d/1TGzhU0AQcn0AwO8K1wz8uTqpE5-YS7dFbpnqwrrLn-o/edit#) (internal)
