### ISSUE TITLE
[EPIC] User Task due and follow-up date support

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#11742]
## Introduction

Currently, due and follow-up dates are a missing piece for user tasks in Camunda 8.

## Concept

As a process developer:
* I should be able to define due dates and follow-up dates for user tasks when using the Zeebe BPMN Model API.
* A BPMN model **containing User task due/follow-up dates**, created by the Camunda Modeler, or generated by the BPMN Model API should be deployable to the Zeebe engine.
  * The engine is able to parse and transform User tasks that define a due date or/and follow-up date.

## Task Breakdown

```[tasklist]
### BPMN Model API
- [ ] https://github.com/camunda/zeebe/issues/11795
```

```[tasklist]
### Workflow engine
- [ ] https://github.com/camunda/zeebe/issues/11796
- [ ] https://github.com/camunda/zeebe/issues/11797
- [ ] https://github.com/camunda/zeebe/issues/11809
```

```[tasklist]
### Documentation
- [ ] https://github.com/camunda/camunda-platform-docs/issues/1733
```

### Optional goal
- https://github.com/camunda/zeebe/issues/11809

### Out of scope

An API for modification of due dates and follow-up dates after the User task is ACTIVATED is out-of-scope.

## Other Teams

- [ ] [Operate](https://github.com/camunda/operate/issues)
- [x] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [x] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/215
- ZPA technical breakdown (internal): [Google Doc](https://docs.google.com/document/d/1osf8CzZmoAfIM9uiFu7BugJFDWDb1LEdZDRZh9oWgTM/edit?usp=sharing)
- Camunda 7:
  - Due date: [user task docs](https://docs.camunda.org/manual/7.18/reference/bpmn20/tasks/user-task/#due-date), [Camunda extension docs](https://docs.camunda.org/manual/7.18/reference/bpmn20/custom-extensions/extension-attributes/#duedate)
  - Follow-up date: [user task docs](https://docs.camunda.org/manual/7.18/reference/bpmn20/tasks/user-task/#follow-up-date)

**Comment by skayliu** [comment]
Hey, @koevskinikola 👋 , what about the `priority` properties for user task? As a user i want to order the task list by  `priority`.

**Comment by koevskinikola** [comment]
Hey @skayliu, thanks for raising this question. The user task `priority` property is a nice feature to have. However, it's currently not on our roadmap, and we don't see it as a high priority.

Just in case, I've raised a question on this topic with the product managers, and I'll keep you updated on the answer.

**Comment by skayliu** [comment]
@koevskinikola, There's a case, normaly the user's tasklist is order by create time desc, if with `priority` of `high` value, it will be at the top of the others, so the approver will pay more attention to these tasks first.

Before: 
![image](https://user-images.githubusercontent.com/26370117/222429291-2c2d89e5-1b58-4c8f-8c1f-54e2eae715b1.png)

After:
![image](https://user-images.githubusercontent.com/26370117/222429322-a73f0ffc-661c-476e-9e05-92f76f697e84.png)

**Comment by koevskinikola** [comment]
@skayliu would it be possible to infer the priority level of a task by using the `dueDate` property? Is there any reason why this wouldn't work?

For example, you could sort by due date asc, so the tasks at the top of the list would have the highest priority due to their due date being the closest to the actual date.

**Comment by skayliu** [comment]
> @skayliu would it be possible to infer the priority level of a task by using the `dueDate` property? Is there any reason why this wouldn't work?
> 
> For example, you could sort by due date asc, so the tasks at the top of the list would have the highest priority due to their due date being the closest to the actual date.

@koevskinikola I don't think `dueDate` will fit for it, we could set defualt value `Normal` for `priority` but can't set a default value for 'dueDate', Just like we flag a email, we can later filter all flaged emails.

**Comment by aleksander-dytko** [comment]
@koevskinikola can we close this epic to mark it as finished?

**Comment by aleksander-dytko** [comment]
@koevskinikola I saw that Project board workflow works the other way around - when you close the issue, it's moved to `Done` column:
![image](https://user-images.githubusercontent.com/102789122/226594179-ba1cd2ca-5d2f-4750-9553-0031fcf1acab.png)
I haven't found an option to change the workflow to match this use case - probably we would need a GH Actions to do that.
