### ISSUE TITLE
Implement GCS Backup Store

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#11917]
Tracking issue to implement a Google Cloud Storage Backup Store.

```[tasklist]
## Preparation
- [x] Gather requirements
- [x] Learn about GCS best practices
- [x] Breakdown into tasks
- [x] Reflect on learnings from implementing the S3 Backup Store
```

```[tasklist]
## Implementation
- [ ] https://github.com/camunda/zeebe/issues/11924
- [ ] https://github.com/camunda/zeebe/issues/11925
- [ ] https://github.com/camunda/zeebe/issues/11977
- [ ] https://github.com/camunda/zeebe/issues/11980
- [ ] https://github.com/camunda/zeebe/issues/12070
- [ ] https://github.com/camunda/zeebe/issues/12069
- [ ] https://github.com/camunda/zeebe/issues/12091
- [ ] https://github.com/camunda/zeebe/issues/12105
- [ ] https://github.com/camunda/zeebe/issues/12110
- [ ] https://github.com/camunda/zeebe/issues/12113
- [ ] GCS backup store can compress backups
```

```[tasklist]
## Testing
- [ ] GCS backup store is used in backup acceptance tests
- [ ] GCS backup store is used in restore acceptance tests
- [ ] GCS backup store can be tested on zeebe-io infrastructure
- [x] GCS backup store is tested manually
```

```[tasklist]
## Documentation
- [x] GCS backup store configuration is documented
- [x] GCS backup store authentication is documented
- [x] GCS backup store limitations are documented
- [x] Document migration path from S3 to GCS backup store
```

closes #11732
