### ISSUE TITLE
[EPIC] Broadcast signal event using throw signal event

### ISSUE THREAD

**Issue by skayliu** [camunda/zeebe#11918]
## Introduction

 This is stage 3 of the umbrella epic:
 
 * [[EPIC] Support signal events #10777](https://github.com/camunda/zeebe/issues/10777)

 ### Stage 3: Broadcast signal event using throw signal event

In the third stage, we'll increase support to all BPMN signal symbols. Specifically, it adds support for the Signal Intermediate Throw Event, and the Signal End Event.

<img width="788" alt="Model highlighting that all the signal events will be supported at this stage, including the signal throw events" src="https://user-images.githubusercontent.com/3511026/201059407-a2c8742a-3709-4c56-b2c8-9ae8ab5aa3f7.png">

When a process instance arrives at a signal throw event, we'll broadcast a signal the same way as the gateway can: write a `Signal:Broadcast` command to the current partition. The implementation of stage 1 and 2 will then distribute the command to other partitions, and all signal (start event) subscriptions will be triggered, without additional implementation efforts needed.

### Tasks

- [x] #11919
	- When Signal Intermediate Throw Event activates:
		- Apply input mappings
		- Transition to activated
		- Write `Signal:Broadcast` command
		- Apply output mappings
		- Transition to complete the element
- [x] #11920
	- Introduce a new `SignalEndEventBehavior`
	- When Signal End Event activates:
		- Apply input mappings
		- Transition to activated
		- Write `Signal:Broadcast` command
		- Apply output mappings
		- Transition to complete the element

 

### Discussions

<details>
<summary>Signal name as an expression is a stretch goal</summary>
<p>

By default, the signal name is a static value. This adds value to most users. Expression support for the signal name can be added later. As in other places, this would simply require the value to be prefixed with the expression marker `=`. See stage 4.

</p>
</details>

<details>
<summary>Broadcasting signals with variables payload is a stretch goal</summary>
<p>

The `Signal` record value will already be made ready to receive variables, but we'll leave them out of the gRPC message. This way, it will not yet be possible to pass variables along with the signal, but we'll be able to extend this in the future. Variables are useful but do not have to be part of the first iteration of this feature. See stage 4.

</p>
</details>

## Follow-up

Once the above tasks are completed, we need to
- [ ] Document signal end events
- [ ]  create an issue for Modeler to support signal end events
- [ ]  create an issue for Operate to support signal end events
- [ ]  create an issue for Optimize to support signal end events
- [ ]  inform the product-hub about the completion

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/657

**Comment by skayliu** [comment]
> Introduce a new SignalEndEventBehavior

Hey, @korthout Sounds like this behavior both need for `Signal Intermediate Throw Event` and `Signal End Event`, what about name  `BpmnSignalBehavior` ?

**Comment by korthout** [comment]
- https://github.com/camunda/operate/issues/4340
- https://github.com/camunda/web-modeler/issues/4287
- https://github.com/camunda/camunda-modeler/issues/3546
- https://github.com/camunda/camunda-optimize/issues/6289
- https://github.com/camunda/camunda-platform-docs/issues/1895

**Comment by skayliu** [comment]
Hey @korthout, Please update the signal intermediate throw event links for the others.

**Comment by korthout** [comment]
Thanks for the reminder @skayliu 👍 I've added the missing follow-up issues and updated the links. Additionally, I added to the Modeler issues that the Signal Name supports expressions.
