### ISSUE TITLE
[EPIC] OpenSearch exporter

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#12002]
## Introduction

OpenSearch is a fork of ElasticSearch, made by Amazon. Organisation running self-manages in AWS are likely to be using OpenSearch instead of ElasticSearch. In order to support these organisation we should provide an OpenSearchExporter.

As OpenSearch is a fork of ElasticSearch a lot of it remains the same. Lucky for us, all the APIs we use with the ElasticSearchExporter work out of the box on OpenSearch. This means we don't have to make much changes here. However, AWS requires API request to be signed. In order to support OpenSearch running in AWS we must sign the requests made by our exporter.

## Concept

**In the kickoff we decided to go with Option 2**:

2. We copy the ElasticSearchExporter and rename/migrate it to OpenSearch
    - **Pros**
        - An exact copy is fast to make and add in release 8.2
        - Separation of responsibility
        - No confusion
        - Easy to finetune implementation details to OpenSearch
        - Can be changed to option 3 after release 8.2
    - **Cons**
        - A lot of code duplication with the ElasticSearchExporter
        - More maintenance effort

It was also discussed that we wouldn't move to option 3 after the release and that this will be the final state. This means there will be code duplication between the two exporters. We accepted that this will be the case. [OpenSearch and ElasticSearch are two completely different things](https://www.elastic.co/amazon-opensearch-service). Whilst the APIs are similar at this time, they might not be in the future. Having the duplication is a tradeoff for having the flexibility to easily adapt to changes in either ElasticSearch or OpenSearch when they start to diverge more from each other.

<details><summary>All discussed options</summary>
The way I see it we have 3 options to get this done:

1. We extend the ElasticSearchExporter to allow configuration of AWS and export to OpenSearch
    - **Pros**
        - Fastest solution
        - One single point of maintenance
    - **Cons**
        - Confusing for users. They use OpenSearch, yet need an ElasticSearchExporter
        - Not future-proof. We don't know if OpenSearch's APIs will start to move away from ElasticSearch. If this happens we would still need a separate exporter.
        - ElasticSearch users will be importing dependencies of AWS and OpenSearch. They don't need these at all.
2. We copy the ElasticSearchExporter and rename/migrate it to OpenSearch
    - **Pros**
        - An exact copy is fast to make and add in release 8.2
        - Separation of responsibility
        - No confusion
        - Easy to finetune implementation details to OpenSearch
        - Can be changed to option 3 after release 8.2
    - **Cons**
        - A lot of code duplication with the ElasticSearchExporter
        - More maintenance effort
3. We make a new OpenSearchExporter and extract duplicate code from the ElasticSearchExporter to reuse here
    - **Pros**
        -  The cleanest solution
        - No duplication
        - No confusion
        - Easily to finetune the exporter to the respective implementations
    - **Cons**
        - The most amount of work
        - OpenSearch and ElasticSearch might diverge more in the future. This means a generic solution would no longer be possible and invited hacky solutions, or we need to revert it again.
</details>

### Proof of Concept

Code can be found here: https://github.com/camunda/zeebe/tree/opensearch_poc/exporters/elasticsearch-exporter

<details><summary>Details</summary>
For this POC I had access to a k8s running on AWS and 2 OpenSearch instances. One which required signing of request and one which didn't.

First I connected the ElasticSearchExporter as-is to the OpenSearch instance that did not require signing of requests. Exporting here worked out of the box, as was also verified by the Operate team.

After this I modified the ElasticSearchExporter to connect to the OpenSearch instance that did require signing. This required a few steps.

**1. Switching the ElasticSearch client to the OpenSearch Client**
OpenSearch provides multiple clients. I tried going with the recommended client, however this client did not allow passing a JSON request body directly. Since we have our templates defined as JSON this required a complicated mapping from this JSON to the domain object this OpenSearch client provides. In the end I opted to step away from this client and went with a different one. This different client works the exact same as the ElasticSearch client we are using currently. As a result this only involved modifying the imports. Everything else works the same. **Note:** _Some compilation issues arose in the unit tests. I have ignored those for the POC._

**2. Configuring AWS**
We need a way to provide some configuration to sign the requests. What I needed during the POC was just a service name and a region. We also require credentials. AWS provides a library for this that will try and find the credentials. In my case the required token got injected into the pod by EKS. All I needed to access these was to add the `sts` (security token service) library. Configuration is nothing new in the ElasticSearchExporter so adding the service name and region is straightforward. I did hardcode them in the POC.

**3. Sign the requests**
For details on how to sign a request see: https://docs.aws.amazon.com/general/latest/gr/signing-elements.html

For signing the requests I could use the code that Operate also uses. It adds an [interceptor](https://github.com/camunda/zeebe/blob/opensearch_poc/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/aws/AwsSignHttpRequestInterceptor.java) to the HTTP client. This interceptor will take care of signing the requests before sending them.

**4. Manual test**
Once I did all the above steps I build a docker image with the modified exporter and deployed it to the k8s cluster. Upon startup the requests to create the component and index templates were made and using the OpenSearch API I could fetch the index templates and see that the Zeebe ones were now available:
<img width="1736" alt="image" src="https://user-images.githubusercontent.com/5787702/224667543-e97d6a65-97b9-460d-995e-f4fae2ad8d35.png">

⚠️  In the ElasticSearchExporter we export our records in bulk. As of this POC performing these bulk request **did not** succeed. I have not yet figured out why this is. ⚠️ 

</details>

## Task Breakdown

```[tasklist]
### Exporters
- [ ] https://github.com/camunda/zeebe/issues/12011
- [ ] https://github.com/camunda/zeebe/issues/12012
- [ ] https://github.com/camunda/zeebe/issues/12013
```

```[tasklist]
### Documentation
- [x] Document OpenSearch exporter (https://github.com/camunda/camunda-platform-docs/pull/1837)
- [ ] https://github.com/camunda/zeebe/issues/12014
- [ ] https://github.com/camunda/zeebe/issues/12015
- [ ] https://github.com/camunda/zeebe/issues/12016
```

```[tasklist]
### Testing
- [x] Manual test
```

### Out of scope

- Optimize and Tasklist

## Other Teams

- [x] [Operate](https://github.com/camunda/operate/issues)
- [x] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [x] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/236
- Operate (internal): https://github.com/camunda/operate/issues/4176
- Infra (internal): https://github.com/camunda/infra-core/tree/opensearch-cluster/camunda-opensearch

**Comment by Evil-Crab** [comment]
Will it support role-based IAM which requires signing requests with the role credentials? 
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/ac.html#ac-types-identity 
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/request-signing.html

**Comment by Evil-Crab** [comment]
Great! I decided to ask because https://github.com/camunda/zeebe/issues/12012 only mentions service name and region, while I also expected to provide path to the file with the secrets.

**Comment by remcowesterhoud** [comment]
We'll use [DefaultCredentialsProvider](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.html) from the AWS SDK. This will search for the credentials in a few places. 

I'm no AWS expert myself, but I know EKS has a web hook that allows you to directly inject security tokens and environment variables into the pod. The `DefaultCredentialsProvider` will find this and wouldn't require any additional configurations.

**Comment by remcowesterhoud** [comment]
Closing this as all the sub-tasks have been completed

**Comment by Evil-Crab** [comment]
@remcowesterhoud Does 8.2 Operate support Opensearch?

**Comment by remcowesterhoud** [comment]
> @remcowesterhoud Does 8.2 Operate support Opensearch?

They will, I don't know the full details by I think there will be a special operate opensearch image for this. @ralfpuchert Do you have any documentation surrounding Operate Opensearch support that's publicly available?

**Comment by johanwelgemoed** [comment]
I confirmed with Felix and it would make sense to make the OpenSearch support on Zeebe and Operate publicly available for other customers and not just for JPMC (if we feel confident enough). There is no official documentation yet so we will need to add that. For Zeebe/Operate 8.2 we will only support Opensearch 1.3.x though. For now we support this via compatibility mode but the plan is to implement it proper as part of our 8.3 release (at which time we would also add support for Opensearch 2.x most likely). Does this help?
