### ISSUE TITLE
[EPIC] Terminate Process Instance in batches

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#12485]
## Introduction

Described in #11355 

In short:
Terminating a process instance with a lot of element instances will cause us to exceed the maximum batch size. This in turn results in a blacklisted process instance. In extreme cases it could also result in an OOM exception, killing the cluster.

### Problem origin

The problem lies in the termination of child instances for a container element (process, subprocess, etc.). When we do this we write a `ProcessInstance.TERMINATE` command for every child the container element contains:

```java
stateBehavior.getChildInstances(context).stream()
    .filter(child -> ProcessInstanceLifecycle.canTerminate(child.getIntent()))
    .forEach(
        childInstanceContext ->
            commandWriter.appendFollowUpCommand(
                childInstanceContext.getElementInstanceKey(),
                ProcessInstanceIntent.TERMINATE_ELEMENT,
                childInstanceContext.getRecordValue()));
```

In extreme cases if there is a lot of children this could result in an OOM. More common is the case where there is not enough children for the OOM to occur, but there is too many to be able to fit all the commands in a single batch. When this happens we run into the `ExceededBatchRecordSizeException`.

### Solution

We must introduce a batching-system that makes it so we can write the terminate command for the child instances in batches. We will achieve this by introducing a new command. I will refer to this as the `ProcessInstanceBatchCommand ` for now. Naming is still to be determined. With this we will also need a new `ProcessInstanceBatchIntent`.

The `ProcessInstanceBatchCommand` will contain the following data:
- The container element key
- ~~A list of keys of element instances that need to be terminated~~
- The key of the first child of the next batch (optional) -> index

There will only be a single `ProcessInstanceBatchIntent`:
- `TERMINATE` - This will process the `ProcessInstanceBatchCommand `. Processing this command means writing the `TERMINATE` command for the keys that are available in the command. It will also write a new `ProcessInstanceBatchCommand ` if the amount of keys in the command is equal to the batch size. For this we will need to implement a new method on the column families (`whileEqualPrefix` with a `startAt` parameter).

Implementation concept in this comment: https://github.com/camunda/zeebe/issues/12485#issuecomment-1522896633

<img width="2296" alt="image" src="https://user-images.githubusercontent.com/5787702/235466526-8e1853ce-42a3-42da-8435-c78c32e1aa33.png">

<details><summary>Old concept</summary>

<img width="885" alt="image" src="https://user-images.githubusercontent.com/5787702/233943077-aa8d1308-5bef-42a8-a2b4-7d011bd954f2.png">

Every time we enter processor for the `ProcessInstanceBatchCommand ` we will start searching for children at a different `startAt` position. For the first batch this should be the container element key. For subsequent batches it should be the container element key with the last child element instance key in the command appended to it.
With this `startAt` position we can find the next X amount of child instances. **This will include the last child element instance of the previous batch!** When creating the next batch this first instance should not get terminated again.

</details>

## Task Breakdown

```[tasklist]
### Broker
- [ ] https://github.com/camunda/zeebe/issues/12537
- [ ] https://github.com/camunda/zeebe/issues/12539
- [ ] https://github.com/camunda/zeebe/issues/12538
```

```[tasklist]
### Zeebe Process Test
- [ ] https://github.com/camunda/zeebe-process-test/issues/745
```

```[tasklist]
### Documentation
- [ ] https://github.com/camunda/camunda-platform-docs/issues/2015
```

### Out of scope

- We won't fix the `StackOverflowError` that can occur with deep nested instances as part of this epic.

## Other Teams

- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- Product Hub (internal):

**Comment by remcowesterhoud** [comment]
After considering we have decided to make a change to the concept. We will no longer use a `BATCH_SIZE` configuration option. We will also remove the list of `childElementInstanceKeys` from the `ProcessInstanceBatchRecord`.

Instead we will write a `ProcessInstsanceBarch.TERMINATE` command with just the container element instance key, and an index. During processing we will iterate over the children of the container element. For each we will verify if we have enough space to write this in the same batch. If we do we will write it, if we don't we will use this child element instance key as the index for the next batch.

This makes the termination tied to the already configurable `MAX_MESSAGE_SIZE`. It also prevents us from writing too many extra commands. It is a similar concept as what is used in the `JobBatchCollector`.

One downside is that terminating a process with a lot of active element instances could result in a drop in performance, as it will write a lot of `TERMINATE` commands at once. Other commands written to the log will be written after these. If this becomes a problem we can still introduce an option to stick to a maximum amount of terminates in a batch.
