### ISSUE TITLE
[EPIC] Zeebe multi-tenancy support

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#12653]
**Is your feature request related to a problem? Please describe.**
Enable Zeebe to support the concept of multiple tenants. Tenant data is clearly separated per tenant while reusing a single Zeebe cluster.

**Task breakdown**

The goal of the first phase is to provide core multi-tenancy concepts/mechanisms in the Zeebe Broker and Gateway. These concepts will later be used as building blocks to support multi-tenancy in Zeebe.

```[tasklist]
### Phase 1 - provide core building blocks
- [ ] https://github.com/camunda/zeebe/issues/13235
- [ ] https://github.com/camunda/zeebe/issues/13237
- [ ] https://github.com/camunda/zeebe/issues/13238
```

The goal of phase 2 is to provide multi-tenancy support for core Zeebe concepts like process instances and jobs. The intention is to provide multi-tenancy support for these concepts early in the implementation so that other Camunda Platform 8 components are unblocked, and can start implementing multi-tenancy on their side as well.

Each task of phase 2 covers the vertical implementation (engine, gateway, client, data migration, documentation) for a Zeebe concept. The vertical implementation of the deployments functionality can serve as an example.

```[tasklist]
### Phase 2 - unblock other C8 components
- [ ] https://github.com/camunda/zeebe/issues/13517
- [ ] https://github.com/camunda/zeebe/issues/13520
- [ ] https://github.com/camunda/zeebe/issues/14273
- [ ] https://github.com/camunda/zeebe/issues/13279
- [ ] https://github.com/camunda/zeebe/issues/13287
- [ ] https://github.com/camunda/zeebe/issues/14494
```

Phase 3 expands the work of Phase 2 to the remaining Zeebe concepts. The goal is to provide full support for multi-tenancy in Zeebe.

```[tasklist]
### Phase 3 - vertically implement multi-tenancy across Zeebe components
- [ ] https://github.com/camunda/zeebe/issues/13289
- [ ] https://github.com/camunda/zeebe/issues/13337
- [ ] https://github.com/camunda/zeebe/issues/13282
- [ ] https://github.com/camunda/zeebe/issues/13288
- [ ] https://github.com/camunda/zeebe/issues/14555
- [ ] https://github.com/camunda/camunda-platform-docs/issues/2561
```

```[tasklist]
### Required for 8.3 release
- [ ] #14470
- [ ] #14471
- [ ] #14427
- [ ] https://github.com/camunda/zeebe/issues/14479
- [ ] https://github.com/camunda/zeebe/issues/14499
```

```[tasklist]
### Required for 8.4 release
- [ ] https://github.com/camunda/zeebe/issues/13336
- [ ] https://github.com/camunda/zeebe/issues/14279
- [ ] https://github.com/camunda/zeebe/issues/14285
```

```[tasklist]
### Enhancements/Tech Dept
- [ ] https://github.com/camunda/camunda-docs/issues/2781
- [ ] https://github.com/camunda/zeebe/issues/14374
- [ ] https://github.com/camunda/zeebe/issues/14497
- [ ] https://github.com/camunda/zeebe/issues/14477
- [ ] https://github.com/camunda/zeebe/issues/15100
```

**Additional context**
* [Product Hub issue](https://github.com/camunda/product-hub/issues/197)
* [Camunda Platform 7 docs](https://docs.camunda.org/manual/develop/user-guide/process-engine/multi-tenancy/)
* [ZPA kick-off doc (internal)](https://docs.google.com/document/d/1qWx82v7yqlJaL4NRXNca2Uxk4NZnmgh0sd5LQFeobHc/edit)

**Comment by remcowesterhoud** [comment]
@koevskinikola Fyi I put supporting resource deletion in Phase 3. I didn't fully write it out yet, but I think it's important to list it so we don't forget.

**Comment by korthout** [comment]
@koevskinikola For keeping track of incurred tech debt:
- #14256

**Comment by koevskinikola** [comment]
Issues related to tech debt incurred by the multi-tenancy implementation have been moved to https://github.com/camunda/zeebe/issues/15710.

**Comment by koevskinikola** [comment]
Closing this issue as the multi-tenancy epic is completed in Zeebe.
