### ISSUE TITLE
[EPIC] Zeebe Gateway / clients support job pushing

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#12888]
## Introduction

:information_source: This is just a wrapper issue to encapsulate the work being done by ZPA on the `gateway` and `clients` in the scope of the general [Job activation latency reduction](https://github.com/camunda/product-hub/issues/540) topic.

Please check #11231 for more details on the complete Epic.

## Task Breakdown

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/zeebe/issues/11708
- [ ] https://github.com/camunda/zeebe/issues/11709
- [ ] https://github.com/camunda/zeebe/issues/12389
- [ ] https://github.com/camunda/zeebe/issues/12390
- [x] Documentation
- [ ] https://github.com/camunda/zeebe/issues/13429
- [ ] https://github.com/camunda/zeebe/issues/13430
- [ ] https://github.com/camunda/zeebe/issues/13473
- [ ] https://github.com/camunda/zeebe/issues/4700
```

## Other Teams

- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- [Product Hub](https://github.com/camunda/product-hub/issues/540) (internal)
- [Google doc](https://docs.google.com/document/d/1OZhhw4ulz0SPrTrTGqJbrSOHC8qPAKmsk4EukVUm-is/edit#) (internal)

**Comment by npepinpe** [comment]
I would break this down into two steps for now. I expect the job worker integration may further be split, but we can already add the low level streaming command to the `ZeebeClient` interface.

- [ ] Add the low level client command to stream jobs.
- [ ] Integrate job streaming into the job worker

**Comment by berkaycanbc** [comment]
@npepinpe anything left to do in ZPA side related to this epic? Otherwise, I will close it.

**Comment by npepinpe** [comment]
Nope, all done :+1:
