### ISSUE TITLE
Support multi-tenancy in the Gateway

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#13237]
### Description

For multi-tenancy, the goal of the Zeebe Gateway is to:
1. Provide data on the user's authorized tenants.
2. Forward this data (through the `RecordMetadata`) to the Zeebe Broker through a `Broker*Request` instance.

Full support for multi-tenancy in the Zeebe gateway will be provided once https://github.com/camunda-cloud/identity/issues/1819 is completed.

For this issue, the Zeebe Gateway should (only) support the following:

* Provide a Gateway configuration flag: `zeebe.gateway.multiTenancy.enabled` - default **FALSE** (disabled)
  * The flag should toggle multi-tenancy for the Zeebe cluster.
  * An `enabled` flag is preferred, as we will probably add additional multi-tenancy configuration properties in the future.
* Expand the [`IdentityInterceptor`](https://github.com/camunda/zeebe/blob/1434d4682eba842ef022ec500cd80ebe7cc29a2a/gateway/src/main/java/io/camunda/zeebe/gateway/interceptors/impl/IdentityInterceptor.java#L65) class. After the token is successfully verified the following should be performed:
   1. Provide a list of tenant ids the user has access to:
      * If multi-tenancy is disabled, the list should only contain the `<default>` tenant id (see #13235)
      * If multi-tenancy is enabled, the Identity SDK should be used to fetch the list of tenant ids (out-of-scope for this issue)
   2. [Proposal] Place the list of tenant IDs in a [gRPC context](https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html) to be forwarded to the `EndpointManager`/`RequestMapper` (consider doing it through a helper class).
* We should provide a general (auth) API that the IdentityInterceptor class will implement. The goal is to provide an Identity-independent use of multi-tenancy, i.e. users can use a multi-tenant Zeebe without the need of Camunda Identity.

**AC:**

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/zeebe/issues/14041
- [x] The Gateway can set/get values from a gRPC context
- [x] `IdentityInterceptor` class is expanded according to the description above.
- [ ] https://github.com/camunda/zeebe/issues/14284
- [ ] https://github.com/camunda/zeebe/issues/14307
```
---

```[tasklist]
### Out of scope
- [ ] https://github.com/camunda/zeebe/issues/14285
```

**Comment by korthout** [comment]
>if tenancy is disabled, it will still ask Identity to provide a list of tenants?

I don't think so, because that's the behavior when multi-tenancy is enabled.

>If multi-tenancy is enabled, the Identity SDK should be used to fetch the list of tenant ids

Apart from the description, I would also find it very odd if Identity is still asked.

---

> What happens if tenancy is disabled and Identity is not configured (i.e., Zeebe is used "standalone")? Does the Gateway still provide the default tenant to include it in the respective broker requests?

I would assume that the default tenant would be added to the tenant access ids list, so it can be used in the broker requests where the default tenant is assumed when multi-tenancy is disabled. This means data isolation can be guaranteed.

**Comment by abbasadel** [comment]
I moved https://github.com/camunda/zeebe/issues/14285 out of scope and will link it to a different issue.

**Comment by korthout** [comment]
@abbasadel I've marked #14286 as closing this issue. I think that's fine for Zeebe, as #14307 is Helm Charts related and not blocking Zeebe.

**Comment by abbasadel** [comment]
Make sense. Thanks @korthout
