### ISSUE TITLE
Provide an engine mechanism for verifying tenant access

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#13235]
### Description
We need to establish core engine concepts and mechanisms that will support the development of multi-tenancy in Zeebe.

#### Record interfaces
The following interfaces should be provided in the `protocol-impl` module. The goal is to implement these interfaces across `Records` that will be owned, or will work with the multi-tenancy concept:
* A `RecordValueWithTenant` interface - **implemented with #13520 (named `TenantOwned`)**
   * ~This interface should be implemented by any `Record`s that will be owned by a tenant (ex. deployments, process instances, jobs, messages, timers, etc.).~
   * ~This interface should provide a `getter` method that returns the `tenantId` (String).~
   * **Still missing**: This interface should provide a static value for the following:
      * `<default>` - a reserved `tenantId` value for a "default" tenant. This `tenantId` value will be used when multi-tenancy is disabled, or a user migrates from an older Zeebe version.
* A `RecordValueWithTenantPermissions` interface 
   * :information_source: There is an ongoing discussion to move the data from this interface into the `RecordMetadata`
   * This interface should be implemented by `Command` records created from client requests. The goal of the interface is to provide the tenant access to the user making the client request.
   * This interface should provide a `getter` method` that returns a list of `tenantIds` (List<String>).

#### Validators

A `TenantAccessChecker` class should be implemented in the `engine` module. It should be used by `*Processor` classes, or any other classes that process `Command` records created by Client requests. The purpose of the class is to determine if the User making the request has access to the requested Tenant data.

The class should provide the following methods:
* `hasAccess(String tenantId, RecordValueWithTenantPermissions)` - to determine if a user has access to data from a given tenant. The output can be `Either<Exception, String>` providing the tenantId.
   * If the `tenantId` is listed in the `RecordValueWithTenantPermissions`, the `tenantId` is returned. Otherwise, an error is raised.
* `hasFullAccess(List<String> tenantIds, RecordValueWithTenantPermissions)` - to determine if a user has access to all of the `tenantIds` provided in a list. This will be used later for job polling.

:information_source: We might expand or refactor this class according to different needs as development on the multi-tenancy topic progresses.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/zeebe/issues/13987
- [ ] https://github.com/camunda/zeebe/issues/13988
- [ ] https://github.com/camunda/zeebe/issues/13989
- [ ] https://github.com/camunda/zeebe/issues/14204
```
