### ISSUE TITLE
[EPIC] Continue process instances that are awaiting signals

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#13241]
## Introduction

 This is stage 2 of the umbrella epic:
 
 * [[EPIC] Support signal events #10777](https://github.com/camunda/zeebe/issues/10777)

### Stage 2: Continue process instances that are awaiting signals

In this stage, it will be possible for users to gain more value from broadcasted signals. 

Process instances will subscribe to signals for the Signal Boundary Event (Interrupting), the Signal Boundary Event (Non-Interrupting), the Signal Intermediate Event, the Signal Intermediate Event attached to Event-based Gateway, the Event-subprocess Signal Start Event (Interrupting), and the Event-subprocess Signal Start Event (Non-Interrupting). Signal broadcasts trigger these events, continuing the execution of the waiting process instances.

<img width="792" alt="Model highlighting that all the signal catch events will be supported at this stage, the signal throw events are marked as not yet supported" src="https://user-images.githubusercontent.com/3511026/201048142-dea0dbd8-eb36-473b-98b2-23fead068d71.png">

Broadcasted signals needs to be distributed over all partitions because process instances awaiting the signal can exist on each of the partitions. Distribution mechanics (i.e. await acknowledgement, or retry) are required to guarantee that the signal is broadcasted to ALL partitions (i.e. process instances) because inter-partition communication may fail. Distribution mechanics have been introduced with #11456, which can be reused for distributing signals over all partitions.

Process instances subscribe to a signal using the same `SignalSubscription` record as top-level signal start events.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/zeebe/issues/13242
- [ ] https://github.com/camunda/zeebe/issues/13243
- [ ] https://github.com/camunda/zeebe/issues/13245
- [ ] https://github.com/camunda/zeebe/issues/13244
- [ ] https://github.com/camunda/camunda-platform-docs/issues/2458
- [ ] https://github.com/camunda/zeebe/issues/13943
```

Blocked by:
- #11456

**Comment by korthout** [comment]
@skayliu with #11456 resolved, I've finally taken the time to break down this part of the signal events epic into tasks.

🙇 Would you still be interested in contributing to this?

**Comment by skayliu** [comment]
Hi, @korthout. Of course, you can assign @lzgabel and me to this EPIC.

**Comment by korthout** [comment]
That's great to hear ❤️ 

Let me know if you have any questions about it and feel free to request reviews from me. 🙇

**Comment by lzgabel** [comment]
Hi @korthout @nicpuppa. Please close this epic as we have completed all tasks！:100:

**Comment by korthout** [comment]
Thanks @lzgabel for all your hard work on this 🚀 We can almost close this epic.

We still need to document the feature as you've pointed out. I've opened camunda/camunda-platform-docs#2458 for this. 

I've also opened #13943 which I think could be great to have immediately in the first release of 8.3, but this is not a blocker for releasing the Signal Catch Events feature. So, once we've documented the feature we can close this epic and track #13943 separately.

**Comment by korthout** [comment]
While we still need to document this feature in camunda/camunda-platform-docs#2458, I no longer see a need to keep this EPIC open. Zeebe supports it with the upcoming `8.3.0-alpha5`, and that's enough reason to close this as completed. 🚀  

Thanks again @lzgabel and @skayliu, for your incredible contributions to this! 🥇 💐 🏆
