### ISSUE TITLE
Support multi-tenancy for BPMN message events

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#13289]
### Description

This issue covers multi-tenancy support for message publishing and message correlation in Zeebe. 

```[tasklist]
### Task breakdown
- [ ] https://github.com/camunda/zeebe/issues/14342
- [ ] https://github.com/camunda/zeebe/issues/14357
- [x] ElasticSearch/OpenSearch message templates include tenantId
- [ ] https://github.com/camunda/zeebe/issues/14276
- [ ] https://github.com/camunda/zeebe/issues/13559
- [x] Notify the Connectors and Operate teams that multi-tenancy is supported for message publishing in Zeebe
- [x] Add E2E multi-tenancy tests for message events
```

⚠️ [DbMigrationStateTest#testMigrateProcessMessageSubscriptionSentTime](https://github.com/camunda/zeebe/blob/main/engine/src/test/java/io/camunda/zeebe/engine/state/migration/to_1_1/DbMigrationStateTest.java#L119) has been disabled. This can be re-enabled after the migration for the subscriptions are implemented.

### Blocked by
- https://github.com/camunda/zeebe/issues/13238

**Comment by koevskinikola** [comment]
Update: All (impacted) Elasticsearch/Opensearch record templates have been updated to include a `tenantId` property with https://github.com/camunda/zeebe/issues/13520.

**Comment by korthout** [comment]
@remcowesterhoud I've removed the migration tasks from this issue, and moved it for tracking to #12653

**Comment by koevskinikola** [comment]
The `PublishMessage RPC documentation is expanded with multi-tenancy` task has been moved to https://github.com/camunda/camunda-platform-docs/issues/2561.

**Comment by koevskinikola** [comment]
Closing this issue, as all the sub-tasks are completed.
