### ISSUE TITLE
Support multi-tenancy for DMN decisions

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#13282]
### Description

This issue covers multi-tenancy support for standalone DMN Decision evaluation in Zeebe. 

#### Expected behavior
* A `DecisionEvaluationRecord` **event** is always owned by a single tenant. A decision evaluation can’t be shared across tenants.
* Any `EvaluatedDecisionRecord` **events** are owned by the same tenant as the `DecisionEvaluationRecord`. 
* All Decisions/DRGs used in a single evaluation must belong to the same tenant.
* Filtering decisions by version remains the same as the non-multi-tenant approach, i.e. if no version is specified, the latest version of the process definition owned by the tenant is used. (provided by #13238)
* A decision can be evaluated only by providing a tenant id with the client request. The following scenarios are possible:
   * A tenant id is provided:
      1. A decision is evaluated if the user making the request has access to the tenant owning the decision.
      4. The request/command is rejected if the user doesn't have correct access to the tenant.
   * A tenant id isn't provided:
      1. A decision is evaluated if a user has access to only a single tenant, and a decision can be found that belongs to that tenant..
      2. The request/command is rejected if the user has access to multiple tenants, or a decision can't be found.

ℹ️ In the implementation, first focus on implementing the simple path, with a `tenantId` explicitly provided in the client request/command record. (The same as in #13279)

```[tasklist]
### Task breakdown
- [ ] https://github.com/camunda/zeebe/issues/13777
- [x] Engine can evaluate DMN Business Rule tasks by tenant id
- [x] ElasticSearch/OpenSearch decision evaluation templates include tenantId
- [ ] https://github.com/camunda/zeebe/issues/14278
- [ ] https://github.com/camunda/zeebe/issues/13557
- [ ] https://github.com/camunda/zeebe/issues/14563
- [ ] Notify the Operate team that multi-tenancy is supported for standalone decision evaluation in Zeebe
```

**Comment by koevskinikola** [comment]
Update: All (impacted) Elasticsearch/Opensearch record templates have been updated to include a `tenantId` property with https://github.com/camunda/zeebe/issues/13520.

**Comment by romansmirnov** [comment]
Regarding
> Engine can evaluate DMN Business Rule tasks by tenant id

This has already been implemented with #13238

**Comment by koevskinikola** [comment]
Documentation for this task has been moved to https://github.com/camunda/camunda-platform-docs/issues/2561

**Comment by remcowesterhoud** [comment]
Closing this as it only involves E2E (#14563). We are tracking this on our project board separately.
