### ISSUE TITLE
Support multi-tenancy for process instance operations (modify, cancel, set variables)

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#13288]
### Description

Add multi-tenancy support for the following process instance operations:
* [Process instance modification](https://docs.camunda.io/docs/next/apis-tools/grpc/#modifyprocessinstance-rpc)
* [Cancel process instance](https://docs.camunda.io/docs/next/apis-tools/grpc/#cancelprocessinstance-rpc)
* [Set variables](https://docs.camunda.io/docs/next/apis-tools/grpc/#setvariables-rpc)

To support each operation, the following changes need to be applied:
- The engine validates tenant access in the appropriate processors (`ProcessInstanceModificationProcessor`, `ProcessInstanceCommandProcessor`, `UpdateVariableDocumentProcessor`).
- The Gateway propagates tenant data to the Broker.
- No client changes are needed for these operations. The tenant access is validated by comparing the following information: 
  - The tenant ownership is acquired from the State. 
  - The list of tenants the user is assigned to is acquired from the Identity SDK in the Gateway and forwarded to the engine through the command record (modification, cancel, set variables).

#### Expected behaviors

For each of the process instance operations, the following applies:
* A process instance operation is only possible if the user/token has access to the tenant owning the process instance.

```[tasklist]
### Task breakdown
- [ ] https://github.com/camunda/zeebe/issues/14550
- [ ] https://github.com/camunda/zeebe/issues/14520
- [ ] https://github.com/camunda/zeebe/issues/13388
```

### Blocked by
- #13279
