### ISSUE TITLE
Multi-tenancy data migration is provided for `ProcessingState`s used in Deployments

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#13315]
### Description

Multi-tenancy support requires expanding the various `ProcessingState` classes by adding a `tenantId` key. 
* Existing data (from older Zeebe versions) will need to be migrated to contain this key as well.
* For existing data, the value of the `tenantId` key will be `<default>`, i.e. all existing data will be assigned to the `<default>` tenant.

During a Deployment, the following ProcessingStates are updated:
- `DeploymentState`
- `ProcessState`
- `DecisionState`

### Note

Migrating a large Zeebe state might be problematic if we consider how many changes multi-tenancy will introduce to the Zeebe state classes (almost all of them). We should consider some approaches where we can avoid a data migration that causes long unavailability to the Zeebe cluster.

One option might be to do "lazy migration". We use `NIL_VALUE` as the default tenant identifier while multi-tenancy is disabled. Once multi-tenancy is enabled, the first read from the state of data that has `NIL_VALUE` for the `tenantId` triggers a replacement (either directly in the state or we just provide the `<default>` tenant id instead).

There are also separate Product Hub Epics that aim to optimize the data migration process:
* https://github.com/camunda/product-hub/issues/256
* https://github.com/camunda/product-hub/issues/1368

### AC

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/zeebe/issues/14424
- [ ] https://github.com/camunda/zeebe/issues/14425
- [ ] https://github.com/camunda/zeebe/issues/14426
```

**Comment by koevskinikola** [comment]
:question: Do we need to touch the `DistributionState` as well?

**Comment by remcowesterhoud** [comment]
I will use this comment to keep track of what needs to be migrated.

## DeploymentState
No migration necessary


## ProcessState
TBD

## VersionManager
TBD

## DecisionState
TBD

**Comment by abbasadel** [comment]
As discussed with @megglos and @korthout, this issue has the priority after MT scoped tickets. While it is not a blocker for the code freeze, we need to deliver it part of 8.3

**Comment by korthout** [comment]
@abbasadel I may have missed something, but I believe this became blocking for the code freeze with @romansmirnov's suggestion [to return to data migration](https://camunda.slack.com/archives/C05Q0EXE9V4/p1695223551936369).
