### ISSUE TITLE
`JobBatchRecord` and `JobActivationProperties` provide tenant information

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#13318]
### Description

To support multi-tenancy when polling or pushing jobs, a job should be activated when the `jobType` **AND** `tenantId` match.
We also want to be able to poll or push jobs for multiple tenants at once.

As a result, a list of `tenantIds` needs to be included in the `JobBatchRecord`s and `JobActivationProperties` classes, to ensure that filtering jobs by `jobType` **AND** `tenantId` is possible.

```[tasklist]
### AC
- [x] The `JobBatchRecord` class provides a `tenantIds` property (List\<String\>).
- [x] The `JobActivationProperties` class provides a `tenantIds` property (List\<String\>).
- [x] ~The `JobBatchRecord` class implements the `RecordValueWithTenantPermissions` interface~ (see #13989 and #14283)
- [x] ~The `JobActivationProperties` class implements the `RecordValueWithTenantPermissions` interface~ (see #13989 and #14283)
- [x] ~The Gateway adds a list of tenant ids assigned to a user to the`JobBatchRecord` or `JobActivationProperties` instances for each `ActivateJobs`/`StreamJobs` RPC call.~ (see #14283)
```

**Comment by koevskinikola** [comment]
:information_source: The ZDP team will need to be involved here, to expand the `JobStreamer` API to provide a new method `streamFor(final DirectBuffer jobType, final DirectBuffer tenantId)` that returns a `JobStream` for a given `jobType` and `tenantId`.
