### ISSUE TITLE
Zeebe supports multi-tenancy for BPMN signal events

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#13336]
### Description

This issue covers multi-tenancy support for signal broadcasting in Zeebe. 

```[tasklist]
### Task breakdown
- [ ] https://github.com/camunda/zeebe/issues/14277
- [ ] https://github.com/camunda/zeebe/issues/13558
- [x] The `SignalSubscriptionState` can perist the `tenantId`
- [x] Engine can process `SignalRecord` commands with tenant id
- [x] Multi-tenancy data migration is provided for ProcessingStates used by signal broadcasting
- [ ] https://github.com/camunda/camunda-docs/issues/2820
- [x] ElasticSearch/OpenSearch signal templates include tenantId
- [ ] Notify the Operate team that multi-tenancy is supported for signal broadcast in Zeebe
```

### Blocked by
- https://github.com/camunda/zeebe/issues/13238

**Comment by koevskinikola** [comment]
Update: All (impacted) Elasticsearch/Opensearch record templates have been updated to include a `tenantId` property with https://github.com/camunda/zeebe/issues/13520.
