### ISSUE TITLE
Support multi-tenancy for BPMN timer events

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#13337]
### Description

Support multi-tenancy for timer start events and timer boundary/intermediate events.

:information_source: For timers, the Gateway and Client code doesn't need to be adjusted. Timers are always processed in the engine, and inherit the `tenantId` from the process definition or process instance.

```[tasklist]
### Tasks
- [x] The `TimerRecord` class contains a `tenantId` property
- [x] The `TimerInstance` class contains a `tenantId` property
- [ ] The `TimerInstanceState` has a `tenantId` key and can store and get instances by it
- [x] Elasticsearch/Opensearch `timer-template.json` files have a `tenantId` property
- [x] Timer start events inherit the `tenantId` from the process definition in the `DeploymentCreateProcessor`
- [x] `TriggerTimerProcessor` propagates the `tenantId` from the `TimerRecord` to any follow-up records.
- [x] `DueDateChecker` propagates the `tenantId` from the `TimerInstance` to any follow-up records.
- [ ] Documentation on timer start events is expanded.
- [ ] Add E2E multi-tenancy tests for timer events
```

For the release candidate, we've disabled the timer events feature for non-default tenants.

It's easy to-re-enable:
- remove TIMER [here](https://github.com/camunda/zeebe/blob/58ed10ab83e56c7970025911e8dd694aa054f3d9/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/validation/UnsupportedMultiTenantFeaturesValidator.java#L33-L34)
- replace the tests cases [here](https://github.com/camunda/zeebe/blob/58ed10ab83e56c7970025911e8dd694aa054f3d9/engine/src/test/java/io/camunda/zeebe/engine/processing/multitenancy/TenantAwareTimerEventTest.java#L69-L237)
- un-ignore the test case [here](https://github.com/camunda/zeebe/blob/80d849648b7de82f55ee1de624e3f797df0ce3bc/engine/src/test/java/io/camunda/zeebe/engine/processing/incident/TimerIncidentTest.java#L237)

### Blocked by
- https://github.com/camunda/zeebe/issues/13238

**Comment by koevskinikola** [comment]
Update: All (impacted) Elasticsearch/Opensearch record templates have been updated to include a `tenantId` property with https://github.com/camunda/zeebe/issues/13520.

**Comment by korthout** [comment]
I moved this to in progress, because I wanted to start with it, but ended up working on other thing instead.

**Comment by romansmirnov** [comment]
> The `TimerInstanceState` has a `tenantId` key and can store and get instances by it

As in other cases, I decided against implementing the `TimerInstanceState` to be tenant -aware.
