### ISSUE TITLE
JobRecords are owned by the tenant of the parent process instance

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#13345]
### Description

Extend multi-tenancy support to `JobRecords`.

```[tasklist]
### Tasks
- [x] When a job (`JobRecord`) is created, it is assigned the `tenantId` of the parent process instance.
- [x] The `JobState` can persist the new `tenantId` key.
- [x] The Elasticsearch/OpenSearch `job-template.json` is contains the new `tenantId` property.
```

**Comment by koevskinikola** [comment]
Closing as PR #14407 resolves this issue.

**Comment by koevskinikola** [comment]
Documenting the decisions on the `JobState` adjustments:
1. We realized that we would only need to adjust the `activatableColumnFamily` of the `DbJobState`, as this is the only one exposed to user requests through job polling. The rest of the CFs are internal and don't need tenant validation.
2. To make the `activatableColumnFamily` tenant-aware, we would need to include the `tenantId` in the key of the CF. The `tenantId` should be suffixed since we want to avoid preferential treatment of tenants when polling, i.e. jobs should be picked up by the `jobType` and then filtered by the `tenantId`.
3. We initially planned to avoid performing data migration on the `JobState` by using nested `DbCompositeKey` classes for the `activatableColumnFamily`. We would nest the `typeJobKey` composite key into another composite key containing the `tenantId` called `tenantAwareTypeJobKey` (see [slack discussion](https://camunda.slack.com/archives/C05Q0EXE9V4/p1695223551936369) for more details).
4. When looking up jobs from the `activatableColumnFamily` we would check if the nested composite key `tenantAwareTypeJobKey` is long enough to contain a `tenantId` or not. If not, it would mean this is old data, which is mapped to the `<default>` tenant. See [this commit](https://github.com/camunda/zeebe/pull/14407/commits/b96f044323bdf5b8896939e1a185c76c20588869#diff-ef73a79bfa12b3c9cc862cff7aefcdc63b8cb9efaa732c6de49b842915017b20R330-R346) for more details.
5. Unfortunately, after manually testing the solution against an `activatableColumnFamily` containing "old data", it turned out that the data wasn't mapped correctly to the new `tenantAwareTypeJobKey`, and we couldn't correctly detect "old data".
6. The above ([5]) led us to decide to use the `DbTenantAwareKey` class instead of a nested composite key for the `activatableColumnFamily`. Our decision was based on the following:
   * We couldn't get the initial solution to work correctly, and we had little time to determine the issues and ensure a robust end result.
   * We realized that the `activatableColumnFamily` only contains the activatable jobs, which are not a large data set, so avoiding a migration here wouldn't bring a large benefit.
