### ISSUE TITLE
A FailJob request/command supports tenant validation

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#13346]
### Description

Support tenant validation when a job is failed.

:information_source: No changes on the Client side, as the tenant ownership is clear from the `JobRecord`, and the user's tenant id list is obtained from the gateway.

```[tasklist]
### Task breakdown
- [x] The `JobFailProcessor` completes a job only if the tenant that owns the job is accessible by the user making the request.
- [x] The `JobFailProcessor` rejects a command if the tenant that owns the job is **not** accessible by the user making the request.
- [x] The `IncidentRecord` has a `tenantId` property.
- [x] The `IncidentState` can persist the new `tenantId` key.
- [x] The `JobFailProcessor` creates an `IncidentRecord` with the `tenantId` of the `JobRecord`.
- [x] The Elasticsearch/Opensearch `incident-template.json` has a `tenantId` property.
- [x] ~Gateway provides a user's tenant id list with the broker request when a FailJob RPC call is made~ (Done with #13989 and #14283)
```

### Blocked by
- #13345

**Comment by koevskinikola** [comment]
Closing as https://github.com/camunda/zeebe/pull/14467 fully resolves this issue.
