### ISSUE TITLE
Support multi-tenancy for setting variables on a process instance scope

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#13388]
### Description

Support multi-tenancy when setting variables on a particular scope (e.g. process instance, flow element instance).

:information_source: No changes on the Client side, as the tenant ownership is clear from the `ElementInstance`, and the user's tenant id list is obtained from the gateway.

```[tasklist]
### Task breakdown
- [ ] The `VariableDocumentRecord` and `VariableRecord` contain a new `tenantId` property (see #13235)
- [ ] The `VariableState` contains a `tenantId` key, and can store and fetch variables by `tenantId`
- [x] Elasticsearch/Opensearch `variable-template.json` and `variable-document-template.json` contain  a`tenantId` property.
- [x] The `UpdateVariableDocumentProcessor` updates variables of a given scope only if the tenant that owns the scope is accessible by the user making the request.
- [x] The `UpdateVariableDocumentProcessor` rejects a command if the tenant that owns the "scope" is **not** accessible by the user making the request.
- [x] The `VariableBehavior` class appends the `tenantId` from the provided "scope" to all `VariableRecord` instances.
- [x] ~Gateway provides a user's tenant id list with the broker request when a `SetVariables` RPC call is made~ (authorized tenants are passed in the `RecordMetadata`)
- [x] Follow-up (`VariableDocumentRecord` and `VariableRecord`) events contain a `tenantId` inherited from the scope that was updated.
```

### Additional context
- The `VariableDocumentRecord` class needs to contain a `tenantId` property only when used as a response to the client request, and as an event to be exported.

### Blocked by
- #13279

**Comment by koevskinikola** [comment]
Update: All (impacted) Elasticsearch/Opensearch record templates have been updated to include a `tenantId` property with #13520.
