### ISSUE TITLE
A ResolveIncident request/command supports tenant validation

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#13426]
### Description

Support tenant validation when an incident is resolved.

:information_source: No changes on the Client side, as the tenant ownership is clear from the `IncidentRecord`, and the user's tenant id list is obtained from the gateway.

```[tasklist]
### Task breakdown
- [x] The `ResolveIncidentProcessor` resolves an incident only if the tenant that owns the incident is accessible by the user making the request.
- [x] The `ResolveIncidentProcessor` rejects a command if the tenant that owns the incident is **not** accessible by the user making the request.
- [x] ~Gateway provides a user's tenant id list with the broker request when a ResolveIncident RPC call is made~ (Done with #13989 and #14283)
```

### Blocked by
- #13345
- #13346

**Comment by koevskinikola** [comment]
Closing as https://github.com/camunda/zeebe/pull/14467 resolves this issue.
