### ISSUE TITLE
A ThrowError request/command supports tenant validation

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#13425]
### Description

Support tenant validation when an error is thrown for a job.

:information_source: No changes on the Client side, as the tenant ownership is clear from the `JobRecord`, and the user's tenant id list is obtained from the gateway.

```[tasklist]
### Task breakdown
- [x] The `JobThrowErrorProcessor` throws an error on a job only if the tenant that owns the job is accessible by the user making the request.
- [x] The `JobThrowErrorProcessor` rejects a command if the tenant that owns the job is **not** accessible by the user making the request.
- [x] ~Gateway provides a user's tenant id list with the broker request when a ThrowError RPC call is made~ (Done with #13989 and #14283)
```

### Blocked by
- #13345

**Comment by koevskinikola** [comment]
PR https://github.com/camunda/zeebe/pull/14466 resolved this issue.
