### ISSUE TITLE
[EPIC] Dynamic Scaling of Zeebe Cluster - Phase 1: Number of brokers

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#13642]
## Introduction

**Goal**: I can add or remove brokers to an existing Zeebe clusters while keeping the partitions count same.

When a user provisioned the cluster for a specific workload and later the workload is increased, the cluster can be scaled by adding more brokers and moving some of the partitions to the new brokers. This gives more resources per partition which will then be able to handle the workload. Scaling this way is limited because it depends on how many partitions were initially provisioned. However, this is the first step towards dynamic scaling Zeebe to handle increased workloads.

## Task Breakdown

```[tasklist]
### Store and manage dynamic cluster configuration
- [ ] https://github.com/camunda/zeebe/issues/13739
- [ ] https://github.com/camunda/zeebe/issues/13765
- [ ] https://github.com/camunda/zeebe/issues/13958
```

```[tasklist]
### Move one partition from one broker to other
- [ ] https://github.com/camunda/zeebe/issues/13906
- [ ] https://github.com/camunda/zeebe/issues/14085
```

```[tasklist]
### Allow making configuration changes
- [ ] https://github.com/camunda/zeebe/issues/14298
- [ ] https://github.com/camunda/zeebe/issues/14353
- [ ] https://github.com/camunda/zeebe/issues/14159
- [ ] https://github.com/camunda/zeebe/issues/14462
- [ ] https://github.com/camunda/zeebe/issues/14745
```

```[tasklist]
### Testing
- [ ] https://github.com/camunda/zeebe/issues/14905
- [ ] https://github.com/camunda/zeebe/issues/14953
- [ ] https://github.com/camunda/zeebe/issues/15313
- [ ] https://github.com/camunda/zeebe/issues/15273
- [ ] https://github.com/camunda/zeebe/issues/15546
- [ ] https://github.com/camunda/zeebe/issues/15379
- [ ] https://github.com/camunda/zeebe/issues/15517
```

```[tasklist]
### Extended
- [ ]  ~Expose API to initialize configuration in coordinator~
- [ ]  ~Expose configuration flag to enable/disable auto initialize by coordinator~
- [ ] ~Automatic configuration changes ( When a broker is added, coordinator automatically starts re-distributing partitions)~
```

```[tasklist]
### Misc
- [ ] https://github.com/camunda/zeebe/issues/14959
- [ ] https://github.com/camunda/zeebe/issues/15103
- [ ] https://github.com/camunda/zeebe/issues/15147
- [ ] https://github.com/camunda/zeebe/issues/15220
- [ ] https://github.com/camunda/zeebe/issues/15219
- [ ] https://github.com/camunda/zeebe/issues/15292
- [ ] https://github.com/camunda/zeebe/issues/15381
- [ ] https://github.com/camunda/zeebe/issues/15001
- [ ] https://github.com/camunda/zeebe/issues/15293
- [ ] https://github.com/camunda/zeebe/issues/15726
- [ ] https://github.com/camunda/zeebe/issues/15793
- [ ] https://github.com/camunda/zeebe/issues/15728
- [ ] https://github.com/camunda/zeebe/issues/15743
- [ ] https://github.com/camunda/zeebe/issues/15679
```

### Observability

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/zeebe/issues/15172
```

### Documentation

- https://github.com/camunda/camunda-docs/issues/2855 

### Other teams
- Distribution team. No changes required
- Operator team. No changes required. Supporting this in SaaS will be a different epic.

## Discussions and Decisions

- [Kickoff (internal doc)](https://docs.google.com/document/d/1X0r_Om5Fg2M-TRjYrWQsTg3ekQ1c7eaV4ylWou2rXb8)
- Technical discussion can be found [here(internal doc)](https://docs.google.com/document/d/1QiK6SKspSLTXy_S4yMIzbB4e2IyFGGrbx5Fmusrv8NQ/edit#heading=h.tphvziwi0wim)

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/1087 
- POC https://github.com/camunda/zeebe/issues/12851

**Comment by oleschoenburg** [comment]
Regarding "Automatic configuration changes", maybe this would be a good opportunity to build a better version of the rebalancing API. For example starting leadership transfer to rebalance when the cluster is healthy but unbalanced.

**Comment by deepthidevaki** [comment]
Here are some of the followups that came up in PR reviews or discussions. We should do them with in the scope of this epic. I'm just noting this here so that we don't forget. Will create issues for these later.

- [ ] Retry operations in TopologyChangeApplier or ClusterTopologyManager. Operations like partition join/leave can fail due to temporary issues like timeout, unavailability of leader. This should be retried.
- [ ] Add revapi to check backward compatibility issues with protobuf definitions in topology module
- [ ] Allow configuring cluster topology gossipper. Currently the configs such as sync interval, timeout etc.. are hard coded.
- [ ] Single member cannot leave a partition
- [ ] Engine factory should read partition count from ClusterTopology. Eventhough we don't allow change partition count yet, ClusterTopology is the source of truth. It should be possible to start a broker with wrong configuration, but it find the correct one from the coordinator.
- [ ] Add checksum in persisted cluster topology to detect corruption

Additional improvements
- Should we specify which node is coordinator via Broker configs?
- Should we allow changing coordinator dynamically?

**Comment by oleschoenburg** [comment]
One thing I've just noticed and that we should guard against:
One a single broker, single partition cluster, a `PartitionJoinRequest` for partition 2 (doesn't exist) results in the following:
1. the change is accepted
2. applying the change fails because there's no other member apart from 0 who can assist
3. after a restart, applying the change fails because partition 2 already exists

**Comment by deepthidevaki** [comment]
> One thing I've just noticed and that we should guard against: One a single broker, single partition cluster, a `PartitionJoinRequest` for partition 2 (doesn't exist) results in the following:
> 
> 1. the change is accepted
> 2. applying the change fails because there's no other member apart from 0 who can assist in joining
> 3. after a restart, applying the change fails because partition 2 already exists

Added it to the list of pending tasks in https://github.com/camunda/zeebe/issues/13642#issuecomment-1735063771

**Comment by deepthidevaki** [comment]
Updated the epic to reflect, we wouldn't be addressing the tasks in `Extended` for this scope.

**Comment by oleschoenburg** [comment]
Can we find a way where this feature can be enabled through rolling updates? This is relevant for customers enabling the experimental feature flag by hand and rolling it out as statefulset update, but also when we decide to enable it by default.

Currently, non-coordinator nodes restart first and are then stuck in the `GossipInitializer` until the coordinator can start.

**Comment by deepthidevaki** [comment]
That's a good point. I don't have an idea how to handle that now. Let's discuss.

**Comment by deepthidevaki** [comment]
Following issues will be addressed later as they are not critical for the completion of this epic.
- https://github.com/camunda/zeebe/issues/15793 
- https://github.com/camunda/zeebe/issues/15679 


Closing this Epic as completed. :tada: 

What is not done as part of this Epic:
- No automatic scaling based on heuristics like load
- No automatic scaling when a new node is detected in the cluster. You have to explicitly trigger scaling via the rest api.

Some limitations/potential improvements:
- Broker 0 is the designated code to coordinate any topology changes. When Broker 0 is not available, no other broker can take over the responsibility. This means that any scaling operation can be done when Broker 0 is healthy. Potential improvement - allow overriding this via config. Further improvement, brokers can elect a coordinator themselves based on availability.
- Cancelling a stuck scaling operation is tricky and dangerous.
