### ISSUE TITLE
Store and manage configuration via gossip

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#13765]
Persists configuration locally and propagates via gossip.

- On bootstrap: local configuration state is empty
   - Coordinator :  First query initial set of cluster members for the current configuration. If no member replies with a known configuration, coordinator generates a new configuration from the provided static properties with version=0. Coordinator only has to get a response from any one of the members.
   - Member: Other members request the coordinator for the configuration. Raft partitions and other zeebe services that depend on the cluster configuration are only started after this node receives the configuration from the coordinator.
- On restart
   - Member/Coordinator: All members  use the local persisted configuration.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/zeebe/issues/13793
- [x] Decide serialization format used for persisting and gossiping configuration
- [ ] https://github.com/camunda/zeebe/issues/13801
- [ ] https://github.com/camunda/zeebe/issues/13862
- [ ] https://github.com/camunda/zeebe/issues/13941
- [ ] https://github.com/camunda/zeebe/issues/13956
- [ ] Add integration test for topology manager and gossiper
```

**Comment by deepthidevaki** [comment]
Writing down some of the things that we may have to follow up:

- Handle corruption in persisted cluster topology
- Add missing unit test cases
- Add an integration test that test ClusterTopologyManager and Gossiper together.
- Add any missing configuration for Gossiper
- Should we specify which node is coordinator via Broker configs?
- Should we allow changing coordinator dynamically?

In addition, we can move BrokerInfo out of SWIM to the new Gossiper.

**Comment by oleschoenburg** [comment]
We also need to think about how we want to integrate this with backups. Perhaps the easiest way would be to include the file in the backup. Alternatively, we could make it part of the backup manifest.

**Comment by deepthidevaki** [comment]
Backups are not tied to the topology, right? It doesn't matter which brokers are replicating the partitions or how many replicas are there because we only keep one copy of backup per partitions. What is important is the number of partitions. We already store number of partitions in the backup.

**Comment by oleschoenburg** [comment]
Hm yeah that's true. If we were to backup and restore the topology, this would also mean that it is more difficult to restore into a different topology on purpose. Nevermind then :see_no_evil:
