### ISSUE TITLE
Release: `Repo dispatch Benchmark` fails on 8.0/8.1

### ISSUE THREAD

**Issue by megglos** [camunda/zeebe#13787]
**Description**

I noticed this during the release, on 8.0/8.1 building starter & worker fails as e.g. the maven wrapper is not present on 8.1
```
/home/runner/work/_temp/79d164a7-e6b4-4e02-9e4e-89a3d8a459e8.sh: line 1: ./mvnw: No such file or directory
Error: Process completed with exit code 127.
```
https://github.com/camunda/zeebe/actions/runs/5738456998/job/15552373143

On 8.0 also build zeebe fails as there is no DIST=`build` setup in the Dockerfile https://github.com/camunda/zeebe/actions/runs/5202088373/job/14079846461

```[tasklist]
### Tasks
- [x] backport maven wrapper to 8.0/1 - to avoid workflow merge conflicts from main to stable
- [x] Add a `benchmark.yaml` workflow to each stable branch - to maintain a stable setup
- [x] trigger the workflows via [workflow dispatch](https://docs.github.com/en/free-pro-team@latest/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event) from the https://github.com/zeebe-io/zeebe-engineering-processes referencing the release_branch
- [x] delete the `dispatch-benchmark.yaml` workflow from main
```

**Comment by megglos** [comment]
ZDP-Triage:
- will look into it asap to resolve

**Comment by remcowesterhoud** [comment]
Individual triage:
- Seems to be actively worked on by ZDP at this time. It's not sensible to work on this simultaneously so I'll move it to the ZPA backlog. This also allows us to focus multi-tenancy and migration.
