### ISSUE TITLE
Test infrastructure to launch multiple in-process distribution applications

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#13962]
**Description**

> **Note**
> You can see the initial prototype and [many migrated tests here](https://github.com/camunda/zeebe/pull/13871).

We have several QA tests which rely on launching the complete Zeebe distribution - whether the `StandaloneBroker`, `StandaloneGateway`, `RestoreApp`, or a mixture (cluster) of these. The goal here is to provide test infrastructure to launch any number of these applications, auto-wired by Spring as in production, in-process during our tests.

## Motivation

Right now, we have two ways of doing this:

- Using `zeebe-test-container` and launching multiple isolated containers
- Duplicating the wiring code from the `dist` module into one of JUnit 4 rules (e.g. `ClusteringRule`, `EmbeddedBrokerRule`, etc.)

Each of these has downsides:

1. Containers are expensive and incur a non-negligible startup penalty due to cold starts
2. Testing your changes in a container require you to rebuild the image every time, which is easy to forget and results in a worse local development loop.
3. Any changes in the standalone applications often needs to be duplicated in the `ClusteringRule` or `EmbeddedBrokerRule`. Best case scenario, things don't run/compile; worst case scenario, things fail in subtle ways due to improper wiring of dependencies.
4. Lots of duplication between the `ClusteringRule`, `EmbeddedBrokerRule`, and the `dist` module.
5. There is no `EmbeddedGatewayRule` or anything like this to start the gateway alone
6. The `ClusteringRule` and `EmbeddedBrokerRule` don't start the actuators, and don't test the `dist` module, such that they aren't full acceptance tests
7. Steeper learning curve during onboarding, where new developers need to learn about the `camunda/zeebe:current-test` image, remember to rebuild it on change, how to debug a container based test, etc.

## Proposal

Introduce a new set of QA utilities which allow starting multiple Spring applications in JVM, with some convenience related to Zeebe, and crucially, to clustering.

For each Spring application we have in the `dist` module, we would introduce a new class which both represents its properties and also controls its lifecycle, much like the `GenericContainer` from `Testcontainers`.

It would look something like this:

```java
@Test
void shouldAwaitCompleteTopology() {
  // given
  try (final var broker = new TestStandaloneBroker().start().awaitCompleteTopology(); 
       final var client = broker.newClientBuilder().build()) {
    // when
    final var topology = client.newTopologyRequest().send().join();

    // then
    TopologyAssert.assertThat(topology).isComplete(1, 1, 1);
  }
}
```

Additionally, we will introduce a cluster builder and class to handle wiring and manipulation of Zeebe clusters for tests, much like [zeebe-test-container's ZeebeCluster API](https://github.com/camunda-community-hub/zeebe-test-container#cluster).

```java
@Test
void shouldAwaitCompleteTopology() {
  // given
  final var builder = TestCluster.builder()
            .withBrokersCount(1)
            .withGatewaysCount(1)
            .withEmbeddedGateway(false);
  try (final var cluster = builder.start().awaitCompleteTopology(); 
       final var client = broker.newClientBuilder().build()) {
    // when
    final var topology = client.newTopologyRequest().send().join();

    // then
    TopologyAssert.assertThat(topology).isComplete(1, 1, 1);
  }
}
```

Ideally, we should also introduce a JUnit 5 extension to manage the lifecycle of these nodes/clusters. While we can always manage their start/stop manually, the extension allows us to do the following:

1. Assign temporary folders to each broker that will not get deleted when the broker shuts down, but when the test lifecycle is finished. This means during a test you can start/stop a broker, then introspect the data before restarting it, for example.
2. A concise way of expressing common "await" patterns (e.g. block until all nodes are READY, and the topology of the cluster is complete/healthy).
3. Central point to ensure resources are disposed of (e.g. also avoid having to wrap everything in try-catch blocks).

For example:

```java
@ZeebeIntegration
final class MyTest {
  // wait until all nodes are ready, but don't wait for the topology
  @TestZeebe(autoStart = true, awaitReady = true, awaitCompleteTopology = false)
  private final TestStandaloneCluster cluster =
      TestStandaloneCluster.builder()
          .withBrokersCount(1)
          .withGatewaysCount(1)
          .withEmbeddedGateway(false)
          .build();

  @Test
  void shouldRunOnlyAfterClusterIsReady() {
   // given - when - then
  }
}
```

### Caveats

There are some downsides to this approach versus container based tests, or the existing JUnit 4 rules.

1. There is still a high cost to the initial Spring startup. This is only incurred on the first launch, but any tests in the same JVM afterwards will be pretty fast. Still, they're likely to be a bit slower than starting an `EmbeddedBrokerRule`, for example. But much faster than starting a container!
2. Launching a cluster results in a tons of mixed logs from the different nodes. Containers provided a nice level of isolation there, which will be missed.
3. Since our metrics are all static constants, you cannot rely on them here anymore, especially if you're launching multiple applications in the same fork.
4. JUnit 5 extensions are neat and all, but not a complete guarantee that all resources will be reaped at the end like with Testcontainers (since we lack a sandbox kind of thing now).

## Breakdown

```[tasklist]
- [ ] https://github.com/camunda/zeebe/issues/13963
- [ ] https://github.com/camunda/zeebe/issues/13964
- [ ] https://github.com/camunda/zeebe/issues/13965
```

The next of tasks is focused on providing launchers for each of the Spring applications. Taking inspiration from Testcontainers, these launchers should be usable immediately after construction, but not started. Instead, users can customize them via `withers` (e.g. `withBean`, `withEnv`, etc.), before manually starting them.

Each of these should implement `AutoCloseable`, and also allow start/stop in a blocking fashion.

> **Note**
> Start should return when when Spring considers the application started, i.e. after the `run` method returns in the, say, `StandaloneBroker`. Not when the cluster is ready, for example. This is because we have various cases where we want to wait for readiness, or for topology, or not. Instead, we'll provide helpers to await such states that users can call after.

```[tasklist]
# Test Spring applications
- [ ] https://github.com/camunda/zeebe/issues/13966
- [ ] https://github.com/camunda/zeebe/issues/13967
- [ ] https://github.com/camunda/zeebe/issues/13969
- [ ] https://github.com/camunda/zeebe/issues/13968
```

With all of these, we can start with the cluster API. We can also start already with the JUnit 5 extension even before the cluster stuff is done, by simply first managing the test applications alone.

```[tasklist]
# Test cluster
- [x] Add a test cluster class and builder
- [x] Add JUnit 5 extension to manage test application lifecycle
- [x] Add Junit 5 extension to manage test cluster lifecycle
```

Finally, with all this done, we can start using this in our own tests.

```[tasklist]
- [ ] https://github.com/camunda/zeebe/issues/14377
- [x] Replace usage of the `SpringExtension` test extension in favor of the appropriate test application usage.
- [ ] Replace usage of usage of the `ClusteringRule`, `ClusteringRuleExtension`, and `EmbeddedBrokerRule`
```
