### ISSUE TITLE
Dynamically start and stop partitions

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#14085]
Implement support for adding and removing partitions to a running broker. Eventually, this will be trigger through the topology module when it goes through a configuration change. Until then, it is a manual test-only operation.

This is a major change to the way a broker operates and we expect to find various places that assume that all partitions are known at startup and that list never changes.

Standalone, this feature is very limited because it can only be used to get an existing broker to start or stop an existing partition. This would allow us to temporarily change the replication factor or to temporarily move a partition from one set of brokers to another. Until we start using `DynamicClusterTopologyService` (`zeebe.broker.experimental.features.enableDynamicClusterTopology` is false by default), these changes are lost on restart. This makes the this feature dangerous to use because a broker restart can lead to unexpected unavailability of a partition.

```[tasklist]
### Tasks
- [x] `PartitionManager` can add a partition
- [x] `PartitionManager` can remove a partition
- [x] `PartitionManager` removes partitions from Topology and health checkers
- [ ] https://github.com/camunda/zeebe/issues/15001
```

**Comment by oleschoenburg** [comment]
I'm considering to first remove the entire `RaftPartitionGroup` abstraction since it does not provide value and just obstructs the partition manager from actually adding and removing partitions.

**Comment by npepinpe** [comment]
yes please do. remove all this group stuff :smile:

**Comment by oleschoenburg** [comment]
@deepthidevaki One aspect we haven't discussed yet is what to do with partition data once the leave is completed. Should we just delete it once leave is completed or shall we just keep the data for now?

**Comment by deepthidevaki** [comment]
I think it is safe even if we don't delete it and rejoin. During rejoin it should get new data and overwrite what ever it has. But it is better to delete it for reclaiming space.

**Comment by oleschoenburg** [comment]
I've started with implementing `leave` in the partition manager. The basic are simple enough, we can make the raft configuration change and then shutdown the partition: 119589b368911124182001449d1a4ce854234743 72ab8c2a8a6a7226ab355b6264d79b059567b8ed

There are several issues though where the partition is not reliably removed from the topology, health statuses etc.
I'm considering first going for a larger refactoring of the two `TopologyManager`s (one in the broker, one in the gateway).
This is also related to #14018 because `BrokerInfo` contains number of partitions and their health status which must be cleaned up after leaving a partition.
