### ISSUE TITLE
Support general-usage tenant-providing interceptor for SM

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#14285]
Zeebe 8.3.0 only supports multi-tenancy over Identity:

https://github.com/camunda/zeebe/blob/5b23af53e0c3837abc11325a8a496ac37f793e4e/dist/src/main/config/broker.standalone.yaml.template#L108-L119

Users may want to use their own tenant provider. We want to make this available using [custom interceptors](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/zeebe-gateway/interceptors/).

According to [the decision made below](https://github.com/camunda/zeebe/issues/14285#issuecomment-1851578839), the following tasks need to be completed:

### Tasks
- [x] Expand the `InterceptorUtil` class to provide the `AUTHORIZED_TENANTS_KEY` gRPC context key.
- [x] ~Extract the tenant-providing logic from the `IdentityInterceptor` into a new `IdentityTenantProvidingInterceptor`~
	1. ~This new interceptor is added only if `identity` is set as the `authentication.mode`, and `multiTenancy` is enabled (set to `true`).~
	2. Won't be done since the tenant-providing logic for Identity is closely tied to the Identity token, which is validated within the `IdentityInterceptor`. We would have to extract the token twice if we extract the tenant-providing logic.
- [x] Handling `tenantId` data:
	1. Only use the data provided by the `AUTHORIZED_TENANTS_KEY` gRPC Context key if multi-tenancy is enabled.
- [x] Tests
	1. Ensure that the existing tests that cover multi-tenancy over Identity pass
	2. Add IT tests to ensure that the Gateway uses the data provided by a custom tenant-providing interceptor when multi-tenancy is enabled.
	4. Add IT tests to ensure that the Gateway doesn't use the data provided by a custom tenant-providing interceptor when multi-tenancy is disabled.
	5. Add IT tests to ensure that a custom tenant-providing interceptor overrides the Identity tenant-providing interceptor when multi-tenancy is enabled.
- [x] https://github.com/camunda/camunda-docs/issues/3029:
       - Extend the [Interceptor docs](https://docs.camunda.io/docs/self-managed/zeebe-deployment/zeebe-gateway/interceptors/) with a section on *Implementing a tenant-providing interceptor*
       - Update the MultiTenancy docs for Zeebe to state that:
                - Multi-tenancy in Zeebe is independent from Identity, if Zeebe is used as a standalone product
                - If Zeebe is used as a standalone product, and multi-tenancy is enabled, users can implement a custom tenant-providing interceptor. A link to the Interceptor docs should be provided.
        - If the full Camunda 8 stack is used, then a custom tenant-providing interceptor can't be used, and Identity must be configured since other Camunda 8 components must use Identity.

**Comment by koevskinikola** [comment]
Solution proposals:
1. Zeebe provides an `AbstractTenantProvidingInterceptor` class. 
    1. The class will implement the logic for adding the `tenantId` list to the gRPC context.
    2. Users will need to extend this class and implement the tenant-providing logic.
2. Zeebe provides a `TenantProvider` interface
    1. Zeebe uses a `TenantProvidingInterceptor` class in the Zeebe Gateway module. Implementations of the  `TenantProvider` interface are passed to this interceptor.
    2. Users will need to implement the `TenantProvider` interface
3. Zeebe extends the `InterceptorUtil` class to provide the `AUTHORIZED_TENANTS_KEY`, and documents (in a similar manner to the `QueryApi`) how to use it with the gRPC Context.
   1. Users may implement a "tenant-providing" interceptor as they see fit.
   2. We document this in the Zeebe Interceptors documentation.

**Comment by koevskinikola** [comment]
Decision:
We use solution proposal [3] from [the list above](https://github.com/camunda/zeebe/issues/14285#issuecomment-1847356998). Why:
* PRO: It provides the most flexibility for users. Users can implement their tenant-providing logic in any of their gRPC interceptors.
* PRO: It uses an existing Zeebe Interceptor mechanism (the `InterceptorUtil` class) to pass and extract data to/from interceptors.
* CON: Users may still provide a `tenantId` list using this mechanism when multi-tenancy is disabled, as we have no mechanism to prevent this within an interceptor.
   * However, we can control if the `tenantId` list is used or not inside the Gateway, depending if multi-tenancy is disabled or not.
   * The alternative to avoid this CON is to use approach [1] or [2]. However, we would need to re-implement a mechanism for instantiating externally provided classes (we have this with the `IdentityRepository`. Furthermore, these approaches are less flexible, as we would require users to either extend an abstract class or implement an interface inside their code.
