### ISSUE TITLE
Disable temporarily unsupported features with multi-tenancy enabled the non-default tenant

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#14479]
Support for multi-tenancy is rolled out gradually. Not all Zeebe features are available immediately.

Users should not be able to break the system. We need to disable the following features when multi-tenancy is enabled temporarily. We only have to disable features partially.

>**Note**
> These features will still be supported for the default tenant! Even with multi-tenancy enabled.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/zeebe/issues/14480
- [ ] https://github.com/camunda/zeebe/issues/14482
- [ ] https://github.com/camunda/zeebe/issues/14483
- [ ] https://github.com/camunda/zeebe/issues/14484
- [ ] https://github.com/camunda/zeebe/issues/14485
```
