### ISSUE TITLE
Add multi-tenancy support in the Zeebe Go client

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#14477]
### Description

The Zeebe Go client should support multi-tenancy.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/zeebe/issues/15153
- [ ] https://github.com/camunda/zeebe/issues/15095
- [ ] https://github.com/camunda/zeebe/issues/15096
- [ ] https://github.com/camunda/zeebe/issues/15097
- [ ] https://github.com/camunda/camunda-docs/issues/2893
```

**Comment by Sijoma** [comment]
Picked this up and created: https://github.com/camunda/zeebe/pull/14946

**Comment by koevskinikola** [comment]
I've converted this issue to an umbrella issue that covers all the sub-tasks needed to support multi-tenancy for the Go client. I moved the previous issue description to #15153 and re-assigned [the related PR ](https://github.com/camunda/zeebe/pull/14946)there.

**Comment by koevskinikola** [comment]
ZPA team:
Moving this issue back to the `Backlog` column of the ZPA project board, as this feature was deprioritized until `8.5`.

**Comment by koevskinikola** [comment]
Closing as this topic has been de-prioritized and it is currently not clear if/when it will be picked up again.
