### ISSUE TITLE
Disable support for process instance operations when multi-tenancy is enabled

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#14483]
If multi-tenancy is enabled, we cannot support all process instance operations yet. The features will have to be partially disabled or break tenancy-isolation:
- https://github.com/camunda/zeebe/issues/13288

## Requirements

We cannot ensure that all process instances belong to the default tenant. So we'll need to restrict these features based on the tenant-id of the associated process instance.

Each of the operations is still available for the default tenant.

### Cancel Process Instance

If we don't support multi-tenancy for this feature, we have two options:
- We can either allow all tenants to cancel any process instance by key
- or completely disable the feature for tenant-specific process instances

I'm not sure what's better at this time.

### Modify Process Instance

This feature will not function correctly, while we don't fully support multi-tenancy. It must be disabled.

### Set Variables

If we don't support multi-tenancy for this feature, we have two options:
- We can either allow all tenants to set variables for any process instance by key
- or completely disable the feature for tenant-specific process instances

### Disabling the features

This can be done in the engine (i.e. respective command processor), by looking up the respective process instance and rejecting the command if the owning tenantId is not the default tenant.

### Allow all tenants access

This does not require code changes but should be clarified to users. If we take this approach, multi-tenancy does not fully isolate (i.e. shield) the process instance data from other tenants.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/zeebe/issues/14511
- [ ] https://github.com/camunda/zeebe/issues/14542
- [ ] https://github.com/camunda/zeebe/issues/14543
```

**Comment by korthout** [comment]
Closing this in favor of:
- https://github.com/camunda/zeebe/pull/14553
