### ISSUE TITLE
Implement endpoints for testing cluster topology changes

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#14746]
Building on top of https://github.com/camunda/zeebe/pull/14642, we want to expose an API that will make testing cluster topology changes much easier:

```[tasklist]
### Tasks
- [x] Broker API for joining a partition
- [x] Broker API for leaving a partition
- [x] Gateway Endpoint for joining a partition
- [x] Gateway Endpoint for leaving a partition
```
