### ISSUE TITLE
Partition priority can be changed dynamically

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#14745]
Ref:- https://github.com/camunda/zeebe/issues/14462#issuecomment-1764430663

When reassigning partitions to new brokers, the new distribution might result in new priorities (priority set for raft prioirity election) for existing brokers. If we don't change the priority according to the new distribution, replicas can end up with duplicate priority. This can lead to undesired leader distribution, or in worst case unbounded election latency. 
To handle this gracefully, we will also allow changing priority via topology change operation.

```[tasklist]
### Tasks
- [ ] Allow changing priority in raft context
- [ ] Add topology change operation for priority operation
- [ ] Partition manager can change priority 
```

**Comment by deepthidevaki** [comment]
Before allowing priority to be changed dynamically, I would propose some changes to priority election.

Current priority election is as follows.
- Each node is assigned priority 1 to replication factor
- Node with highest value has highest priority
- Node with higher priority becomes the leader. This is acheived as follows
    - Each node keeps a `currentValue` initialized to `targetPrioirity`. (targetPriority = number of replicas/highest priority value).
    - On each election timeout currentValue is decremented by 1
    - When `currentValue`<= node's priority the node starts election
    - On reset `currentValue` will be reset to `targetPriority`

This has some disadvantages for dynamic configuration changes. When changing number of replicas, priority of all nodes have to be changed. Otherwise, the newly added node will have the highest priority. Changing number of replicas is not in the scope of dynamic scaling yet, but this is something that we can easily support with the infrastructure we build for dynamic scaling.

**Option 1**
We keep it as it is and add operation to change priority. Changing target priority cannot be changed, meaning we will have issues if we want to change number of replicas dynamically. (Workaround is restarting the nodes after adding new replicas to a partition).  Alternatively, we allow changing the targetPriority - this should be changed in all replicas during a topology change which is unnecessary overhead.

**Option 2**   
Change the priority election to redefine the order of priority. Node with lowest value will have the highest priority. Election timer works as follows:
 - `currentValue` will be initialized to node's priority
 - On each election timeout `currentValue` is decremented by 1
 - election is triggered when `currentValue` is <= 0. 
 - on reset `currentValue` will be reset to node's priority
 
This way the priority election is unaffected by the number of replicas.

Cons of Option 2 - This is a breaking change if any one is using `Fixed` partitioning scheme. But fixed partitioning config is still an experimental configuration flag. For other's this change will be transparent as we can reassign the priority values based on the new order so the final leader distribution will be same as before.
