### ISSUE TITLE
[EPIC] Process Instance Migration Phase 1

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#14907]
## Introduction

Keep your running instances up-to-date with the latest process improvements ([public roadmap issue](https://github.com/camunda/issues/issues/279)).

Process Instance Migration is a feature that is [available in Camunda 7](https://docs.camunda.org/manual/develop/user-guide/process-engine/process-instance-migration/) that allows process instances to be 'migrated' to another process model. Typically, this is useful when the process definition needs to be changed due to bugs or new requirements. This epic aims to add basic process instance migration functionality for relatively simple process definitions.

Efforts on this feature start from lessons learned from the following issues, where we identified several potential iterations. However, that concept was overthrown after spiking another approach where we don't cancel the process instance and create a new instance using the target process definition, but rather adjust the existing process instance in such a way that the keys (process instance key, job keys, etc) remain the same:
- https://github.com/camunda/zeebe/issues/11099
- #14960 

This means that Process Instance Migration will allow users to migrate an existing process instance to a new process definition, but this will come with certain restrictions. For example, the type of an activity cannot be changed when mapping it in the migration plan.

By default, a process instance's context is always preserved during migration. This means users won't be surprised by the process instance changing unexpectedly. This means no expressions, input mappings, execution listeners, or event subscriptions are evaluated, executed, or changed by default according to the difference between the two process definitions. In future iterations, users will be provided options to change this behavior through the API.

Users can use [Cancel Process Instance](https://docs.camunda.io/docs/next/apis-tools/grpc/#cancelprocessinstance-rpc) in combination with [Create and Start at a User-Defined Element](https://docs.camunda.io/docs/next/components/concepts/process-instance-creation/#create-and-start-at-a-user-defined-element) to overcome the limitations of Process Instance Migration, at the cost of losing the original process instance and a re-creation of the associated keys.

### Requirements and limitations

Process instances can only be migrated under the following requirements and limitations. The reasoning for each statement can be found by expanding the details.

<details><summary>Process instance migration can only migrate active process instances, i.e. existing process instances that have not yet been completed, terminated, or banned</summary>
<p>

Terminated and completed process instances are removed from Zeebe, so Zeebe has no knowledge about them anymore.

Banned process instances still exist in Zeebe. However, they are isolated from active instances so that they don't cause further damage. Banned instances cannot be recovered, but allow investigation by Zeebe developers to troubleshoot severe bugs.

</p>
</details> 

<details><summary>All active elements require a mapping (including active Sub Processes)</summary>
<p>

We require all active elements in a process instance to have an explicit mapping in the migration plan. This is also a requirement for active Sub Processes.

When a Sub Process is added nesting a mapped active element, the engine assumes that the user wants to have a new element instance of that Sub Process. Likewise, when a Sub Process nesting a mapped active element is removed, the engine could assume that the user wants to remove the element instance of that Sub Process. However, when a Sub Process nesting a mapped active element remains, the user likely wants to reuse the element instance of the Sub Process. For example, if variables exist at this Sub Process, they wouldn't expect to lose them.

Now consider the case where a Sub Process nesting a mapped active element remains, but its element ID is changed. Should the engine consider this a different Sub Process from the active one, or does the user mean that this is the same Sub Process? There is no way for the engine to decide this for the user.

To highlight this, let's add one additional Sub Process to the target process nesting the Sub Process with the adjusted ID. In the example, we map Task `A` to `A`, what should happen to the instance of Sub Process `Sub 1` and any variables existing on it?

![sub-process-magic](https://github.com/camunda/zeebe/assets/3511026/6c455938-25e4-4c45-a47a-e5e15b348195)

1. If we recreate the Sub Process
   - The variables are lost
   - Or the engine has to add logic to copy the variables automatically and choose between `Sub 2` and `Sub 3`
2. If we adjust the Sub Process as Migrated
   - The engine has to choose between `Sub 2` and `Sub 3` as migration target and create an instance of the other

In both scenarios, the engine has to make a choice that it can't really make.

The alternative is to require users to provide a mapping for all active elements, including active Sub Processes. The engine can still assume to create new element instances for Sub Processes added to the hierarchy in the target process. When an active Sub Process is removed from the hierarchy, the user can provide an explicit mapping to:
- a target Sub Process -> to migrate and keep the element instance 
- no element `""` (empty string) -> to terminate the element instance

This has several advantages:
- The expected outcome of the migration plan is clear because the mappings are explicit
- If the ID of a Sub Process is changed in a target process and the user forgets to map the Sub Process, it will otherwise lead to the loss of local variables existing at the Sub Process, or the engine has to make a choice for the user about copying the variables. This mistake could be easily made, so we should protect the user.

</p>
</details> 

<details><summary>Mapping instructions cannot change the element type</summary>
<p>

If we would allow changing the element type, then type-specific expressions and entities may have to be created and/or removed depending on the mapping. This quickly leads to difficult situations. 

For example, when mapping a service task to a user task, we'd have to remove the job, evaluate user-specific expressions (e.g. assignee), and create a new job with the new information, or adjust the existing job with the new info. If the type changes further from task to gateway, this also leads to more required changes. For Zeebe, it's best to keep this complexity under control and restrict how elements can be migrated.

Zeebe provides a way to move elements between elements of different types with the Process Instance Modification functionality. Users can modify and migrate a process instance in a two or three-step procedure:
1. Migrate a process instance, keeping the active element unchanged and introducing a new element with a different type
2. Modify the process instance, moving the active element to the newly introduced element
3. Migrate the process instance, removing the no longer needed element from the process

</p>
</details> 

<details><summary>The target process definition must exist in Zeebe (deployed and not deleted)</summary>
<p>

This requirement should not raise any eyebrows. Zeebe must know what the target process looks like in order to migrate a process instance to it.

</p>
</details> 

<details><summary>A mapping instruction's `sourceElementId` must refer to an element existing in the source process</summary>
<p>

If the mapping refers to a non-existing element id, then the user might have made a mistake in their mapping instructions. Instead of just accepting this, we prefer to point out the mistake. As process instance migration is a power tool, it's possible to damage a process instance. Therefore, we feel it's best to support the user wherever possible.

</p>
</details> 

<details><summary>A mapping instruction's `targetElementId` must refer to an element existing in the target process (or refer to no element, i.e. `""` empty string)</summary>
<p>

Exactly similar to the point above about `sourceElementId`, with one exception: if the mapping refers to a Sub Process, it's possible to remove the element instance by referring to no target element. See the discussion about `All active elements require a mapping (including active Sub Processes)` above.

</p>
</details> 

#### Additional limitations

This epic will be limited as it only provides basic functionality and focuses on simpler process definitions. However, these are not requirements and may be changed later.

<details><summary>The number of active leaf element instances (i.e. tasks, events, gateways) stays the same</summary>
<p>

We may add support in future versions for removing or adding leaf element instances through specific mapping instructions, but we believe that this makes the feature unnecessarily complex. Users can use Process Instance Modification to remove or add element instances to a process instance and can combine it with Process Instance Migration in a multi-step procedure to deal with this. See the discussion on `Mapping instructions cannot change the element type` for an example of such a procedure changing step 2 to remove or add an element instance.

</p>
</details>

## Concept

A new `MigrateProcessInstance` RPC will be added to Zeebe's Gateway to allow clients to migrate process instances. This RPC requires specifying a migration plan. This migration plan consists of mapping instructions specifying how active elements in the source process are migrated to elements in the target process.

A simple migration example is migrating an active Service Task `A` to a process with that same Service Task `A` and a Service Task `B` after it. The mapping instructions specify that `A` is mapped to `A`. After the migration, the process instance is still waiting at Service Task `A`, and when completing its Job the process flows to Service Task `B`.

<img width="1137" alt="Screenshot 2023-11-10 at 10 28 39" src="https://github.com/camunda/zeebe/assets/3511026/4d1d18a2-3c3d-455f-a619-ddafc3cf3ea6">

## Reference-level details

We'll introduce a new `MigrateProcessInstance` RPC. This API allows for defining a migration plan consisting of a target process definition and a set of mapping instructions. Each instruction looks like `[source element id -> target element id]`. The RPC takes a `MigrateProcessInstanceRequest` similar to the following structure (note that the naming and structure are not yet definitive):

```protobuf
message MigrateProcessInstanceRequest {
  // key of process instance to migrate
  int64 processInstanceKey = 1;

  MigrationPlan migrationPlan = 2;

  message MigrationPlan {
    // the process definition key to migrate to
    int64 targetProcessDefinitionKey = 1;
    // source (to migrate from) element id and target element id (to migrate to)
    repeated MappingInstruction mappingInstructions = 2;
  }

  message MappingInstruction {
    // the element id to migrate from
    string sourceElementId = 1;
    // the element id to migrate to
    string targetElementId = 2;
  }
}
```

When migrating an instance, we adjust the active element instances in Zeebe's state using `ProcessInstance:ELEMENT_MIGRATED` events. These make sure that the following information is updated:
- `processDefinitionKey`: the key of the target process definition
- `bpmnProcessId`: the BPMN ID of the target process definition
- `version`: the version of the target process definition
- `elementId`: changes to the mapped element ID (note that the mapping may define the `sourceElementId` and the `targetElementId` as equivalent, in which case it stays the same)
- `flowScopeKey`: may change if the element exists within a different (sub)-process in the target process definition, e.g. when a new sub-process wraps the element or when a wrapping sub-process is removed in the diff between the source and target process definitions)

Similarly, we will adjust other entities:
- jobs with `Job:MIGRATED`
- variables with `Variable:MIGRATED`
- incidents with `Incident:MIGRATED`
- (eventually) event subscriptions like `Timer:MIGRATED` and `SignalSubscription:MIGRATED`, but these are kept out-of-scope initially by recreating event subscriptions

In the following example, both the element instance of the Process and the element instance of the active Service Task `A` are adjusted using `ProcessInstance:ELEMENT_MIGRATED` events. The Job associated with Service Task `A` is also adjusted using a `Job:MIGRATED` event. If any Process Variables exist on the process instance, then these are adjusted using `Variable:MIGRATED` events.

![migrate-changing-id](https://github.com/camunda/zeebe/assets/3511026/21711484-d071-4453-b629-82d1a0b3fa0c)

We also need to adjust the internal entities (these exist in the state only and don't have their own associated records):
- Event Scope Instance, requires changes to interrupting and boundary element ids 
- EventTrigger, requires changes to elementId (but likely does not require adjustment for migrated instances)

Such internal entities can either:
- be adjusted through the `ProcessInstance:ELEMENT_MIGRATED` events
- be promoted to have their own records so they can be adjusted through `*:MIGRATED` events

Note that any entities introduced for new features will also need `MIGRATED` events to be adjusted. For example:
- #14938 
- #14920 
- #11217 

#### Changing the element hierarchy

Migrated activities do not have to remain descendants of their closest migrating ancestor scope (Hierarchy Preservation) like in Camunda 7. Instead, a Sub Process can be added in the target process, nesting an element active in the source process. Zeebe will assume that the user intends to create a new element instance of the Sub Process that can be used as the ancestor scope of the active element.

In the following example, we see that element instance `B` is mapped to an element `B` that is nested inside `A New Sub Process`. A new element instance (with a new key) will be created for the element `A New Sub Process` using `ProcessInstance:ELEMENT_ACTIVATING` and `ProcessInstance:ELEMENT_ACTIVATED`. The flow scope (i.e. ancestor scope) of the element instance `B` is then adjusted to the key of the newly created instance of `A New Sub Process` using `ProcessInstance:ELEMENT_MIGRATED`.

This is recursive behavior, meaning that multiple nesting Sub Processes can be added simultaneously.

![added-a-new-flowscope](https://github.com/camunda/zeebe/assets/3511026/61be220e-e0ad-4000-9b11-f346dbb17378)

Likewise, a Sub Process in the source process may be removed in the target process. Zeebe will assume that the ancestor scope of the removed Sub Process instance can be used as the ancestor scope of any element active in that Sub Process. 

This is recursive behavior, meaning that multiple nesting Sub Processes can be removed simultaneously.

![migrated-a-removed-flowscope](https://github.com/camunda/zeebe/assets/3511026/140fd788-0850-4370-8db0-26dd0218a6f5)

## Task Breakdown <a href="#task-breakdown" id="task-breakdown">#</a>

```[tasklist]
### Process Instance Migration Phase 1
- [ ] https://github.com/camunda/zeebe/issues/14923
- [ ] https://github.com/camunda/zeebe/issues/15161
- [ ] https://github.com/camunda/zeebe/issues/15106
- [ ] https://github.com/camunda/camunda-docs/issues/2910
- [ ] https://github.com/camunda/zeebe/issues/15107
- [ ] https://github.com/camunda/zeebe/issues/15110
- [ ] https://github.com/camunda/zeebe/issues/15111
- [ ] https://github.com/camunda/zeebe/issues/15113
- [ ] https://github.com/camunda/zeebe/issues/15119
- [ ] https://github.com/camunda/camunda-docs/issues/2899
- [ ] https://github.com/camunda/zeebe/issues/14921
- [ ] https://github.com/camunda/zeebe/issues/15131
- [ ] https://github.com/camunda/zeebe/issues/15364
- [ ] https://github.com/camunda/zeebe/issues/15123
- [ ] https://github.com/camunda/zeebe/issues/15124
- [ ] https://github.com/camunda/zeebe/issues/15125
- [ ] https://github.com/camunda/zeebe/issues/15126
- [ ] https://github.com/camunda/zeebe/issues/15363
- [ ] https://github.com/camunda/zeebe/issues/15114
- [ ] https://github.com/camunda/zeebe/issues/15129
- [ ] https://github.com/camunda/camunda-docs/issues/2900
- [ ] https://github.com/camunda/zeebe-process-test/issues/972
- [ ] https://github.com/camunda/zeebe/issues/15405
- [ ] https://github.com/camunda/zeebe/issues/15406
- [ ] https://github.com/camunda/zeebe/issues/15435
- [ ] https://github.com/camunda/zeebe/issues/15440
- [ ] https://github.com/camunda/zeebe/issues/15460
- [ ] https://github.com/camunda/zeebe/issues/15461
- [ ] https://github.com/camunda/zeebe/issues/15568
```

### Next phases

- #17346 
- #17349

### Out of scope

The following topics are explicitly scoped out, within the bounds of the concept, requirements, and limitations described in the sections above.

```[tasklist]
### Out of scope
- [ ] https://github.com/camunda/zeebe/issues/15407
- [ ] https://github.com/camunda/zeebe/issues/14922
- [ ] Migrate boundary event instances
- [ ] Migrate manual task instances
- [ ] Migrate undefined task instances
- [ ] Migrate end event instances
- [ ] Migrate start event instances
- [ ] Migrate element instance nesting inside new sub process
- [ ] Migrate element instance nested inside removed sub process
- [ ] Migrate element instances no longer marked as multi-instance
- [ ] Migrate element instances newly marked as multi-instance
- [ ] Migrate signal event subscriptions
- [ ] Migrate message event subscriptions
```

## Other Teams

- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

### How to copy local variables of sub-processes when the scope hierarchy changes?

In Camunda7, there is a requirement for [hierarchy preservation](https://docs.camunda.org/manual/develop/user-guide/process-engine/process-instance-migration/#hierarchy-preservation). It may be, that we don't have this same requirement in Zeebe. However, this lack presents ambiguity when it comes to copying variables of sub-processes.

A potential solution would be introducing Variable Mapping Instructions to the Migration Plan, where the user can specify exactly where to move variables when removing a Sub Process from the hierarchy.

This functionality can be kept out of scope for now.

### How should we deal with process instances in non-wait states?

When the engine completes an element and flows to the next element, it:
- marks the element as completed
- marks the outgoing sequence flow as taken
- and appends a command to activate the next element for the process instance

This means that there are moments in time when an element is not active in the state. Rather the sequence flow is taken, and a not-yet-processed command describes the continuation of the process execution.

After migrating the instance, such unprocessed commands will still be attempted to be processed, but they will be rejected because they refer to the now terminated source process instance.

This scenario also exists for Process Instance Modification, as the referenced process instance key stays the same for both modification and migration. However, parts of the process instance could be terminated, for which unprocessed commands could also be rejected.

For Process Instance Migration, other information (e.g. process definition key) has changed since the command was appended. What we could do to resolve this, is to never trust this data in `ProcessInstance` commands and always look up the current process definition by doing a lookup of the element instance by key. By trusting the state over the data in commands, we may be able to process more commands correctly.

Still, an element activation command may be unprocessed targeting a no longer existing element id. In that case, the command will simply be rejected. The user may need to use Process Instance Modification to rectify the process instance state.

This scenario might not be too problematic, as it only affects non-wait states. Migration is typically done from wait state to wait state (e.g. user task to user task, service task to service task, etc), where the process has already reached that specific point and is awaiting further instructions from the client. For the cases where this affects non-wait states, modification can be used by the user to rectify any tokens lost during migration. In the future, process instance suspension may be used to stop process execution and increase the user's control over the process migration.

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/1470
- Product Hub (internal): https://github.com/camunda/product-hub/issues/1829

**Comment by aleksander-dytko** [comment]
@korthout I propose to remove `Basic` from the issue descriptions the scope of the epic, if far beyond the basic functionality.
Also, let's remove `version:8.4.0` as the task breakdown does not reflect the 8.4 scope.

**Comment by korthout** [comment]
Closing this issue as completed and released in `8.4.0`. Future work is extracted to other issues.
