### ISSUE TITLE
QA tests for partition leave and join

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#14905]
```[tasklist]
### Tasks
- [x] A partition can be added to an existing broker
- [x] A partition can be removed from a broker
- [x] Leaving a partition removes it from the gateway's view
- [x] Joining an unknown partition is rejected
- [ ] Partition join interrupted due to restart should continue after restart
- [ ] Partition leave interrupted due to restart should continue after restart
- [x] Cluster returns to a healthy state after scaling
```

**Comment by oleschoenburg** [comment]
I'm closing this without adding tests for restart behavior. This is difficult to control in tests and we wont achieve full test coverage anyway. I believe that e2e and chaos tests serve us better here.
