### ISSUE TITLE
Implement Azure Backup

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/zeebe#14927]
## Goal 

Support Azure Cloud Storage for Zeebe Backups.

## Additional Info

https://github.com/camunda/product-hub/issues/1785

## Task breakdown 

Status: Ongoing discovery.

- [ ] Azure Backup Store Configuration.
- [ ] Backup Sore can save backup.
- [ ] Backup Sore can delete the backup. 
- [ ] Backup Sore can query the backups. 
- [ ] Azure Backup store tests.
- [ ] Azure Backup store documentation.
