### ISSUE TITLE
[EPIC] Add support for BPMN compensation events 

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#14920]
## Introduction

We execute tasks in our processes that sometimes have to be canceled later under certain circumstances. BPMN compensation events and compensation handlers are a very powerful construct for handling such situations.

Without these BPMN symbols, users would have to add a lot of additional complexity to their models.

![Screenshot from 2023-10-31 09-27-40](https://github.com/camunda/zeebe/assets/4305769/28da4807-2eba-4a39-8f63-31b99c26d1d9)

## Concept

BPMN compensation events are part of the BPMN 2.0 standard (chapter 13.4.5 Compensation, page 441). 

In this iteration, we **plan to implement** the following features of compensation events:
- Add support for compensation events:
  - Compensation boundary events
  - Compensation intermediate throw events
  - Compensation end events
  - Compensation start events (i.e. compensation event subprocesses)
- Mark activities for compensation (i.e. compensation handlers):
  - Service Tasks
  - User Tasks
  - Send Tasks
  - Script Tasks
  - Manual Tasks 
  - Undefined Tasks
- Trigger compensation recursively for subprocesses
- Access local variables (i.e. snapshot data) from completed subprocesses
- Trigger compensation for a given activity (i.e. instead of implicitly for the current scope)

### Compensation subscriptions 

In order to compensate an activity, we need to keep track of completed activities with a compensation handler. Currently, we remove all data of an element instance from the state when it is completed. So, we need to store the data separately.

The only place to modify the state is within an event applier. An event applier is invoked on writing or replaying an event. 

We could extend the existing event applier for the `process_instance.COMPLETED` event and store the data of the completed activity. But this would introduce additional non-trivial logic to the event applier and would violate our goal to keep the event appliers simple (i.e. only apply/write the state changes of the event). 

A better way is to move the logic in the processors and introduce a new record to manage the subscriptions for compensation. 

 ```
Compensation subscription
========================

Record:
- tenant id
- process instance key
- process definition key
- element id of activity with compensation handler
- flow scope element id of activity with compensation handler
- element id of compensation throw event
- element instance key of compensation throw event
- local variables of activity with compensation handler (i.e. snapshot data)

-----------------------------------------

Lifecyle:
CREATED -> TRIGGERED -> COMPLETED | DELETED

- on CREATED: 
  - when an activity with a compensation boundary event is completed, or
  - when an embedded subprocess with a compensation event subprocess is completed
  - then add the subscription to the state 
- on TRIGGERED: 
  - when the compensation throw event is activated
  - then set the element instance key and element id of the compensation throw event
  - and update the subscription in the state
- on COMPLETED: 
  - when the compensation handler is completed
  - then remove the subscription from the state
- on DELETED: 
  - when the process instance is completed or terminated
  - then remove the subscription from the state 

-----------------------------------------

State:
< process instance key | subscription key > -> subscription record

- the subscription key can be used for the reverse ordering
```  

![Screenshot from 2023-11-03 11-40-44](https://github.com/camunda/zeebe/assets/4305769/9aaa272f-5bf6-4f48-b26a-98b89c560c0a)

### Broker

- [x] camunda/zeebe#14939
- [x] camunda/zeebe#14942
- [x] camunda/zeebe#14943
- [x] camunda/zeebe#14944
- [x] camunda/zeebe#14965
- [x] camunda/zeebe#14967
- [x] camunda/zeebe#15063
- [x] camunda/zeebe#14970
- [x] camunda/zeebe#15066
- [x] camunda/zeebe#15065
- [x] camunda/zeebe#15064
- [x] camunda/zeebe#15068
- [x] camunda/zeebe#15141
- [x] camunda/zeebe#15152
- [x] camunda/zeebe#15332
- [x] #15465
- [x] camunda/zeebe#15333
- [x] #16808
- [x] #16809
- [x] #16970
- [x] #15459 _(stretch goal)_
- [x] #16600 _(stretch goal)_
- [x] #16601 _(stretch goal)_
- [x] #16602 _(stretch goal)_

### Gateway API

No changes in the gRPC API.

### Exporters and Metrics

- [x] camunda/zeebe#15140
- [ ] https://github.com/camunda/zeebe-analytics/issues/23 _(stretch goal)_

### Testing

- [x] #15495
- [x] #15496 _(after 8.5 is released)_
- [x] #15498
- [ ] #16807 _(stretch goal)_

### Zeebe Process Test

- [x] camunda/zeebe-process-test#995

### Documentation

- [x] https://github.com/camunda/camunda-docs/issues/2802

### Out of scope

- Mark activities for compensation (i.e. compensation handlers):
  - Call activites
  - Embedded subprocesses 
- Trigger compensation recursively for child process instances
- Support compensation event subprocesses
- Don’t wait until compensation is completed
- Invoke compensation handlers synchronously in reverse order
- Optionally invoke compensation handlers if the activities are activated but not completed yet
- Support for BPMN cancel events
- Support for BPMN transactional subprocess

## Other Teams

- [x] [Operate](https://github.com/camunda/operate/issues)
- [x] [Tasklist](https://github.com/camunda/tasklist/issues)
- [x] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [x] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [x] [Optimize](https://github.com/camunda/camunda-optimize/issues)

### Invoke compensation handlers in reverse order

According to the BPMN specification, the compensation handlers are invoked in the reserve order of the execution. 

![Screenshot from 2023-10-31 09-54-32](https://github.com/camunda/zeebe/assets/4305769/7031fcc3-d669-4e3b-ac9d-9fb1165b5e4e)

(BPMN 2.0, 13.4.5 Compensation, page 442)

We don't plan to follow this rule. Instead, we will activate the compensation handlers altogether. 

Consider the following example: 

![Screenshot from 2023-11-01 09-34-32](https://github.com/camunda/zeebe/assets/4305769/72a682d1-ef44-4fd7-8191-37937011cff4)

Assuming that the tasks "A" and "B" are completed. When the compensation end event is reached, we will activate the compensation tasks "Undo A" and "Undo B". Jobs workers can process these jobs concurrently and in any order. 

According to the BPMN specification, we should activate the task "Undo B" first. When the task is completed, we should activate the task "Undo A". 

In Camunda 7, the reverse order of the compensation is only guaranteed if the compensation handlers are invoked synchronously (i.e. via JavaDelegate). Asynchronous or external tasks are activated [concurrently](https://docs.camunda.org/manual/7.19/reference/bpmn20/events/cancel-and-compensation-events/#intermediate-throwing-compensation-event).

Since Camunda 8 works mainly with external tasks, the behavior will be the same.

If the order of the compensation handlers is important, the user could trigger the compensation for the activities explicitly. See the following example.   

![Screenshot from 2023-11-01 09-59-16](https://github.com/camunda/zeebe/assets/4305769/5eee858f-6cf7-4e06-a9b2-96db281b44fb)

### Interrupt compensation handlers

Can a compensation hander be interrupted/canceled? 

Consider the following examples:

1. The compensation handler is in the same scope as an interrupting event subprocess. 

![Screenshot from 2023-11-10 06-37-27](https://github.com/camunda/zeebe/assets/4305769/bb5c120f-2c32-4988-a2ef-6a94a94d110d)

2. The compensation handler is inside an embedded subprocess that has an interrupting boundary event.

![Screenshot from 2023-11-10 06-37-07](https://github.com/camunda/zeebe/assets/4305769/4ba7be61-4380-4478-9e92-fdaa57a338d1)

3. The compensation handler is in the same scope as a termination end event.

![Screenshot from 2023-11-10 08-47-54](https://github.com/camunda/zeebe/assets/4305769/e03f5c80-99ff-48c7-9d79-0e2090c1d656)

In Camunda 7, a compensation handler can be interrupted. In some of these cases, the process instance might end in an invalid state where the instance is stuck in the compensation throw event.

The BPMN specification is not clear about this scenario. It mentions only the following:

> [A compensation activity] is outside the normal flow of the Process.

For Camunda 8, we will follow the way of Camunda 7. When the compensation is triggered, the process instance activates the compensation handlers in the same scope as the compensation throw event. As a result, the compensation handler is interrupted when the scope of the compensation throw event is interrupted or terminated. Effectively, the compensation handler is interrupted when the compensation throw event gets interrupted.

Looking at case (2) the behavior will be different to Camunda 7. The compensation handler is inside an embedded subprocess with a boundary event. The compensation throw event will invoke the compensation handler in the scope of the process instance. It doesn't activate the subprocess again and doesn't create a timer subscription for the boundary event. As a result, the boundary event can't interrupt the compensation handler. Only, if the compensation throw event would be inside the same subprocess.

### Invoke compensation handler for an activity with an incident

When triggering compensation, we invoke the compensation handlers of all completed activities. But what about activities with an incident in a `COMPLETING` state? 

In this case, the underlying job of the activity has been completed but the variable output mapping failed to apply. From a BPMN perspective, the activity itself is not completed. However, the action and possible side effects were executed.  

To undo the action, it could make sense to invoke the compensation handler even if the activity is not completed.

In Camunda 7, we don't have this case because there is no `COMPLETING` state. If the output mapping (or execution listener) fails then the transaction is rolled back and the activity is still active.   

For Camunda 8, we will not focus on this case in the current iteration. So, we will ignore the activity for the compensation. However, this case could be interesting as a follow-up topic to give users more control over the compensation.   

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/219
- Public roadmap issue: https://github.com/camunda/issues/issues/56 
- Camunda 7 documentation: https://docs.camunda.org/manual/7.19/reference/bpmn20/events/cancel-and-compensation-events/

**Comment by saig0** [comment]
:next_track_button: I updated the description of the epic and moved the support for **BPMN compensation event subprocesses** out of the scope. We will focus on the event subprocesses in a [follow-up epic](https://github.com/camunda/zeebe/issues/16247).

**Comment by saig0** [comment]
:heavy_check_mark: The epic is done. All tasks have been implemented and shipped with version 8.5. :rocket: 

:fast_forward: The remaining tasks are moved to the epic for the next iteration of compensation ([ref](https://github.com/camunda/zeebe/issues/16247)).
