### ISSUE TITLE
[EPIC] Create and complete User Tasks in Zeebe

### ISSUE THREAD

**Issue by tmetzke** [camunda/zeebe#14938]
## Introduction

Introduce User Tasks in Zeebe as first-class citizens. Keep track of their creation and completion in records and states. Allow completing them via a new Zeebe Task API.

## Concept

See increments [no. 1](https://docs.google.com/document/d/1RUGoofgrSz1pFYKEBDjUggaz8fDeBkkJEv8KSl2fJBM/edit#heading=h.vlnha0d84b0z), [no. 2](https://docs.google.com/document/d/1RUGoofgrSz1pFYKEBDjUggaz8fDeBkkJEv8KSl2fJBM/edit#heading=h.u72rmyzf9e2), and [no. 3](https://docs.google.com/document/d/1RUGoofgrSz1pFYKEBDjUggaz8fDeBkkJEv8KSl2fJBM/edit#heading=h.8kycy2kc67pp) of the technical proposal (internal) for the initial concept.

In short:

* Users can choose the type of implementation for each User Task in the model (i.e. either service task (legacy) or user task (new)).
* For legacy User Tasks, nothing changes. 
* For new User Tasks, when they are processed, Zeebe User Task records are written instead of jobs with task details.
* Zeebe User Tasks can be completed via the Zeebe Task gRPC API.
* The Zeebe User Task state is kept in Zeebe as well.

## Task Breakdown

The first increment brings the foundations of Zeebe User Tasks as first-class objects in Zeebe.
```[tasklist]
### Increment 1
- [ ] 
``` 

## Other Teams

- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- Product Hub (internal):

**Comment by tmetzke** [comment]
## Command & Event structure

### Current Service Task-like User Tasks

* Creates Job records with task data in untyped custom headers
* Completes User Tasks when `Job.Complete` Commands are issued

![Zeebe User Tasks - Commands   Events (1)](https://github.com/camunda/zeebe/assets/586643/ab6a83c9-ac51-4816-8e2a-ea4ada58752e)

### Proposed Zeebe User Tasks

* Creates Zeebe User Task records with task data in typed record attributes
* Completes User Tasks when `UserTask.Complete` Commands are issued (new gRPC API)

![Zeebe User Tasks - Commands   Events](https://github.com/camunda/zeebe/assets/586643/1e218c47-7f4a-4c2b-82fb-834df1b870bc)

**Comment by koevskinikola** [comment]
Technical notes:
* Increment 2 - Exporters & Metrics # `Add support for new Zeebe User Task records` - I think this will already be supported when #14996 is completed. We can of course, delay the ES/OS index template addition, but it's possible that the project build will fail if we don't do it.
* Increment 3 # `Support cancelation of Zeebe User Tasks (e.g. by interrupting the process instance)` - if we follow the same pattern as in the `BusinessRuleTaskProcessor`, this task might already be completed in "Increment 2 - Broker", when creating a User task record. We don't have to do it, but then if we release an alpha, users won't be able to cancel a User task, resulting in free-floating data.
* In Increment 3, we should work on the `Gateway` tasks first. That will unblock us to parallelize the Clients and Broker implementations.

**Comment by tmetzke** [comment]
> Technical notes:
> 
> * Increment 2 - Exporters & Metrics # `Add support for new Zeebe User Task records` - I think this will already be supported when [Create a Zeebe User Task record and event structure #14996](https://github.com/camunda/zeebe/issues/14996) is completed. We can of course, delay the ES/OS index template addition, but it's possible that the project build will fail if we don't do it.
> * Increment 3 # `Support cancelation of Zeebe User Tasks (e.g. by interrupting the process instance)` - if we follow the same pattern as in the `BusinessRuleTaskProcessor`, this task might already be completed in "Increment 2 - Broker", when creating a User task record. We don't have to do it, but then if we release an alpha, users won't be able to cancel a User task, resulting in free-floating data.
> * In Increment 3, we should work on the `Gateway` tasks first. That will unblock us to parallelize the Clients and Broker implementations.

Thanks a lot, @koevskinikola. I agree with all abovementioned points and will adjust the description accordingly 👍

**Comment by tmetzke** [comment]
Based on the (🔒 internal) [C8 API Strategy](https://docs.google.com/document/d/14gJTSS6soaOqf2BShJswguNRHBClrsmmDGD_XDKXrRE/edit#heading=h.zf13esin36i), I removed all gRPC-related tasks from this epic (gateway, ZPT, clients).

**Comment by tmetzke** [comment]
All issues are done, closing as completed 🎉
