### ISSUE TITLE
Save Zeebe User Task state in Zeebe

### ISSUE THREAD

**Issue by tmetzke** [camunda/zeebe#14997]
**Is your feature request related to a problem? Please describe.**

Based on #14996, I can save User Tasks to the log stream.
However, the state of such a User Task is not reflected in RocksDB.
I can thus not access the current state of a User Task and can thus not validate related commands while processing them, e.g. validate if a completion is allowed.

**Describe the solution you'd like**

The state of User Tasks based on the new Zeebe User Task record can be stored to and fetched from RocksDB.

```[tasklist]
### Tasks
- [x] A `UserTaskState` interface is provided
- [x] A `MutableUserTaskState` interface is provided
- [x] A `DbUserTaskState` implementation is provided
- [x] A `UserTaskState` getter is provided in the `ProcessingState` and `ScheduledTaskState` interfaces and their implementations.
- [x] A `UserTaskStateTest` unit test is added.
```

**Describe alternatives you've considered**

n/a

**Additional context**
* Blocked by #14996 (we need a User task record that can be saved)
* Base requirement to enable https://github.com/camunda/zeebe/issues/14938.

**Comment by koevskinikola** [comment]
Sizing is `small`, but may leak into `medium` with reviews.
