### ISSUE TITLE
Create a Zeebe User Task record and event structure

### ISSUE THREAD

**Issue by tmetzke** [camunda/zeebe#14996]
**Is your feature request related to a problem? Please describe.**

I want to have User Tasks as first-class citizens in Zeebe, represented on the log stream.
There is no specific record or event structure in Zeebe to do this.

**Describe the solution you'd like**

```[tasklist]
### Tasks
- [x] There is a basic record and event structure for User Tasks that can be stored on the log stream.
- [x] The record and events represent the values a User Task can have.
- [x] The record is supported by our exporters (ES and OS index templates are provided).
```

**Describe alternatives you've considered**

Keep using Job records to represent User Tasks on the log stream.

**Additional context**

* Base requirement to enable https://github.com/camunda/zeebe/issues/14938.
* Guide for [adding new records in Zeebe](https://github.com/camunda/zeebe/blob/main/docs/developer_handbook.md#how-to-create-a-new-record).

**Comment by koevskinikola** [comment]
I've set the size of this issue to `medium`. In my estimate, the implementation time is `small`, i.e. a single day, but we should account for review times as well, which might happen on another day, which makes the size `medium`.
