### ISSUE TITLE
A `defaultJobWorkerTenantIds` configuration property is available

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#15097]
### Description

The Zeebe Go client may be configured with a `defaultJobWorkerTenantIds` configuration property. 

The property will set the `tenantIds` property for all job activation commands globally on the client, without requiring a developer to explicitly set it for each command.

The default value is `['<default>']`.

```[tasklist]
### Tasks
- [ ] A `defaultJobWorkerTenantIds` configuration property can be set through code.
- [ ] A `defaultJobWorkerTenantIds` configuration property can be set through a `ZEEBE_DEFAULT_JOB_WORKER_TENANT_IDS` environment variable.
- [ ] The `defaultJobWorkerTenantIds` configuration property is applied to job activation commands that require it on instantiation. The `tenantIds` property can be explicitly set later.
```

**Comment by koevskinikola** [comment]
Closing as this topic has been de-prioritized and it is currently not clear if/when it will be picked up again.
