### ISSUE TITLE
A `defaultTenantId` configuration property is available

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#15096]
### Description

The Zeebe Go client may be configured with a `defaultTenantId` configuration property. 

The property will set the `tenantId` property for all commands globally on the client, without requiring a developer to explicitly set it for each command.

The default value is `<default>`.

```[tasklist]
### Tasks
- [ ] A `defaultTenantId` configuration property can be set through code.
- [ ] A `defaultTenantId` configuration property can be set through a `ZEEBE_DEFAULT_TENANT_ID` environment variable.
- [ ] The `defaultTenantId` configuration property is applied to all commands that require it on instantiation. The `tenantId` property can be explicitly set later.
```

**Comment by koevskinikola** [comment]
Closing as this topic has been de-prioritized and it is currently not clear if/when it will be picked up again.
