### ISSUE TITLE
Introduce a new MigrateProcessInstance RPC

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#15119]
Introduce a new `MigrateProcessInstance` RPC to the gateway. This requires multiple steps.

```[tasklist]
### Tasks
- [x] Add the `MigrateProcessInstance` RPC to the gateway protocol
- [x] Implement the request mapping for process instance migration
- [x] Implement the response mapping for process instance migration
- [x] Test the gateway's process instance migration rpc
```

Blocked by:
- #15106
