### ISSUE TITLE
[EPIC] Job worker back pressure/flow control

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#15168]
## Introduction

The current job streaming implementation in Zeebe is very performant, but very sensitive to failures. Any failure that occurs from the moment the job is activated until it's received by the client adds latency to the perceived activation time (and thus, to the overall process).

One major failure mode is the possibility of brokers pushing too many jobs downstream and overloading either the gateways or the clients.

When a client is overloaded, in the worst case scenario, it will crash (e.g. out of memory). This has an even higher impact on overall latency, as any job it had received is activated, meaning it's locked out for other workers, and will remain so until it times out, which can add a lot of time to the latency.

Furthermore, depending on where the client is running (e.g. embedded in an application), this can have a wider impact on the user application's availability.

## Concept

The idea is to implement explicit back pressure directly in the worker. Workers will track how many jobs have been stream and polled in a single unified queue, and block both polling and streaming when they're out of capacity.

The only configuration option for now will a fixed maximum capacity, i.e. how many _**unhandled**, activated_ jobs they can buffer at a time, i.e. the `maxActiveJobs` parameter.

Whenever a worker has reached its maximum capacity, we will block the gRPC transport (see [ClientCallStreamObserver#isReady](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/CallStreamObserver.html#isReady())) and suspend polling. To properly support this, the gateway will have to respect the client's `isReady` flag on the server side.

> **Note**
> Doing so will also provide minimal back pressure support for unofficial clients or those using the bare gRPC API.

One downside with _only_ blocking is that the server is still partially buffering future messages. This can result in a job the server believes it has sent, but actually did not, which leads to a worker receiving a job that has timed out. It also means blocking on the client side, which could block a complete thread. Finally, it still causes brokers to keep activating jobs needlessly, only to find out after pushing all the way downstream that there was no capacity.

## Task Breakdown

We'll break this down into two iterations.

### First iteration

For the first iteration, the goal is for the worker to block the gRPC stream such that it doesn't receive/buffer further jobs until it has capacity again. The gateway will minimally support this by not pushing to clients which are not ready (i.e. `isReady() == false`). Here, the gateway will either try with another client, or will send the job back to the broker (which can then retry with other gateways if any, or yield the job back to the engine).

This requires a unified way to track streamed and polled jobs to avoid consuming too many resources. Alternatively, we might start with two queues to simplify things.

> **Note**
> @Zelldon - I think starting with two queues initially will let us progress faster, and it should be fine to leave unifying polling/streaming to later. Let me know what you think.

```[tasklist]
# First iteration
- [ ] https://github.com/camunda/zeebe/issues/15181
- [ ] https://github.com/camunda/zeebe/issues/15179
```

We can validate behavior with benchmarks, using the existing job worker metrics to ensure we don't queue too many jobs at a time. _After this, job push should be safe to use in production, if sub-optimal_.

**First iteration is targeted for completion during CW46-47.**

### Second iteration

The second iteration will focus on our expanding our test suite, primarily around chaos and E2E tests, which will likely include some work to improve the observability of the feature.

```[tasklist]
- [ ] https://github.com/camunda/zeebe/issues/15455
- [ ] https://github.com/zeebe-io/zeebe-chaos/issues/442
- [ ] https://github.com/zeebe-io/zeebe-chaos/issues/444
- [ ] https://github.com/zeebe-io/zeebe-chaos/issues/443
- [ ] https://github.com/camunda/zeebe-e2e-test/issues/357
- [ ] https://github.com/camunda/zeebe-e2e-test/issues/358
- [ ] https://github.com/camunda/zeebe-e2e-test/issues/359
- [ ] https://github.com/camunda/zeebe/issues/15454
- [ ] https://github.com/zeebe-io/zeebe-chaos/issues/446
```

**This means the complete feature should be ready for the 8.4 release**.

### Zeebe Process Test

There shouldn't be any changes required for Zeebe Process Test.

### Documentation

```[tasklist]
# Documentation
- [ ] https://github.com/camunda/camunda-docs/issues/3025
```

### Out of scope

Essentially, out of scope are all kinds of optimizations.

- Optimal capacity splitting based on producer push rate
- Optimal work load distribution based on worker capacity
- Heuristics to reduce traffic of control messages to report capacity

## Discussions and Decisions

- [Slack channel](https://camunda.slack.com/archives/C04G2F074UQ)

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/1869

**Comment by npepinpe** [comment]
I assume many of the issues above will be further broken up into smaller issues, but it felt premature to do that now.

**Comment by Zelldon** [comment]
Looks like our moving to done, doesn't close issues @npepinpe

**Comment by Zelldon** [comment]
Remove myself here

**Comment by npepinpe** [comment]
I think we can mark it as done, as it's also unlikely I will end up implementing the e2e tests any time soon. I'll mark those as follow ups.
