### ISSUE TITLE
[EPIC] Provide additional user task lifecycle actions and events

### ISSUE THREAD

**Issue by tmetzke** [camunda/zeebe#15526]
## Introduction

Provide the additional user task lifecycle actions in the broker that emit new events on the event stream.
This enables more use cases for user tasks, allowing users to assign and update them.

## Concept

The general technical concept is described in the [(🔒 internal) User Task lifecycle & listeners in Zeebe](https://docs.google.com/document/d/1RUGoofgrSz1pFYKEBDjUggaz8fDeBkkJEv8KSl2fJBM/edit#heading=h.jfwkcbaivk7y) as increment [5](https://docs.google.com/document/d/1RUGoofgrSz1pFYKEBDjUggaz8fDeBkkJEv8KSl2fJBM/edit#heading=h.nkx4pi1zpa1d).

In short:
* We prepare the following actions as commands in the broker:
  * Assign - Set the assignee without a check of a potentially existing assignee. To be used when a user or machine assigns another user to a task
  * Claim - Set the assignee. If the assignee is already set, reject. To be used to claim a task for myself from a working queue (e.g. with multiple candidates).
  * Update - Updates supported attributes of a task.
* The commands issue new events:
  * ASSIGNING & ASSIGNED
  * UPDATING & UPDATED
* The commands allow setting a custom `action` attribute in the user task to enable custom lifecycle implementations on top of our general actions.
* Custom form keys are tracked by and exported as "externalReference" in native user tasks as well.
* The creation date of user tasks is tracked in the records and also stored in the state.

## Task Breakdown

```[tasklist]
### Preparation
- [ ] https://github.com/camunda/zeebe/issues/15528
```

```[tasklist]
### Broker
- [ ] https://github.com/camunda/zeebe/issues/15529
- [ ] https://github.com/camunda/zeebe/issues/15530
- [ ] https://github.com/camunda/zeebe/issues/15531
- [ ] https://github.com/camunda/zeebe/issues/15839
- [ ] https://github.com/camunda/zeebe/issues/16006
- [ ] https://github.com/camunda/zeebe/issues/16174
```

### Out of scope

* Providing external API will be done with https://github.com/camunda/zeebe/issues/15622 and is out of scope here

## Other Teams

The following teams are aware through (🔒 internal) https://github.com/camunda/product-hub/issues/1823:
- [x] [Operate](https://github.com/camunda/operate/issues)
- [x] [Tasklist](https://github.com/camunda/tasklist/issues)
- [x] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [x] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [x] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- Product Hub (🔒 internal): https://github.com/camunda/product-hub/issues/1823

**Comment by tmetzke** [comment]
All commands implemented, all additional attributes handled, closing this as done.
