### ISSUE TITLE
Chaos tests for scaling brokers

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#15546]
```[tasklist]
### Tasks
- [ ] https://github.com/zeebe-io/zeebe-chaos/issues/458
- [ ] https://github.com/zeebe-io/zeebe-chaos/issues/455
- [ ] https://github.com/zeebe-io/zeebe-chaos/issues/456
- [ ] https://github.com/zeebe-io/zeebe-chaos/issues/457
- [ ] https://github.com/zeebe-io/zeebe-chaos/issues/466
```
