### ISSUE TITLE
[EPIC] Job push for the Go client

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#15552]
## Introduction

We've already added and are making good use of job push with the Java client, it's time to extend the Go client to also support it.

## Task Breakdown

```[tasklist]
# Go client support
- [ ] https://github.com/camunda/zeebe/issues/15539
- [ ] https://github.com/camunda/zeebe/issues/15553
- [ ] https://github.com/camunda/zeebe/issues/15554
```

**Target release is 8.4**.

### Zeebe Process Test

There shouldn't be any changes required for Zeebe Process Test.

### Documentation

```[tasklist]
# Documentation
- [ ] https://github.com/camunda/camunda-docs/issues/3026
```

## Discussions and Decisions

- [Slack channel](https://camunda.slack.com/archives/C04G2F074UQ)

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/1869

**Comment by Zelldon** [comment]
@npepinpe can we close this ?

**Comment by npepinpe** [comment]
Yes :+1:
