### ISSUE TITLE
[EPIC] Expose native user tasks in the REST API

### ISSUE THREAD

**Issue by tmetzke** [camunda/zeebe#15622]
## Introduction

Expose native user tasks in the Zeebe REST API.

## Concept

* We provide the following REST endpoints for native user task interaction (more details in the (🔒 internal) [API document](https://docs.google.com/document/d/1W4XA74hmD8mpRucIBeupBe3KoTfAYR2iQ57n_Pf43U8/edit#heading=h.edwiy1s9vwdl)):
  * Complete task - `POST /user-tasks/{userTaskKey}/completion`
  * Assign task - `POST /user-tasks/{userTaskKey}/assignment`
  * Unassign task - `DELETE /user-tasks/{userTaskKey}/assignee`
  * Update task - `PATCH /user-tasks/{userTaskKey}`
* In general, the REST API endpoints are key-based, i.e. attributes referencing entities that also exist as records in Zeebe are named "XYZkey". This is consistent with other Camunda 8 REST APIs, e.g. the [Operate API](https://docs.camunda.io/docs/next/apis-tools/operate-api/overview/).
* The `candidateUsers` and `candidateGroups` are exposed as JSON arrays of Strings. Optionally, we can also change the internal record attributes from String to List properties. This would make the conversions easier.
* Zeebe user tasks transport the `zeebe:taskHeaders` extension elements from the model.

## Task Breakdown

```[tasklist]
### Broker
- [ ] https://github.com/camunda/zeebe/issues/16007
- [ ] https://github.com/camunda/zeebe/issues/16523
```

```[tasklist]
### Gateway
- [ ] https://github.com/camunda/zeebe/issues/16118
- [ ] https://github.com/camunda/zeebe/issues/16413
- [ ] https://github.com/camunda/zeebe/issues/16414
- [ ] https://github.com/camunda/zeebe/issues/16415
- [ ] https://github.com/camunda/zeebe/issues/16734
```

```[tasklist]
### Clients
- [ ] https://github.com/camunda/zeebe/issues/16447
- [ ] https://github.com/camunda/zeebe/issues/16662
- [ ] https://github.com/camunda/zeebe/issues/16663
- [ ] https://github.com/camunda/zeebe/issues/16664
```

```[tasklist]
### Testing
- [ ] https://github.com/camunda/zeebe/issues/16693
- [ ] https://github.com/camunda/zeebe/issues/16694
- [ ] https://github.com/camunda/zeebe/issues/16695
- [ ] https://github.com/camunda/zeebe/issues/16696
```

```[tasklist]
### Documentation
- [ ] https://github.com/camunda/camunda-docs/issues/3421
- [ ] https://github.com/camunda/camunda-docs/issues/3463
- [ ] https://github.com/camunda/zeebe/issues/16929
```

## Other Teams

- [ ] Tasklist is aware and aligned via the (🔒 internal) [API document](https://docs.google.com/document/d/1W4XA74hmD8mpRucIBeupBe3KoTfAYR2iQ57n_Pf43U8/edit#heading=h.edwiy1s9vwdl).

## Links

- Product Hub (🔒 internal): https://github.com/camunda/product-hub/issues/1823

**Comment by tmetzke** [comment]
Due to a change in the Zeebe user task REST API definition, we won't necessarily need a CLAIM command anymore. It could potentially be merged into the ASSIGN command processing. Note that the "action" attribute should always be "assign" by default for all commands invoked from this REST endpoint, regardless of what is invoked in Zeebe. As a result, there should be no event on the stream containing a "claim" action attribute value by default. Users can still provide this action value via the REST endpoint themselves, of course. Ultimately, the "assignment" REST endpoint implementer can decide on this.

**Comment by tmetzke** [comment]
REST endpoint documentation will be delivered with https://github.com/camunda/camunda-docs/issues/3421

**Comment by tmetzke** [comment]
All planned items delivered, closing this.
