### ISSUE TITLE
[EPIC] Zeebe REST API

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#15735]
## Introduction

Support a Zeebe REST API.

:warning: This issue is a work-in-progress.

## Other Teams

- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- [Product Hub (internal)
](https://github.com/camunda/product-hub/issues/1926)
- [Cross-team collaboration doc (internal)](https://docs.google.com/document/d/1IxHvRBNa6VtQN53QjbHxfckD8mJqYxEuh5Uvza4pq80/edit)
- [Zeebe breakdown document (internal)](https://docs.google.com/document/d/1qN9gJHtgwli5n7GBqU-mm1GngS7-pQ38-i3v7_ivQVI/edit#heading=h.eqd411rw2pi9)
- [Spike results](https://docs.google.com/document/d/1lzl1VKyl_YQUsL3kjc7U9gjg7PQW1ZfVzrkgJ-4nEws/edit#heading=h.tdp57bpktli2)

**Comment by tmetzke** [comment]
Closing this as it's handled in other team epics and issues
