### ISSUE TITLE
Supporting Rolling Updates

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#15879]
Rolling updates where brokers (and gateways) are upgraded from one minor version to the next are not officially supported yet.
While we already take great care to enable this in practice, it's time to commit to it fully and ensure that a rolling update always works and never results in incorrect processing results.

This will resolve https://github.com/camunda/product-hub/issues/256.

```[tasklist]
### User Documentation
- [x] Update guide allows rolling updates to the next minor version
- [x] Document required update sequence: Brokers first, then Gateways and finally Clients
- [x] How to do rolling updates using the official Helm charts
- [x] Edge cases and recovery when rolling update fails
```

```[tasklist]
### Developer Documentation
- [ ] Policy for breaking changes
- [ ] Guidelines for data migrations
```

```[tasklist]
### Processing Correctness
- [ ] https://github.com/camunda/zeebe/issues/15885
- [ ] https://github.com/camunda/zeebe/issues/16152
- [ ] https://github.com/camunda/zeebe/issues/16378
- [ ] https://github.com/camunda/zeebe/issues/7449
- [ ] https://github.com/camunda/zeebe/issues/15833
- [ ] https://github.com/camunda/zeebe/issues/16220
- [ ] https://github.com/camunda/zeebe/issues/16608
```

```[tasklist]
### Operations
- [x] Ensure that Helm charts configure the correct update strategy
- [ ] https://github.com/camunda/zeebe/issues/15678
- [ ] Step down as leader when stream processor fails
- [ ] https://github.com/camunda/zeebe/issues/13708
- [ ] Configuration to disable snapshot version checks
```

**Comment by felix-mueller** [comment]
@oleschoenburg I believe both mentioned issues have now been resolved by helm chart team :)
