### ISSUE TITLE
[EPIC] Provide a REST API infrastructure in Zeebe

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#15878]
## Introduction

This is the first increment for the implementation of a REST API in Zeebe. It aims to set up the REST API infrastructure in the Zeebe Gateway. It also provides an implementation of a single REST API endpoint to serve as an example for Zeebe devs to be able to implement additional REST API endpoints.

### Gateway

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/zeebe/issues/15908
- [ ] https://github.com/camunda/zeebe/issues/15925
- [ ] https://github.com/camunda/zeebe/issues/16163
- [ ] https://github.com/camunda/zeebe/issues/16164
- [ ] https://github.com/camunda/zeebe/issues/16165
- [ ] https://github.com/camunda/zeebe/issues/16118
- [ ] https://github.com/camunda/camunda-platform-helm/issues/1228
- [ ] https://github.com/camunda-cloud/camunda-operator/issues/2393
- [ ] https://github.com/camunda/camunda-platform-helm/issues/1493
- [ ] https://github.com/camunda/camunda-platform-helm/issues/1392
```

### Documentation

```[tasklist]
### Tasks
- [ ] camunda/camunda-docs#3221
- [ ] https://github.com/camunda/camunda-docs/issues/3277
- [ ] https://github.com/camunda/camunda-docs/issues/3278
- [x] Document the new REST API port for the Helm charts
- [x] Document REST API client authorization
- [x] Document REST API client/server secure communication
```

### Testing

/
### Zeebe Process Test

/

### Out of scope

/

## Other Teams

- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- [Product Hub (internal)
](https://github.com/camunda/product-hub/issues/1926)
- [Cross-team collaboration doc (internal)](https://docs.google.com/document/d/1IxHvRBNa6VtQN53QjbHxfckD8mJqYxEuh5Uvza4pq80/edit)
- [Zeebe breakdown document (internal)](https://docs.google.com/document/d/1qN9gJHtgwli5n7GBqU-mm1GngS7-pQ38-i3v7_ivQVI/edit#heading=h.eqd411rw2pi9)
- [Spike results](https://docs.google.com/document/d/1lzl1VKyl_YQUsL3kjc7U9gjg7PQW1ZfVzrkgJ-4nEws/edit#heading=h.tdp57bpktli2)

**Comment by npepinpe** [comment]
Done, the open issue in the controller is essentially finished.
