### ISSUE TITLE
Handle snapshots correctly during a rolling update

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#15885]
During a rolling update, snapshots can be replicated.

1. Old broker sends a snapshot to a new broker
2. New broker sends an old snapshot to an old broker
3. New broker sends a new snapshot to an old broker

Because our runtime state and our snapshots are not versioned in any way, we currently accept all of the above scenarios. This can lead to issues, especially in case 3 where an old broker suddenly has to operate on new runtime state that is possibly incompatible.

In the past, this has caused issues such as https://github.com/camunda/zeebe/issues/14406.

One idea to resolve this is to version our runtime state (and thus snapshots too). When an old broker recovers from a snapshot with a newer version, it should stop processing or replaying the partition to avoid incorrect processing results or data corruption. This would also resolve https://github.com/camunda/zeebe/issues/14406 because we could use the same version to decide whether migrations need to run or not. 
```[tasklist]
### Tasks
- [x] Write broker version to state after running migrations
- [x] Don't use snapshots from newer broker versions
- [x] Don't use snapshots from too old broker versions
- [ ] https://github.com/camunda/zeebe/issues/16812
```
