### ISSUE TITLE
Migrate element instances with incidents

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#15920]
Introduce a new `IncidentIntent` `MIGRATED`.

#### Add an event applier that updates the following properties of an incident record:

- `bpmnProcessId`: the BPMN ID of the target process definition
- `processDefinitionKey`: the key of the target process definition
- `elementId`: changes to the mapped element ID of the associated service task (note that the mapping may define the sourceElementId and the targetElementId as equivalent, in which case it stays the same)

#### In the `ProcessInstanceMigration` command processor, add:
- for each child instance of the process instance:
  - if this child has a process or job incident, append `Incident:MIGRATED` event

#### Create an applier class `IncidentMigratedApplied` that does the following:
- If the migrated `IncidentRecord` is a process incident, update the record in `processInstanceIncidentColumnFamily`
- If the migrated `IncidentRecord` is a job incident, update the record in `jobIncidentColumnFamily`

#### Add test cases:
- Add a test case for process incident
- Add a test case for job incident
- In test cases show that we can migrate a process instance, and can still resolve the incident.

#### Cleanup:
- Remove `requireNoIncident` validation
- Remove the A process instance with an incident sentence from the [limitations documentation](https://docs.camunda.io/docs/next/components/concepts/process-instance-migration/#limitations)

#### Update [API Definition document](https://docs.google.com/document/d/1V_sZQmr6KHFuAxovkxCLY4Kb38t3_r68TihCnHqhIbw/edit#heading=h.9xhvuj8z66v5):
- Add an incident section to the API definition so we can inform Operate about the upcoming changes. They'll need to consume the `zeebe-records_incident` index that has an intent `MIGRATED` for changes to incidents.

```[tasklist]
### Tasks
-[ ] https://github.com/camunda/zeebe/issues/16620
-[ ] https://github.com/camunda/zeebe/issues/16621
-[ ] https://github.com/camunda/zeebe/issues/16622
- [ ] https://github.com/camunda/zeebe/issues/16620
- [ ] https://github.com/camunda/zeebe/issues/16621
- [ ] https://github.com/camunda/zeebe/issues/16622
- [ ] https://github.com/camunda/camunda-docs/issues/3399
```

**Comment by korthout** [comment]
Thanks for the good description @berkaycanbc 👍 

Please also add an incident section to the [API definition](https://docs.google.com/document/d/1V_sZQmr6KHFuAxovkxCLY4Kb38t3_r68TihCnHqhIbw/edit#heading=h.9xhvuj8z66v5) so we can inform Operate about the upcoming changes. They'll need to consume the `zeebe-records_incidents` index for changes to incidents.

**Comment by berkaycanbc** [comment]
Thanks @korthout for the review, very useful suggestions! I updated the description based on them. 👍
