### ISSUE TITLE
Hot Backups: Do not pause exporter 

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/zeebe#16149]
## Goal 

See the most recent data in Operate, Tasklist, and Optimize while taking a backup.

## Proposed Implementation

The current implementation for taking backups in the C8 requires us to pause the exporter before the backup to keep the snapshots consistent with ES. This causes any application that's reading from ES to be waiting on updates until the backup finishes and the exporter gets manually resumed.

The proposed solution is to add a Soft Pause endpoint in the gateway that enables us to continue to export records without updating the last acknowledged record position. This enables us to continue to export data to ES without creating new snapshots while we do the backups.

In the same way that Pause and Unpause exporter functionality needs to persist this information in all replicas of portions, so will this soft pause. The proposed heuristic is that the hard pause supersedes the soft pause.

## Prototype

A simple prototype was created in order to prove the concept with an integration test that ensured that the records continued to be exported while the exported position of each partition status stayed the same. This exported position of the portion status is also updated to the last Acknolaged exported position once the soft paused gets removed.

The current limitation on the prototype:
- Small changes to the logic in how Soft Pause information Persisted in all Partions Replicas, as the prototype implementation might lead to some issues.
- Changes to the gateway endpoint to reuse the pause exporter 
- Missing extensive unit tests.
- Missing e2e tests.
- Missing test assuring last Acknowladged position should be still paused after new leader election

Estimation for implementation of the epic after defining the remaining topics in the preparation phase is 1 to 2 weeks.

## Additional Info

closes [#https://github.com/camunda/product-hub/issues/1785](https://github.com/camunda/product-hub/issues/2051)

The new endpoint added, reuses the paused endpoint by adding the boolean parameter `soft`:
`curl -XPOST 'localhost:9600/actuator/exporting/pause?soft=true'`
The endpoints are documented [here](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/operations/management-api/?exporting=softPause) 

Tracking issue to the implementation of the "Do not pause exporter" while on hot backups feature. 

```[tasklist]
## Preparation
- [x] Gather requirements
- [x] Breakdown into tasks
- [x] Implement prototype.
- [x] Define new API endpoint
- [x] Define way to propagate the information that updating the exporter position is paused
- [x] Define behavior of precedence between soft and hard pause
```

```[tasklist]
## Prototype
- [x] Prototype
```

```[tasklist]
## Implementation
- [ ] https://github.com/camunda/zeebe/issues/16344
- [ ] https://github.com/camunda/zeebe/issues/16642
- [ ] https://github.com/camunda/zeebe/issues/16874
- [ ] https://github.com/camunda/zeebe/issues/17256
```

```[tasklist]
## Tests
- [x] Unit tests
- [x] QA tests
- [x] Last Acknowladged position should be still paused after new leader election
- [x] Manual tests in benckmark
- [x] Manual test: perform a backup
```

```[tasklist]
## Changes in Documentation
- [ ] https://github.com/camunda/zeebe/issues/17424
- [ ] https://github.com/camunda/zeebe/issues/17425
```

```[tasklist]
### Additional
- [x] Notify controller team about the changes in the APIs
- [x] Backport changes to 8.2, 8.3, 8.4 and 8.5
```

**Comment by Sijoma** [comment]
This would be great to have to be in a position to more easily do backups for a full Kubernetes cluster during incidents etc.

**Comment by rodrigo-lourenco-lopes** [comment]
We just finished the last step for QA so I will mark this epic as done.
