### ISSUE TITLE
Provide an OpenAPI specification in the `gateway-protocol` module

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#16163]
### Description

An OpenAPI specification document is provided in the Zeebe `gateway-protocol` module.

```[tasklist]
### Tasks
- [x] An OpenAPI specification document for the Zeebe REST API is created in the Zeebe `gateway-protocol` module.
- [x] The OpenAPI specification is defined in the YAML format.
- [x] The specification uses OpenAPI version `3.0.2`
- [x] The Zeebe REST API is versioned
- [x] Initial REST server variables are defined (`host`, `port`, `schema`)
```
