### ISSUE TITLE
[ZPA] Improve operational quality of services 

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#16276]
## Introduction

In an effort to improve the operations quality of product teams, opportunities for growth were raised during the [Platform Operations Quality Assessment](https://docs.google.com/spreadsheets/d/1SFt0O6u0cqt6_9izfRlJdCPF_dCYGe_AeNOTj9vxeow/edit#gid=1885598468) of the Zeebe Process Automation team (ZPA). This issue provides an overview of these issues.

## Task Breakdown

This is a work in progress. At this time, it's just a copy of the results from the assessment. We'll need to transform this into actionable tasks and possibly break them up further.

```[tasklist]
### Tasks
- [ ] Several resources that exist in the Zeebe repo, are covering parts of the ZDP, not the ZPA team, which need to be clarified or adjusted.
- [ ] We should share more knowledge about how to add metrics and how to consume them, build dashboards, etc.
- [ ] We should discuss more and try to understand what is bad for our users (like when it takes long to trigger a timer), and based on this write metrics and alerts.
- [ ] It was raised that we currently have two teams sharing one medic, which makes it sometimes hard for the people in charge (especially new joiners). Might be worth investigating whether this can be split off.
- [ ] Changes to incident handbooks or processes, seem to be sometimes missed or not communicated well enough, we should improve that.
- [ ] We should think about whether we need more configurations that we can change on runtime, to avoid downtime and make it more flexible for the users.
- [ ] We need clarity on dependency update PRs that are not auto-mergeable.
- [ ] Get better hands-on experience with the service we provide to understand whether resources need to be adjusted (might be an opportunity to save costs or even improve availability).
- [ ] A common pattern/strategy or format on how to write good user-facing error messages. If they follow always the same pattern they provide a better UX and are also better to understand, etc.
```

### Out of scope

None yet.

## Discussions and Decisions

...

## Links

- Product Hub (internal): Not tracked by product hub
- [Operations Quality Assessment](https://docs.google.com/spreadsheets/d/1SFt0O6u0cqt6_9izfRlJdCPF_dCYGe_AeNOTj9vxeow/edit#gid=1885598468)

**Comment by korthout** [comment]
- https://github.com/camunda/zeebe/issues/16579

**Comment by megglos** [comment]
> A common pattern/strategy or format on how to write good user-facing error messages. If they follow always the same pattern they provide a better UX and are also better to understand, etc.

[current error message guidelines ](https://github.com/camunda/zeebe/wiki/Error-Guidelines#messages)lack clarity on engine/BPMN processing error messages

**Comment by korthout** [comment]
Closing this as ZPA doesn't exist anymore
