### ISSUE TITLE
[EPIC]Migrate Spring Zeebe SDK to Zeebe

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/zeebe#16816]
## Introduction

Migrate Spring Zeebe SDK.

## Concept

- Migrate relevant `spring-zeebe` modules to `zeebe` repository:
   - spring-starter
   - spring-client-annotations
   - spring-client-zeebe
   - spring-client-common
- Provide support for both Zeebe REST and gRPC API 
- Remove deprecated annotations as well as Operate and Tasklist
- Refactor and clean up the code (1st iteration, with focus on removing not needed components and code)

## Task Breakdown

```[tasklist]
### Clients
- [ ] https://github.com/camunda/zeebe/issues/16875
```

```[tasklist]
### Spring Boot Starter
- [ ] https://github.com/camunda/zeebe/issues/16876
- [ ] https://github.com/camunda/zeebe/issues/17073
- [ ] https://github.com/camunda/zeebe/issues/17077
- [ ] https://github.com/camunda/zeebe/issues/17123
```

### Documentation

- [ ] Align with DevEx where and how to include documentation on the start into docs.io

### Out of scope

- [spring-boot-starter-camunda-test](https://github.com/camunda-community-hub/spring-zeebe/blob/main/test/embedded/pom.xml)
- [spring-boot-starter-camunda-test-testcontainer](https://github.com/camunda-community-hub/spring-zeebe/blob/main/test/testcontainer/pom.xml)

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/2148
- Spike PR: https://github.com/camunda/zeebe/pull/16795

**Comment by tmetzke** [comment]
As far as I can see, we did not preserve the git history of the code and commits. Was that intentional? I think it would have been a nice way of honoring the effort the community put into the project in the past.

**Comment by jonathanlukas** [comment]
From https://camunda.slack.com/archives/CSQ2E3BT4/p1712219810864509

The spring zeebe properties restructure (https://github.com/camunda-community-hub/spring-zeebe/commit/ef375370c2c326055b2e0d1078dd015ca8efe90b) contains 2 aspects:
* the property restructure is fully backwards-compatible (in theory) as it contains a mechanism for each property to be used from new or old configuration
* the property restucture moves away from the zeebe. namespace for properties in favor of camunda.client. which would allow for moving forward with a unified API client

**Comment by ana-vinogradova-camunda** [comment]
Closing this issue as the migration is complete. A new Epic for further work will be created and linked to this Epic.

> As far as I can see, we did not preserve the git history of the code and commits. Was that intentional? I think it would have been a nice way of honoring the effort the community put into the project in the past.

It wasn't intentional, and I think you are right saying it would have been a nice way of honoring the effort of people. Let us think what we can do about it.

**Comment by tmetzke** [comment]
> > As far as I can see, we did not preserve the git history of the code and commits. Was that intentional? I think it would have been a nice way of honoring the effort the community put into the project in the past.
> 
> It wasn't intentional, and I think you are right saying it would have been a nice way of honoring the effort of people. Let us think what we can do about it.

It depends a bit on priority, I guess. You could remove the code again, add the git history and thus the code properly, and add an adjustment commit on top that re-creates the state of the code we currently have. It's a one-off effort, I think. But it's also effort.
