### ISSUE TITLE
The REST API authenticates requests through Identity

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#16835]
```[tasklist]
### Tasks
- [x] Identity authentication is enabled via profile
- [x] Identity authentication not applied to the management endpoints
- [x] Authentication failures are returned as problem+json
- [x] Identity is used to verify token when enabled
- [x] Identity is used to fetch tenant IDs when enabled
- [x] Tenant IDs are injected into the request context when enabled
```
