### ISSUE TITLE
[EPIC]: Combine multiple applications into a single shippable jar

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#17062]
## Description

Based on the initiative of streamlining our applications we want in the first iteration to create a single jar, which combines our different components (in the first step Zeebe + Operate). As a follow-up (next step) we plan to work on creating a single application, that allows us to bootstrap everything together.

## Breakdown

- [ ] Gather input from @romansmirnov and its POC https://github.com/camunda/zeebe/pull/16943
- [x] Prepare Operate's dependencies, to align with Zeebe
  - [x] Enforce dependencies (cleanup) add used transient dependencies, remove unused, etc. https://github.com/camunda/zeebe/pull/17031
  - [x] **>>After release<<** Use Zeebe parent pom, as Operate pom (move dependency declarations up to Zeebe)
  - [x] Clean up Operate pom's, remove duplicated plugin definitions, etc.
- [ ] Make sure both CI's are executed on dependency changes in parent
- [x] <Optional> Migrate Operate to Java 21
- [ ] Move the Application class to the `dist/` folder
- [x] Remove obsolete Operate distro folder
- [x] tbd... create single jar with multiple Main classes

```[tasklist]
### Tasks
- [x] Prepare Operates dependencies, to align with Zeebe configs
- [x] Enfore dependencies
- [x] Use Zeebe parent POM
- [x] Rename Zeebe parent POM - artificats to something related to C8
- [x] Make sure both CI's are executed on dependency changes in parent
- [x] Migrate Operate to Java 21
- [ ] Move application class to `dist/` folder
- [x] Remove obsolete Operate dist folder
```

related to https://github.com/camunda/product-hub/issues/2277

**Comment by romansmirnov** [comment]
@Zelldon, sharing some notes - that I have in mind - from my POC:

* Spring Webflux and Spring Web, aka Reactive and Servlet
  * Zeebe uses Spring Webflux and starts a _reactive_ web application.
  * Operate uses Spring Web and starts a _servlet_ web application.
  * Bundling both (Spring Webflux and Spring Web) into a Single Jar, Zeebe, and Operate can still be started separately as of right now.
  * But with Spring Web, Tomcat is on the classpath, and Spring will prefer Tomcat to start as a _reactive_ web application when starting Zeebe. It will no longer use Netty for the _reactive_ web application.
  * How to deal with that?
    * IMO, nothing must be done to achieve the Single Jar because Zeebe and Operate can still run separately. (It will become relevant later with the Single Application step)
* `application.properties`
  * The Single Jar will contain an `application.properties` file currently used by Zeebe.
  * Operate would also apply that `application.properties` file if not otherwise declared.
  * For now, I suggest renaming the file to `application-zeebe.properties` and adding the profile `zeebe` when starting the Broker and/or the Standalone Gateway. That way, Zeebe will only use the properties file.
  * The same applies to Operate, which contains an `application.yml` file. At least in the POC, I renamed it to `application-operate.yml` and added the profile `operate` when starting Operate.
  * An alternative would be consolidating both properties files and the Spring configuration between Operate and Zeebe.
* ` tbd... create single jar with multiple Main classes`
  * As the issue description suggests, I would propose moving Operate's `Application.java` to the `dist` module. With that, we start following one way of building the distribution.
  * We must ensure that the development setup still works, i.e., potentially, the Make commands must be adjusted to point to the correct `Application`.
  * However, I would suggest having separate start scripts: `broker`, `gateway`, `restore`, `operate`, and `migrate`
  * `operate` will be the script to start Operate, and `migrate` will be the script to start Operate's schema migration.

**Comment by Zelldon** [comment]
I think we can mark this as done. With alpha1 we shipped Tasklist, Operate and Zeebe as part of one jar.
