### ISSUE TITLE
Open links to other C8 apps in the same tab

### ISSUE THREAD

**Issue by pedesen** [camunda/zeebe#17122]
### Description

As an Operate user, I want to open links to other applications in the same tab so I can keep a clean and productive workspace

Product hub issue: https://github.com/camunda/product-hub/issues/1225

### TODO
- [x] remove `target=_blank` from the app switcher of the app header component

### How to test

- Open Operate in C8 ([test cluster](https://chaos-1.operate.ultrawombat.com/09897856-44f9-41cf-a8d6-3438d8b05db2/))
- Click the "Camunda apps" button (top left)
- Navigate to each app and ensure they're opened in the same tab

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [x] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered
