### ISSUE TITLE
Bump dmn-js dependency

### ISSUE THREAD

**Issue by pedesen** [camunda/zeebe#17179]
### Description

Bump dmn-js to the most recent version and fix all issues related to this. Some checks in renovate PRs are failing.

### TODO

- [x] bump dmn-js version
- [x] Investigate why visual regression tests are failing
- [x] Investigate why a11y tests are failing
- [x] Fix all issues

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered
