### ISSUE TITLE
Outline REST API proposal handling target process

### ISSUE THREAD

**Issue by tmetzke** [camunda/zeebe#17302]
**Description**

* Create an outline of the target process for handling new REST API proposals in the future.
* Add necessary resources for the proposal to work, e.g. an issue template.
* This should include:
  * How and where can proposals be submitted?
  * Who evaluates them?
  * How are decisions for a proposal made and by whom?
  * Who drives documenting and (optionally) implementing a proposal's results?

**Comment by tmetzke** [comment]
I created a proposal at 🔒 https://modeler.cloud.camunda.io/projects/9e2afaea-41a9-4547-8c05-1f0a3907442f--c8-rest-api and invited @megglos for now to review it.

**Comment by megglos** [comment]
> I created a proposal at 🔒 https://modeler.cloud.camunda.io/projects/9e2afaea-41a9-4547-8c05-1f0a3907442f--c8-rest-api and invited [@megglos](https://github.com/megglos) for now to review it.

LGTM! Shall @aleksander-dytko also take a look?

**Comment by tmetzke** [comment]
I created a reactive process as an alternative, listening to GitHub events and using Slack for tasks: https://modeler.cloud.camunda.io/diagrams/be7d6e26-e051-4c15-800d-b6b57dadab2c--proposal-process-reactive

**Comment by tmetzke** [comment]
@aleksander-dytko and I agreed on the following:
* @aleksander-dytko takes ownership of driving future REST API proposals.
* Proposals must be made through GitHub issues in the `camunda/zeebe` repository, adding labels `component/c8-api` and `kind/proposal`.
* @aleksander-dytko qualifies proposals from a product perspective, i.e. Do we consider this topic relevant for our APIs?
* @aleksander-dytko pulls in additional technical expertise where needed, @tmetzke serves as the initial technical contact point and delegates if necessary (if the load becomes too high, we can adjust this in the future).

## Tasks (tackled by @tmetzke)
* [x] Create a `@c8-api-guidelines-dri` group in Slack to easily address the DRI(s) (makes it easy to change DRIs transparently in the future)
* Set up automation to
  * [x] Add proposals to the [Proposal tracker](https://github.com/orgs/camunda/projects/111) automatically.
    * Handled by a project workflow in the proposal tracker
    ![image](https://github.com/camunda/zeebe/assets/586643/c0c5b926-61b6-42e1-95c5-94fc4f303266)
  * [ ] Inform about new proposals in [#top-c8-rest-api-guidelines](https://camunda.slack.com/archives/C06P6H2FL5T) when they are added to the proposal tracker, pinging the `@c8-api-guidelines-dri` group.
  * [ ] Capture changes to the proposal status and inform the [#top-c8-rest-api-guidelines](https://camunda.slack.com/archives/C06P6H2FL5T) channel accordingly (e.g. when rejecting proposals, moving them to peer review, and having them documented)

When those tasks are done, the handover to @aleksander-dytko is completed.
