### ISSUE TITLE
[EPIC] Process Instance Migration Phase 2: Common use cases

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#17346]
## Introduction

Second phase of the [Process Instance Migration](https://docs.camunda.io/docs/next/components/concepts/process-instance-migration/) concept.

This phase expands the basic migration introduced in #14907 with some of the most common elements and use cases.

## Concept

With #14907, basic process instance migrations were made possible. Allowing users to [change the process instance flow for inactive parts](https://docs.camunda.io/docs/next/components/concepts/process-instance-migration/#changing-the-process-instance-flow-for-inactive-parts) and to [change the active elements](https://docs.camunda.io/docs/next/components/concepts/process-instance-migration/#changing-the-active-elements). Both require mapping instructions for the active elements to migrate. Mapping instructions, and thus migrations, were limited to service tasks only. Global and local variables are automatically migrated along with the active elements. Tasks with incidents or catch events could not be migrated yet.

In this phase, we're expanding the functionality to user tasks (with support for both Job Worker and zeebe user tasks) and [embedded subprocesses](https://docs.camunda.io/docs/next/components/concepts/process-instance-migration/#migrating-active-elements-inside-embedded-subprocesses). We're also allowing the migration of tasks with incidents to [correct mistakes in a process instance](https://docs.camunda.io/docs/next/components/concepts/process-instance-migration/#correcting-mistakes-in-a-process-instance). Lastly, we're adding the first support for [dealing with boundary events](https://docs.camunda.io/docs/next/components/concepts/process-instance-migration/#dealing-with-attached-boundary-events), but limit it to unmapped message boundary events only.

## Task Breakdown

```[tasklist]
### Process Instance Migration Phase 2
- [ ] https://github.com/camunda/zeebe/issues/15919
- [ ] https://github.com/camunda/zeebe/issues/16383
- [ ] https://github.com/camunda/zeebe/issues/16384
- [ ] https://github.com/camunda/zeebe/issues/15920
- [ ] https://github.com/camunda/zeebe/issues/15923
- [ ] https://github.com/camunda/camunda-docs/issues/3517
- [ ] https://github.com/camunda/zeebe/issues/16249
```

## Discussions and Decisions

- https://github.com/camunda/zeebe/issues/16999

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/1829
