### ISSUE TITLE
Adjust backend after 8.5.0 release

### ISSUE THREAD

**Issue by sdorokhova** [camunda/zeebe#17371]
### Description

This description is copied from https://github.com/camunda/operate/issues/2084. Please check if it's still up-to-date and adjust if needed.

### TODO

Following adjustments are needed after minor release (X.Y.0) is out:

- [x] 1. Create importer module for upcoming minor version (X.Y+1.0).
  * module name: importer-v(Y+1)
  * content must be copied from importer-vY
  * Package must be renamed: org.camunda.operate.zeebeimport.vY -> org.camunda.operate.zeebeimport.v(Y+1)
  * ElasticsearchBulkProcessor#getZeebeVersion must return (Y+1)
  * add new module to parent pom.xml
- [x] 2. Remove old importer module: importer-v(Y-1)
~~3. Fix test ImportSeveralVersionsIT: adjust zeebe-versions.properties (contains Zeebe Docker image versions), config files adjustment may also be needed~~ (test is ignored for a long time)
- [x] 4. Adjust migration tests

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered
