### ISSUE TITLE
Relicense to Camunda License 1.0

### ISSUE THREAD

**Issue by romansmirnov** [camunda/zeebe#18104]
**Description**

```[tasklist]
### Tasks
- [x] Remove Zeebe Community License from the repository
- [x] Include new [Camunda License](https://docs.google.com/document/d/1xO8c6LgdKI5Dj3bzzgcL-l0xnQb-bs5mnrJXvuh3tcs/edit)
- [x] Update source code license headers (Zeebe, Tasklist, Operate)
- [x] Update the Readme and the contributor guidelines
```
