### ISSUE TITLE
[Epic] Evaluate DMN decisions

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#8083]
**Description**

This issue represents the epic [Evaluate DMN decisions](https://github.com/camunda-cloud/zeebe/milestone/70). All required issues are listed below:

- Deployment: 
  - [x] #8060
  - [x] #8061 
  - [x] #8172
  - [x] #8173
  - [x] #8063
  - [x] #8067
  - [x] #8069
  - [x] #8174
  - [x] #8072
  - [x] #8077
  - [x] #8567
  - [ ] #8806 ¹
- Response include decisions: ¹
  - [x] #8065 
  - [x] #8074
  - [x] #8075
  - [x] #8076
- Execution:
  - [x] #8081
  - [x] #8082 
    - [ ] https://github.com/camunda-community-hub/dmn-scala/issues/104 ¹
  - [x] #8080 
    - [ ] #8571 ¹ 
  - [x] #8779 
  - [ ] #8093 ¹
    - [x] https://github.com/camunda-community-hub/dmn-scala/issues/105 ¹
  - [ ] #8092 ¹
    - [ ] https://github.com/camunda-community-hub/dmn-scala/issues/106 ¹
  - [x] #7054 (to return a temporal output value of a decision)
- Incidents:
  - [x] #8094 
  - [x] #8095
- History/Audit/Monitoring/Metrics:
  - [x] #8112 
    - [ ] https://github.com/camunda-community-hub/dmn-scala/issues/136 ¹ 
  - [x] #8115
  - [x] #8116
  - [x] #8235 
  - [x] #8643 ¹
  - [x] #8867 ¹
  - [ ] https://github.com/camunda-cloud/zeebe-analytics/issues/22 ¹
  - [x] #8805
- Documentation:
  - [x] https://github.com/camunda-cloud/camunda-cloud-documentation/issues/421
  - [x] https://github.com/camunda-cloud/camunda-cloud-documentation/issues/422
- Clean up:
  - [ ] #8653 ¹
  - [ ] #8807 ¹
  - [ ] #8808 ¹
 
¹ - not required for MVP. It should be done but can be postponed if necessary.

**Comment by korthout** [comment]
@saig0 I think we're missing an issue to cover deployment rejection for missing `resultVariable ` as described in https://github.com/camunda-cloud/zeebe/issues/8060.

**Comment by korthout** [comment]
https://github.com/camunda-cloud/zeebe/issues/8069 implies updating the decision and decision requirements using a version number, but this should probably be an additional issue.

**Comment by saig0** [comment]
The epis is done. All major issues were implemented. :rocket:
