### ISSUE TITLE
As a Camundo, I can measure Camunda Platform 8 Performance KPIs and analyze them in Grafana

### ISSUE THREAD

**Issue by romansmirnov** [camunda/zeebe#9044]
**Description**

According to our [performance goals](https://docs.google.com/document/d/1AM9Qbm4wSxGiyQ39jeUlNHBB9srU0o56do5j4r1mLDk/edit#heading=h.l6jp1qal1m6m), we want to measure some performance KPIs across the Camunda Platform 8 (which includes Zeebe, Operate, Tasklist, and Optimize). In the first iteration, we are aiming to measure the following KPIs:

* Zeebe's Throughput:
  * PI/m: How many process instances are _started_ and _completed_ per minute
  * Tasks/m: How many tasks (meaning, events, and gateways are not included) can be executed (_started_ and _completed_) per minute
  * FNI/m: How many flow nodes (meaning, all BPMN symbols) can be executed (_started_ and _completed_) per minute
* Webapps (Operate, Tasklist, and Optimize):
  * Realtime-ness: Measures how long a change in Zeebe gets visible in the respective Webapp, for example, in which time is an incident created in Zeebe visible in Operate.
  * Response time: Measures the execution time of a specific REST/GraphQL endpoint for each Webapp

Please Note:
* The list might not be complete, and in the future, we might want to extend or adjust the KPIs; however, for now, we will focus on the above documented KPIs.
* Each platform component has already some KPIs and metrics defined. Those KPIs and metrics allow each team to deeply analyze their application's health and other aspects as required. While we might reuse some KPIs, we won't change the already existing Grafana boards showing those KPIs and metrics

We differentiate between two "typical" BPMN processes:
  * _Average Scenario_: A typical _average_ [BPMN process with 16 Flow Nodes](https://github.com/camunda/zeebe/blob/5131e51563236444b1f278ce44b43e22cd7befff/benchmarks/project/src/main/resources/bpmn/typical_process.bpmn) (i.e., 10 Service Tasks, 3 timer events, 1 Exclusive Gateway with simple expression) and a typical set of [14 process variables](https://github.com/camunda/zeebe/blob/5131e51563236444b1f278ce44b43e22cd7befff/benchmarks/project/src/main/resources/bpmn/typical_payload.json) as payload
  * _Complex Scenario_:  A typical _advanced_ BPMN process with 10-15 Flow Nodes. In addition to the _average_ BPMN process, it includes a Call Activity in a multi-instance fashion (calling 100 multi instances) and a Business Rule Task with DMN (3 Input, 1 Output, 10 rows).

Additionally, we differentiate between different load scenarios in a Camunda Platform 8 Cluster:
* _Low load_: The cluster is underutilized. For example, one developer uses the platform to explore the platform's capabilities.
* _Sustainable load_: The cluster is, on average, on a steady load that does not lead to any problems
* _Peak load_: Time frames with higher loads.

In this iteration, we focus on the _average scenario_ with a _sustainable load_.

**Requirements:**
* To execute a performance benchmark, the "system under test" can be defined, including the Camunda Platform 8 version (or generation) and the Cluster Plan.
* When starting a performance benchmark, the "system under test" is started in the Camunda Cloud environment.
* The performance benchmark includes an application that interacts with the "system under test". Therefore, the application consists of a _starter_ and a _worker_:
  * The _starter_ deploys the _average_ BPMN process and starts process instances of it at a steady rate.
  * The _worker_ subscribes for newly available jobs to activate, execute and complete them.
* A Grafana board exists that displays the performance KPIs.

**Task Breakdown:**
- [ ] Build an end-to-end proof of concept with the following focus:
  - [ ] Define, set up, and bootstrap the "system under test" (the system should consist of Zeebe, Operate, Tasklist, and Optimize)
  - [ ] Deploy an application containing a starter and worker that creates load on the "system under test".
  - [ ] Grafana Board showing the Zeebe's throughput KPI
- [ ] Make the POC ready-to-use
- [ ] Include Operate's KPIs into the Grafana Board:
  - [ ] Identify if all necessary metrics are available to measure the Webapps related KPI.
  - [ ] If not, then implement those required metrics.
  - [ ] Identify a typical request to measure the response time.
  - [ ] Trigger the request automatically
  - [ ] Expose Operate's KPIs in the Grafana Board
- [ ] Include Tasklist's KPIs into the Grafana Board:
  - [ ] Identify if all necessary metrics are available to measure the Webapps related KPI.
  - [ ] If not, then implement those required metrics.
  - [ ] Identify a typical request to measure the response time.
  - [ ] Trigger the request automatically
  - [ ] Expose Tasklist's KPIs in the Grafana Board
- [ ] Include Optimize's KPIs into the Grafana Board:
  - [ ] Identify if all necessary metrics are available to measure the Webapps related KPI.
  - [ ] If not, then implement those required metrics.
  - [ ] Identify a typical request to measure the response time.
  - [ ] Trigger the request automatically
  - [ ] Expose Optimize's KPIs in the Grafana Board
- [ ] Define the parameters of a sustainable load (for the different Cluster plans):
  - [ ] How many process instances should be started per second?
  - [ ] To simulate actual work, how much time should a worker spend on "executing" a job?
  - [ ] At which rate do we want to trigger the Webapp's requests?
- [ ] process-related topics:
  - [ ] When do we want to run the performance benchmarks?
  - [ ] How long should a performance benchmark run?
  - [ ] Which versions do we want to be under a performance benchmark test?
  - [ ] ...

**Comment by Zelldon** [comment]
@menski @romansmirnov Can this be moved to a different repo like camunda/camunda-platform ? :thinking:

**Comment by menski** [comment]
I don't think the platform repo is fitting. But I already talked with Felix that we might need a cross project issue tracker for such initiatives. I will look into it next week

**Comment by Zelldon** [comment]
@menski any updates on this? Like having a separate project for this?

**Comment by npepinpe** [comment]
@Zelldon - I think this is what you're working on these days, sort of. Feel free to close or keep it open for yourself :)
