### ISSUE TITLE
[EPIC] A technical concept on how to take backup of a Camunda Platform 8 cluster without downtime

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9103]
**Description**

Objective: Users can take backup of a Camunda Platform 8 cluster without downtime.

Scope: The goal of this issue is to have a technical concept on how to take backups of all components in a camunda 8 cluster without downtime. This includes backup of zeebe, operate, optimize, tasklist. We should also have a concept on how to recover from a given backup.

Taking backup of a distributed systems with multiple components is non-trivial because we have to ensure that the data from all components are "consistent" in the backup. As part of this issue, we will define what "consistency" means here. We will find how to coordinate backups of these components so that when the cluster recovers from these backups then all components are in a "consistent" state. Taking backup of only a zeebe cluster is also non-trivial for the same reasons. The backup from multiple brokers should be "consistent". 

Tasks:
- [x] Understand technical limitations and requirements
	- [x] #9104
	- [x] #9105
		- [x] Consistency requirements of Operate data	
		- [x] Consistency between Zeebe and Operate
	- [x] #9107
		- [x] Consistency requirement of Tasklist data
		- [x] Consistency between Zeebe and Tasklist
	- [x] #9106
		- [x] Consistency of Optimize data
		- [x] Consistency between Zeebe and Optimize
	- [x] ~#9108~
	- [x] ~#9109~
	- [x] ~#9110~
	- [ ] Check whether curator affects backup process
- [x] Research solutions 
	- [x] https://github.com/camunda/zeebe/issues/9222
	- [x] #9260
	- [x] Discuss approaches to take backup of Operate, Optimize, and Tasklist
	- Uncoordinated backups
		- We allow backups to be inconsistent, but then we can identify it and fix it during recovery. Evaluate if this is possible. Both with in zeebe and among all components in Camunda 8 cluster.
	- Coordinated backups
		- Example - Communication-induced checkpointing algorithms. [Ref](https://docs.google.com/document/d/1dNg2LR6TVEFGSfGIe2gnHEvoOKeef3t5TUm578t5c-s/edit#heading=h.bgvuhxc41wna)
		- ..
	- Other approaches?
- [x] Write down a technical document with the final concept
	- [x] #9375
	- [x] [Write a technical document on how to take backup of c8 cluster without downtime.](https://docs.google.com/document/d/1JcY-qqV6qYaT6ceUpZan3GHvQQaQp9VZA984BDu3tr8/edit?usp=sharing) (Internal doc)
