### ISSUE TITLE
[EPIC] Implement a prototype for taking backup of a zeebe cluster without downtime

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9111]
**Description**

Implement a prototype for taking backup of a Zeebe brokers, with out other components in a camunda 8 cluster. The goal is to evaluate the complexity and feasibility of proposed solution in #9260 

#### Goals

- Identify blockers in the implementation
- Get some idea on how to test it
- Understand the complexity and thus helps plan the implementation

Out of scope:
- Fully functional and fully tested

Tasks breakdown:
- [ ] TODO

**Comment by deepthidevaki** [comment]
With the prototype, we would like to get some idea on the following questions.
- Interaction between Coordinator and zeebe brokers. 
	- How can coordinator know about progress/failures of backup.
	- Who marks the backup as completed?
	- Failure scenarios
- How to implement restore process.
- How to copy backup to remote storage.
	- Interface to the remote storage
	- Failure scenarios etc.
- How to lock snapshots and prevent compaction.
- Changes in StreamProcessor
	- New record types, new fields in existing commands
	- Additional data to be stored in state
	- How to not leak backup logic into engine.
- Are there other edge cases that are not covered in the proposal?

**Comment by deepthidevaki** [comment]
I have started to implement a prototype. In the prototype I will try to answer the following questions.

- [ ] How to prevent compaction of the logs and deletion of snapshot required by the backup in progress.
- [ ] How BackupActor can read snapshots and segments files to copy them to the backup storage without breaking the abstractions .
- [ ] How to add new commands for the checkpoints.
	- StreamProcessor must recognize these commands and processes them instead of forwarding them to the engine.
- [ ] How to add checkpointId to the remote commands sends between partitions.
	- Currently the commands are send by the engine directly. How to abstract this info from the engine.
- [ ] Identify the "data structures" of a backup
	- How to represent a backup of partition taken by a broker. 
	- How to mark it as failed or completed.
- [ ] How to implement the restore operation.

**Comment by deepthidevaki** [comment]
First, I looked in to how to prevent compaction of the logs and deletion of snapshot required by the backup in progress.

We introduced a `BackupActor` which should only be active in the Leader role. BackupActor is the one actually "taking" the backup when StreamProcessor triggers it.

To prevent compaction, I added new methods to the existing interface `LogCompactor` to enable and disable compaction. BackupActor will disable compaction while it is taking backup and re-enable it once the backup is completed or failed. The current implementation have some problems when there are continuous overlapping backups. That means, in worst case it can happen that the compaction is disabled for a long time because before one backup is finished, another backup started which disabled the compaction. To prevent this, we would need to provide more information and find a "minimum" compactable index from the ongoing backups. There is scope for improvement, which we can leave it to implementation phase.

Preventing deletion of snapshot is relatively easy. SnapshotStore exposes a new interface to lock/unlock snapshot. SnapshotStore keep track of the locked snapshots in an in-memory data structure. When a snapshot is locked it is not deleted even when a new snapshot is taken. Deletion of a snapshot is done when commiting a new snapshot. Here we check if the snapshot is locked before deleting it. When a snapshot is unlocked, it is deleted if there is already a newer snapshot
 
An edge case here is : When multiple concurrent backups locks the same snapshot, if one backup unlocks the snapshot the snapshot should remain locked. To handle this, in the prototype we use a Map[snapshot -> lockCount] to keep track of the locked snapshot. When a snapshot is unlocked the lockCount = 0 or the snapshot does not exists in the map. A snapshot is locked by increasing the counter in the map.

Another edge case is what happens when the snapshot is not unlocked due to failovers. It can happen that the leader locks the snapshots, start taking the backup, transition to follower. This case is not handled in the prototype. In this case what we can do is that the BackupActor can proactively unlocks all the locked snapshot while closing. After a restart, all the older snapshots are pruned by the SnapshotStore anyway. So that case need not be handled.

**Comment by deepthidevaki** [comment]
**How to add new commands for the checkpoints.** 

In the prototype, I added new ValueType and Intents for checkpoint-create and checkpoint-created records. This is added as an engine command. To process these records a CheckpointCreateProcessor and CheckpointCreatedHandler is added to the engine processors and engine event handlers. 
This was quite easy to do without breaking any compatability. However, we shouldn't add the processing for checkpoint into the engine. Checkpoint processors should be outside of engine. Ideally, we should define a new record type for these additional  records which are not part of process engine. One way to do it will be to add additional metadata in `LogEntryDescriptor`. But, it is tricky to add new fields to it because it is not an sbe message. There is a version field in it, though we never use it. We could start using the version, and then eventually migrate to sbe for future maintainability.


**How to add checkpointId to the remote commands sends between partitions.**

- Previously deployment commands and message subscription commands were send and received by different modules/classes. First, I consolidated inter-partition communication into a single sender/receiver. This helps to have a single way of sending commands between partitions.
- Defined a new Inter-partition message schema which contains the checkpointId, parttionId and the actual command.
- PartitionCommandSender creates the the inter-partition message with the current checkpointId. It gets the checkpointId from the StreamProcessor. 
- A RemoteCommandHandler that receives all remote commands (deployment, subscription, and deployment response). When receiving a remote command, it first writes a checkpoint record to the logstream and then writes the actual command. This way we don't have to add checkpointId to the existing records. The streamprocessor will process the checkpoint record as usual. As an optimization, the RemoteCommandHandler can check if the current checkpointId and write the checkpoint record only if the local checkpointId < the remote checkpointId.

**Comment by deepthidevaki** [comment]
How BackupActor can read snapshots and segments files to copy them to the backup storage without breaking the abstractions:

Copying snapshots is straight forward. Snapshot API already expose the path to the snapshot directory. BackupActor can access it and copy the files. However, for segments it is not that easy. The journal is hidden away in the raft. We can pass the `dataDirectory` of a partition to the BackupActor. But dataDirectory contains files other than segments, such as raft metastore and config. In the prototype, we filtered the segment files by matching the file extenstion with `.log`. But this is breaking the abstraction to the journal. Another option would be to
- Build SegmentedJournal in Broker and pass it to raft, instead of raft building its journal.
- SegmentedJournal should expose api to get all segments.
- BackupActor gets `SegmentedJournal` via its constructor instead of the path to the dataDirectory.
- BackupActor uses `SegmentedJounral` to list the segments and get the files for each segment.

**Comment by deepthidevaki** [comment]
To restore from a backup, I wrote a new application similar to StandaloneBroker and StandaloneGateway. 
When this app runs, it should do the following:
1. Using the given configuration, it find which partitions belong to this broker. To find this, it builds RaftPartitionGroup, builds all partitions without starting them
2. From the partitions, it finds the dataDirectory
3. Copy snapshot and segments to the dataDirectory
4. Reads checkpointPosition from the backup
5. Deletes the extra recods after the checkpoint position from the segment. To do this it should build SegmentedJournal from the the dataDirectory. And use the Journal api to find the index and delete records after the index.

**Comment by deepthidevaki** [comment]
Prototype is done. You can check the [branch](https://github.com/camunda/zeebe/tree/dd-spike-backup). It can take backup to a local directory. 
Based on what I learned during the prototype, I will do task breakdown and create followup issues to start the implementation.
