### ISSUE TITLE
Use GHA instead of Jenkins

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#9127]
**Description**

Currently our CI Pipeline is running on Jenkins. We want to switch to GitHub Actions to make the pipeline easier to maintain, faster running, more reliable and visible for outside contributors.

### Current Status

With #8968 we've made some progress in the right direction:

- [x] GHA runs unit and integration tests
- [x] Most of the work is parallelized and runs on GitHub hosted runners
- [x] Test reports including logs are archived on failure

### Missing Features

Some of the features of the Jenkins pipeline are still missing:

- [ ] GHA: Build and test the Go client
- [ ] GHA: Archive JVM dumps
- [ ] #9035
- [ ] GHA: Calculate code coverage
- [ ] GHA: Collect test statistics

### Housekeeping

- [ ] Ensure that flaky tests fail the pipeline
- [ ] Bundle post-test steps into a reusable workflow
- [ ] Let bors check GHA instead of Jenkins
- [ ] Disable the Jenkins CI Pipeline
- [ ] Remove Jenkins CI Pipeline leftovers

**Comment by npepinpe** [comment]
I'll just add ad-hoc some of the questions I have, maybe some we can answer already, others we can create one or more issues to investigate:

- How can we keep the pipeline maintainable? One of the issues with Jenkins was how it grew organically over time without much after thought, and it became difficult to make sense of/onboard people. Is there something we can adopt from the start to minimize this?
- When using Testcontainers with GHA self-hosted runners, are the containers created in the same runner, in a different runner? If a different runner, is it a GitHub hosted runner or another self-hosted runner?
- Are we deploying the SNAPSHOT of the Maven artifacts when building main?
- Are we deploying the SNAPSHOT Docker image when building main?
- How will we handle running the nightly QA run? Can GHA handle long running workflows (~1h)?
- Should we keep SonarCloud integration if we have CodeQL baked in? Just wondering, possibly out of scope, but it may simplify things for us we decide not to.
- I would like this time, as we are building again from scratch, to document the pipeline. I guess this goes in the maintainability issue. Unless someone has a different idea to keep things easy to maintain? I don't think we need very in-depth docs, just which workflow contains what, does what, etc. A high level overview, more or less.
- Is [Foresight](https://github.com/marketplace/thundra-foresight) a good product for us? I know Testcontainers uses it to keep track of their builds from GHA, but when I've used it the UI was very slow (though pretty). 
- We run some nightly cron jobs for the stable branches and main, in a staggered fashion. Main at midnight, then each stable job one hour later. Is there a way to do this with GHA as well?

**Comment by cmur2** [comment]
> > When using Testcontainers with GHA self-hosted runners, are the containers created in the same runner, in a different runner? If a different runner, is it a GitHub hosted runner or another self-hosted runner?
> 
> I'm pretty sure it's the same runner but @cmur2 probably knows best.

Disclaimer: I don't know much about the internal workings of Testcontainers utility/framework.

That said, each job of a GHA workflow gets run on a separate runner. There is no way for the executed workflow steps to spawn an additional runner inside the same workflow/job during execution. So everything is confined to the same runner in my understanding.

**Comment by npepinpe** [comment]
Testcontainers simply uses the local Docker client to spawn containers, so it will just spawn them on whatever that's connected to. I believe GitHub hosted runners get a sibling container for this, but we weren't sure about the self-hosted. I guess we can quickly find out if we can exec/ssh into one of them to see what's the Docker client pointing to.

**Comment by npepinpe** [comment]
> @npepinpe Just to be clear, my understanding was that we only want to replace Jenkins with GHA as the bors check. That means that we run tests and code quality checks in GHA but nothing else. Specifically, deploying snapshots and docker images is still done by Jenkins. Do you agree on that or should I add more issues to this epic?

The thing is we don't want to deploy snapshots that are not working ideally, so we would still want to run the tests on the snapshot we're deploying, no? But we don't want to run tests in Jenkins anymore. So option is keep it in Jenkins but it's triggered by the tests passing in GitHub, or move it to GHA. I imagine they're similar effort, so I'd rather put it in GHA - maybe we can reuse the community release action for this? I know some projects use it to release SNAPSHOT. Releasing the Docker snapshot is pretty easy as well I think. What do you think?

**Comment by oleschoenburg** [comment]
Okay, then let's do that. Since @pihme already expressed interest in helping here I'm hopeful that we can get deploys in GHA too!

**Comment by npepinpe** [comment]
Semi related, I signed up for the Testcontainers Cloud beta, and will try it out to see if it would be a good use case for us to increase parallelism with the integration tests.

**Comment by npepinpe** [comment]
Regarding modularity/maintainability, the infra team posted the following links:

- https://github.blog/2022-02-10-using-reusable-workflows-github-actions/
- https://docs.github.com/en/actions/using-workflows/reusing-workflows
- https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

**Comment by korthout** [comment]
@oleschoenburg Please consider https://github.com/camunda/zeebe/issues/9365
