### ISSUE TITLE
[EPIC] Resource definition deletion

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#9576]
## Description

Users want to be able to delete old versions of processes and decision tables for a multitude of reasons. [This has been a highly requested feature for a while, ](https://github.com/camunda/zeebe/issues/2908) and [here.](https://github.com/camunda/zeebe/issues/2506)

Use cases:
- **Free up storage** - Some processes are old and outdated. They will never be started again. Since we cannot delete the definitions they will keep taking up storage space.
- **Improving overview** - When a lot of versions of a process are deployed these will all be visible in Operate, bloating the view with data that is not useful to users.
- **Security** - A process could contain a bug, or could be deprecated. Without the possibility to remove these definitions it will still be possible to start new instances of these processes. This could potentially result in issues for our customers.
- **Stopping cyclical processes** - Some processes are started every X amount of time by a timer start event. In order to stop this, a new version of the process has to be deployed where the timer is removed. Deleting a process definition would be a different way to stop this behavior. 

Additional resources:

- [Kickoff meeting](https://docs.google.com/document/d/1wf5fQ03be6178xk33QobSv_SgChmXfM7IP-OfnN5dzw/edit#heading=h.43jb1qji84y) (internal document)
- [Delete Process Definition Product-Hub](https://github.com/camunda/product-hub/issues/615) (internal)
- [Delete Decision Definition Product-Hub](https://github.com/camunda/product-hub/issues/94) (internal)

## Concept
A new command will be introduced to delete resources. These resources can either be BPMN resources, or DMN resources. In this command the key will be specified. Similar to how deployments work, this deletion will be distributed across the system.

In case of a process definition deletion Zeebe will:

1. Mark the definition as pending deletion. This will prevent the creation of new instances and halt the progress of running instances.
2. Terminate any running instances, for child instances an incident will be created in the parent process. This is an asynchronous step! After everything is terminate we continue with the actual deletion of the process definition.
4. Remove the resource from rocksdb
5. Remove the resource from the cache
6. Publish an event that the resource has been deleted

In case of a decision definition deletion Zeebe will:

1. Remove the resource from rocksdb
2. Remove the resource from the cache
3. Publish an event that the resource has been deleted

Furthermore, Zeebe should not re-use version numbers. When the latest version (X) of a resource is deleted, deploying the resource again will result in version X+1. In order to achieve this, the latest version number of a resource needs to be stored. When deploying a new resource this version should be fetched from rocksdb, incremented by one, and stored again.

<img width="2015" alt="image" src="https://github.com/camunda/zeebe/assets/5787702/4633e1b6-4778-4604-9e1c-40a363783101">

**Note:** For more information regarding the command distribution, please have a look at the documentation [here](https://github.com/camunda/zeebe/blob/main/docs/generalized_distribution.md)

## Spike

We have found several points of interest during the spike.

**Distribution**
- Distributing will not wait for acknowledgements from other partitions before deleting the resource. We adhere by eventual-consistency. By deleting it ASAP we prevent an unhealthy partition from blocking the deletion.
- We need to make sure the deployment has already happened. Otherwise the delete could happen before the deployment, resulting in the version to still be deployed. Rejecting the command and giving feedback to the users should be good enough here.

**Other**
- We should write a process DELETED event to complete the lifecycle of the ProcessRecord (CREATED & DELETED)
- What do we do with banned instances? We cannot terminate these, do we just delete these?
    - The nicest thing would be to delete all the data of these instances from the state. However the is no current way to remove this state. It would require [reevaluating the banning concept in its entirety](https://github.com/camunda/zeebe/issues/5121). Since we'd also like to get rid of the banning concept in its entirety this is out of scope.

#### Broker
- [x] #9766
- [x] #9767
- [x] #9799
- [x] Add `ValueType.RESOURCE_DELETION` to `CommandApiRequestReader`
- [x] #13335

#### Gateway API
- [x] #9790
- [x] #9793
- [x] #9794

#### Exporters/Metrics (process and decision)
- [x] #9811
- [ ] https://github.com/camunda-cloud/zeebe-analytics/issues/82

#### Documentation
- [x] https://github.com/camunda/camunda-platform-docs/issues/2264
- [x] https://github.com/camunda/camunda-platform-docs/issues/2384

#### Zeebe Process Test
- [x] https://github.com/camunda/zeebe-process-test/issues/441
- [x] https://github.com/camunda/zeebe-process-test/issues/443
- [x] https://github.com/camunda/zeebe-process-test/issues/444
- [x] https://github.com/camunda/zeebe-process-test/issues/445

#### Testing
- [x] Manual test

------------------

#### Broker
- [x] #13340
- [x] #13341
- [x] #13342
- [x] #13343
- [x] #13348
- [x] #13349
- [x] #9771
- [x] #9769
- [x] #13588
- [x] #9796
- [x] #9798
- [x] #13354

#### Testing
- [x] Write exhaustive tests to delete a process definition in different scenarios

#### Documentation
- [x] https://github.com/camunda/camunda-platform-docs/issues/2264

#### Out of scope
- [ ] #13587
- [ ] #9795
- [ ] #9797
- [ ] #13352
- [ ] #13353
- [ ] #13355

-------------------

#### Broker
- [x] #9770
- [x] #11540
- [x] #11541
- [x] #9773
- [x] #9774
- [x] #13204

#### Testing
- [x] Write exhaustive tests to delete a decision definition in different scenarios

#### Documentation
- [x] https://github.com/camunda/camunda-platform-docs/issues/2264

-------------------

### Out of Scope
- Deleting a process definition without terminating running instances
- Suspending creation of new process instances
- Undoing the deletion of resources
- Deleting multiple (versions of) definitions with a single command
- Removing data of blacklisted instances

**Comment by aleksander-dytko** [comment]
@remcowesterhoud quick question about `Suspending creation of new process instances` from `Out of Scope` - I just wanted to double-check that when I delete process definition, the creation of new instances of this definition won't be possible, right?

This is about `suspend/resume process definition` functionality, right?

**Comment by remcowesterhoud** [comment]
@aleksander-dytko That's correct. When we were discussing this topic we were thinking it would be nice to suspend a process instance first and wait until instances are completed before deleting the resources. Sort of a graceful deletion where we wouldn't need to terminate instances. However, for an MVP we decided against this as suspending is a big topic on its own.

**Comment by aleksander-dytko** [comment]
@remcowesterhoud thanks for the info, it aligns with user testing use cases. We have an item `suspend process definition` on the roadmap so we can cover this in the future.

**Comment by abbasadel** [comment]
Blocked #11456

**Comment by remcowesterhoud** [comment]
Moving this to `In Progress` as generalised command distribution has progressed far enough to be able to continue here.

**Comment by aleksander-dytko** [comment]
### Decision 8.08

@remcowesterhoud and I decided to pull deletion of a Process Definition that has running instances out of scope for now. Users are mainly requesting to delete old resources. By pulling this out of scope it allows us to prioritize more urgent topics first.

**Comment by remcowesterhoud** [comment]
Closing this as everything for the initial release is completed. Further improvements can be tracked in #13979

**Comment by aleksander-dytko** [comment]
Thanks @remcowesterhoud for making this happen! 🚀
