### ISSUE TITLE
[EPIC]: Engine Abstraction

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#9600]
## Why?

Our team has grown to a certain size, which makes it hard to manage and keep being focused (e.g. discussions etc.). We will split our development team into two separate teams to keep being focused on certain topics/issues, and the team and discussions around important topics manageable.

**The idea is the following:**

The Zeebe Distributed Platform (ZDP) Team provides an abstraction layer around how records are stored/persisted, read, and written. The Zeebe Platform Automation (ZPA) Team is in charge of processing the records and updating their state. With that, the idea is that both teams can fully concentrate/focus on their topics, e.g. ZPA on the real business logic. 

In order to support this split, we will need some better abstraction between certain layers/modules/parts of the system. One of them is the engine. 

### Design / Finding phase

- [x] Create a proposal for a possible abstraction between both teams for the engine
  - [x] Write down an proposal, and validate with the team https://github.com/camunda/zeebe/issues/9601
  - [x] Do a proof of concept of that proposal https://github.com/camunda/zeebe/issues/9602
- [x] Discuss the POC Results https://github.com/camunda/zeebe/issues/9602#issuecomment-1172029736
- [x] If proposal and POC successful completed, do a further break down of following tasks.

### Implementation:
[![issueorder (1)](https://user-images.githubusercontent.com/2758593/177758829-b4e34733-bc91-4f42-89c8-044b77a4b61e.png)](https://modeler.cloud.ultrawombat.com/share/fd6bd130-240a-4819-9e79-5d1f673c83e1)

<sup>I marked the path blue which is necessary to satisfy #9420. This means we need to have the error handling in the engine implementation in order to achieve this. </sup>

- [x] https://github.com/camunda/zeebe/issues/9724
  - [x] In order to work on this in parallel we copy the `TypedStreamWriterImpl` to a new class and make certain changes
    - [x] Copy the content from `TypedStreamWriterImpl` to a new class
    - [x] Remove the LogStreamBatch usage from that class, write directly into a pre-claimed buffer
    - [x] Add a new method to the LogStreamBatch
    - [x] Write tests for both
  - [x] Find a good new name for the Writers Interface, including Command-, Rejection-, StateWriter. In the POC #9602, we called it Builders, because wanted in the end build a list of Records. But maybe we can also use a different name here.
  - [x] Create a new Result Interface / Class which can be returned by the Engine
    - [x] The Result can for simplicity return a BufferWriter like we did in the POC #9602 (we can improve that later), but we can also just return a list of Records if you find a good way for it
    - [x] Result should be used by Processing and ScheduledTasks to return Results
  - [x] Engine should return the result - :warning: here we need the Stream Processing changes first 
  - [x] Use result in platform, write the records to the LogStreamBatchWriter
  - [x] **Bonus:**  The result contains only the list of the records (instead of the general Buffer or BufferWriter)
  - [x] **Bonus2** The serialization is done in the StreamPlatform on writing to the LogStreamBatchWriter
  - [x] We might need to adjust some tests  
 
- [x] https://github.com/camunda/zeebe/issues/9725
  - [x] Mark the processing explicitly as currently ongoing, via flag. The `currentProcessor` field shouldn't be used anymore.
  - [x] Find a good name for the StreamProcessor
  - [x] Rename the current StreamProcessor, e.g. StreamingPlatform (see #9602)
  - [x] Introduce a new StreamProcessor interface, which covers the reality (this needs to be adjusted during progressing with #9600 )
    - [x] init Method
    - [x] replay Method
    - [x] process Method (at the beginning with no Result returning, only after parts of #9724 are done)
    - [x] onError Method - might be empty at the begin
    - [x] ~Implement LifecycleAware?~
  - [x] Create a new StreamProcessor implementation called Engine
  - [x] Move some code out from the StreamingPlatform, ReplayStateMachine and ProcessingStateMachine to the Engine, see POC #9602 and related branch
  - [x] :warning: OnError implementation, can be completed after the writer change is done and we can return a Result see #9724 
    - [x] Transaction is rolled back by StreamPlatform, new Transaction is created and Engine is called (onError)
    - [x] Engine should be able to receive the Throwable, Command and current position (?)
    - [x] Based on the input it can return a Result, which will be written to the log, and the transaction is committed again. Here we can use the same path from the ProcessingStateMachine as we do from the normal processing.
  - [x] **Bonus:** If we create the Engine outside of the StreamingPlatform and give it to the builder, we can inject the dependencies outside and can simplify the StreamProcessor tests
  - [x] Cleanup
    - [x] #10034
- [x] https://github.com/camunda/zeebe/issues/9730
  - [x] Create a new interface for the ProcessingScheduleService (with narrowed scope)
    - [x] Possibily only two methods, runDelayed and runComplete take a look at the POC #9602 
    - [x] Ideally we use real futures on the runComplete, but might be something we refactor later
    - [x] The interface contains a way to return some records, which will be written later on
    - [x] Support runAfterCommit https://github.com/camunda/zeebe/issues/9723#issuecomment-1177371393 to replace side effects
  - [x] Implement the interface, and provide certain guarantees, [take a look at POC for more details ](https://github.com/camunda/zeebe/issues/9602#issuecomment-1172029736)
    - [x] Guarantee 1: We are executed after processing and committing transaction (e.g. if scheduling happened during processing)
    - [x] ~Guarantee 2: We are not executed in parallel with processing (discussable, depends on the Writers and Result implementation)~ We removed this again https://github.com/camunda/zeebe/pull/10355
  - [x] ~**Bonus:** We might want to execute multiple delayed tasks on parallel maybe even in parallel during processing, for that we need to make sure that resources are not shared~
    - [x] The above was not easily possible with https://github.com/camunda/zeebe/pull/10428 we removed the shared writer, and the addition submit, but other than that it was not possible to create a new actor for it.
    - [x] ~The consumer of the SchedulingService have only ReadOnly access to the database~ This was not easily possible
  - [x] Add unit tests for the implementation
  - [x] Before migrating to the new abstraction, migrate the ActorCOntrol#runAtFixedRate consumers to the #runDelayed usage, this means after each run the job needs to be scheduled again
  - [x] Integrate the ProcessingScheduler in the ProcessingStateMachine, means if task is executed we can write the result to the log https://github.com/camunda/zeebe/issues/9999
  - [x] Migrate step by step the actorControl usage
  - [x] Remove the actor control from the ProcessingContext
  - [x] Remove LogStreamWriter from the ProcessingContext

- [x] https://github.com/camunda/zeebe/issues/9723
  - [x] Clarify that use case or question whether we still want to support executing side effects after successful processing only https://github.com/camunda/zeebe/issues/9686
  - [x] If yes, we might want to improve the current side effects to make it not so unstable as it is right now (if a side effect is added it is likely the previous is overwritten). We maybe want to support a queue
  - [x] If no, remove the side effects and send requests/responses directly

- [ ] https://github.com/camunda/zeebe/issues/9727
  - [x] Remove the position from the TypedRecordProcessor#process see #9602 
  - [x] Remove ProxyWriter from the ProcessingContext see #9602 
  - [x] [Remove proxy writers](https://github.com/camunda/zeebe/commit/88ed05a7553409498c15b65aa87e8c5c49f36aff)
  - [x] Remove writers from the processing interface after #9724 and https://github.com/camunda/zeebe/issues/9723
  - [x] Clean up ProcessingContext, remove unused classes/objects
  - [ ] **Bonus**: Split up the engine module into Stream Platform and Engine and separate the components

- [ ] Update downstream repos
  - [ ] Zeebe process test
  - [ ] Eze
