### ISSUE TITLE
Zeebe can backup its data to an external storage without downtime and restore from it

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9606]
As a user (operator), I can take backup of a zeebe cluster to and external storage and restore from a backup. 

We will implement [ZEP: Take backup of zeebe cluster without downtime](https://github.com/zeebe-io/enhancements/blob/master/ZEP008-hot-backup.md).

## Goal:

- Zeebe will expose an API by which an operator can take backups and manage backups. 
- Zeebe will provide a way to restore from a given backup

## Addition info

- #9103
- [ZEP: Take backup of zeebe cluster without downtime](https://github.com/zeebe-io/enhancements/blob/master/ZEP008-hot-backup.md).
- Related to https://github.com/camunda/product-hub/issues/104

#### To discuss and decide
- [x] Decide gateway endpoint and API
- [x] Decide which type of storage to support for backup

#### StreamProcessor
- [x] #9612
- [x] #9613 
- [x] #9719
- [x] #9720

#### Snapshotting
- [x] #9626 
- [x] #9627
- [x] ~#9906~
- [x] #10115
- [ ] #10206

#### Backup management
- [x] #9806
- [x] #9978 
- [x] Implement backup manager
  - [x] #9979
  - [x] #9981
  - [x] #10189
  - [x] #10207 
- [x] #10229
  - [x] #10220
  - [x] Backup store can save a backup
    - [x] #10085
    - [x] #10110
    - [x] #10125
  - [x] #10159
  - [x] #10179
  - [x] #10134
  - [x] #10146
  - [x]  #10184
  - [x] #10218
  - [x] #10219
  - [x] #10235
  - [x] #10238
- [ ] #10208 

#### Communication
- [x] Define communication interface between gateway and broker for backup commands
- [x] #9726
- [x] #9807 
- [ ] #9808
- [x] #9625
- [x] #9721
- [x] #9809
- [x] #9810

#### Broker
- [x] #10262
- [x] #10264
- [x] #10369

#### Gateway
- [x] #9630
- [x] #9633
- [x] #9901 
- [x] #9902 
- [ ] #10209

#### Restore
- [x] #10263

#### Test
- [ ] #10387
- [ ] Write tests for different concurrency scenarios
    - Simulate different concurrency scenarios to take backup. Verify that after restore the inconsistent states due to deployment or message correlation do not exist.
- [ ] Test failure scenarios
   - Test scenarios where a leader change/restart happens while taking backup.

#### Documentation
- [ ] Docs for pause/resume exporting operation
- [ ] Docs for backup apis

#### Metrics
- [x] #10385
- [x] #10386

#### Out of scope
- Providing a client for the backup api
- Supporting multiple types of backup storage

**Comment by deepthidevaki** [comment]
As we are nearing code freeze for 8.1.0 release, we have left some issues for the next quarter. Following are some issues/improvements that we would not be able to get it in 8.1.0. But we should tackle them sooner than later.

- [ ] If the given ID refers to a failed backup (that we know of), take backup command should return an error already, so the user knows to retry with a higher ID. To allow this we may have to let the Backup manager send response for take backup request instead of StreamProcessor. This will let us add more info to the take backup response - such as backup status if it already exists etc.
- [ ] Add more details to the existing take backup and get status api responses. The [openApi spec](https://github.com/camunda/zeebe/issues/9901#issuecomment-1250365176) describes our desired api.
- [ ] Implement api to list all backups in gateway
- [ ] #10209 
- [ ] Change restore process (to be discussed).
	- Add api to restore and monitor progress of restore in gateway
	- Users can restore the cluster from a specific backup by 
		1. Start zeebe cluster with a clean state
		2. List all completed backups => choose which backup to restore from
		3. send POST restore/backupId to gateway
		4. Monitor progress of restore => failed | inprogress | completed
- [ ] Make PartitionStatus actuator available in gateway. This will be useful to monitor status of pause/resume exporting
- [ ] #10206
- [ ] Add grafana panels for the backup metrics.

**Comment by oleschoenburg** [comment]
Future Improvement to the S3 backup store implementation:

- [ ] Transparent backup compression
- [ ] Verify checksums to ensure that backups are not modified or corrupted
- [ ] Restructure object layout for more efficient listing of backups
- [ ] Ensure compatibility with advanced S3 features such as object locking and versioning
