### ISSUE TITLE
Remove LogStream writers from Engine

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#9724]
**Description**

Part of #9600 

In the current state the TypedProcessors (which might become the Engine later) and other entities, like [JobTimeoutTrigger](https://github.com/camunda/zeebe/blob/2d4901c0e516b7fa8b1cf3408b06708c1644ca57/engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobTimeoutTrigger.java#L79-L82), DeploymentDistributor etc. have knowledge about how to write Records to the LogStream abstraction. Ideally, they shouldn't care about that detail. In the end, it would be great if the Engine can get something in and produce something out. For that we have to do some pre-work like removing the actual LogStreamBatchWriters usage and reduce related interfaces.

In the POC #9602 we split up the implementation of the `TypedStreamWriterImpl` so that it just writes into a wrapped buffer. This allowed to pre-claim that buffer in the start, and initialize the Engine with that Writer. This means we can reduce the dependency to the LogStream (helps when we split the Engine and the StreamPlatform). Later we renamed the Writers to something like Builder, but this is discussable.

See `Writers` in https://github.com/camunda/zeebe/issues/9602#issuecomment-1172029736

**Todo:**

- [x] #9780
  - [x] Copy the content from `TypedStreamWriterImpl` to a new class
  - [x] Remove the LogStreamBatch usage from that class, write directly into a pre-claimed buffer
- [x] ~Add a new method to the LogStreamBatch~
- [x] ~Write tests for `LogStreamBatch`~
- [x] made the canWriteEvent method public on the LogStreamBatchWriter in order to use it in the RecordBatch
- [x] https://github.com/camunda/zeebe/issues/10001
  - [x] Replace with RecordBatch
  - [x] Use RecordBatch everywhere
- [x] #9838
- [x] https://github.com/camunda/zeebe/issues/9998
- [x] Find a good new name for the Writers Interface, including Command-, Rejection-, StateWriter. In the POC #9602, we called it Builders, because wanted in the end build a list of Records. But maybe we can also use a different name here.
- [x] Create a new Result Interface / Class which can be returned by the Engine
  - [x] The Result can for simplicity return a BufferWriter like we did in the POC #9602 (we can improve that later), but we can also just return a list of Records if you find a good way for it
  - [x] Result should be used by Processing and ScheduledTasks to return Results
- [x] Engine should return the result - :warning: here we need the Stream Processing changes first  https://github.com/camunda/zeebe/issues/9725
- [x] Use result in platform, write the records to the LogStreamBatchWriter
- [x] **Bonus:**  The result contains only the list of the records (instead of the general Buffer or BufferWriter)
- [x] **Bonus2** The serialization is done in the StreamPlatform on writing to the LogStreamBatchWriter
- [x] We might need to adjust some tests

**Comment by Zelldon** [comment]
There was a comment regarding the naming by @saig0 maybe we consider this here https://github.com/camunda/zeebe/issues/9602#issuecomment-1174862213

**Comment by Zelldon** [comment]
There was a comment by @npepinpe regarding to the serialization and the Result class:

>https://github.com/camunda/zeebe/issues/9602#issuecomment-1174829534
> **Should the engine implementation actually serialize the outputs?**
> Pros: frictionless, no need to interact with the distributed, easier to extend later if we add different processors.
> Cons: more complicated for testing, embedding, possibly need to implement own integrity checks, schema evolution, not reusing the expertise of the distributed team regarding persistence.
> I personally lean with Peter on having "record in -> record(s) out" instead of dealing with (de)serialization.
