### ISSUE TITLE
Refactor StreamProcessor / Engine

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#9725]
**Description**

Part of #9600 

Rename StreamProcessor, to better distinguish between the Platform which drives the Processor, the StreamProcessor interface, and the Engine as implementation, etc. Furthermore, refactor the current implementation to make it possible to split up the modules and have clear boundaries between components.

See `Processing` in https://github.com/camunda/zeebe/issues/9602#issuecomment-1172029736

**Todo:**

  - [x] Mark the processing explicitly as currently ongoing, via flag. The `currentProcessor` field shouldn't be used anymore.
  - [x] Find a good name for the StreamProcessor
  - [x] Rename the current StreamProcessor, e.g. StreamingPlatform (see #9602)
  - [x] Introduce a new StreamProcessor interface, which covers the reality (this needs to be adjusted during progressing with #9600 )
    - [x] init Method
    - [x] replay Method
    - [x] process Method (at the beginning with no Result returning, only after parts of #9724 are done)
    - [x] onError Method - might be empty at the begin
    - [x] ~Implement LifecycleAware?~
  - [x] Create a new StreamProcessor implementation called Engine
  - [x] Move some code out from the StreamingPlatform, ReplayStateMachine and ProcessingStateMachine to the Engine, see POC #9602 and related branch
  - [x] :warning: OnError implementation, can be completed after the writer change is done and we can return a Result see #9724 
    - [x] Transaction is rolled back by StreamPlatform, new Transaction is created and Engine is called (onError)
    - [x] Engine should be able to receive the Throwable, Command and current position (?)
    - [x] Based on the input it can return a Result, which will be written to the log, and the transaction is committed again. Here we can use the same path from the ProcessingStateMachine as we do from the normal processing.
  - [x] **Bonus:** If we create the Engine outside of the StreamingPlatform and give it to the builder, we can inject the dependencies outside and can simplify the StreamProcessor tests
  - [x] Cleanup
    - [x] #10034

**Comment by Zelldon** [comment]
There was a question raised by @npepinpe regarding error handling in onError:

> https://github.com/camunda/zeebe/issues/9602#issuecomment-1174829534
>What if an error occurs in onProcessingError? Do we have some escape hatch? How about UnrecoverableError classes? How > much control do we give to the engine (i.e. can it shut itself down on unrecoverable error)?

My answer would be similar like we do it now: https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/streamprocessor/ProcessingStateMachine.java#L56-L87
```

 * +------------------+            +--------------------+
 * |                  |            |                    |      exception
 * | readNextRecord() |----------->|  processCommand()  |------------------+
 * |                  |            |                    |                  v
 * +------------------+            +--------------------+            +---------------+
 *           ^                             |                         |               |------+
 *           |                             |         +-------------->|   onError()   |      | exception
 *           |                             |         |  exception    |               |<-----+
 *           |                     +-------v-------------+           +---------------+
 *           |                     |                     |                 |
 *           |                     |   writeRecords()    |                 |
 *           |                     |                     |<----------------+
 * +----------------------+        +---------------------+
 * |                      |                 |
 * | executeSideEffects() |                 v
 * |                      |       +----------------------+
 * +----------------------+       |                      |
 *           ^                    |     updateState()    |
 *           +--------------------|                      |
 *                                +----------------------+
 *                                       ^      |
 *                                       |      | exception
 *                                       |      |
 *                                    +---------v----+
 *                                    |              |
 *                                    |   onError()  |
 *                                    |              |
 *                                    +--------------+
 *                                       ^     |
 *                                       |     |  exception
 *                                       +-----+
 *
```

**Comment by npepinpe** [comment]
To clarify, this means we loop in the engine?

**Comment by Zelldon** [comment]
No.

The engine is called with an error and record (**onError**). If here an exception occurs again then, we again catch that in the StreamProcessor, rollback the transaction and start new a transaction and call onError again.

**Comment by npepinpe** [comment]
Thanks! That's not obvious from the diagram, it looks like we loop in `onError` :smile:

**Comment by Zelldon** [comment]
Yeah this state machine is the current state, and taken from the current StreamProcessor sorry :sweat_smile:

**Comment by Zelldon** [comment]
The refactoring of the streamprocessor / engine interface is done. There might be some clean up which we will do with https://github.com/camunda/zeebe/issues/9727
