### ISSUE TITLE
Clean up StreamingPlatform / Engine

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#9727]
**Description**

Part of #9600 

There a multiple things we can remove or clean up during #9600, some of these might be only possible at the end, but some are already possible at the beginning.

See `Finding` in https://github.com/camunda/zeebe/issues/9602#issuecomment-1172029736

**Todo:**

- [x] Remove the position from the TypedRecordProcessor#process see #9602 
- [x] Remove ProxyWriter from the ProcessingContext see #9602 
- [x] :warning:  Remove writers from processing interface after #9724 
- [x] Clean up ProcessingContext, remove unused classes/objects
- [ ] :warning:  **Bonus**: Split up the engine module into Stream Platform and Engine and separate the components (after #9600 is done)
- [ ] Create new streamProcessor maven module https://github.com/camunda/zeebe/issues/10130
 - [x] Move `io.camunda.zeebe.engine.api` to another package so that it's clearer it is a shared API and not only used by the engine
 - [x] Remove multi partition support from StreamPlatformExtension https://github.com/camunda/zeebe/pull/10398
 - [x] Remove context from SchedulingService, to make dependencies more clearer #10428 
 - [x] https://github.com/camunda/zeebe/issues/10216
