### ISSUE TITLE
Introduce ProcessingScheduleService

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#9730]
**Description**

Part of #9600 

Create an abstraction around the processing actor, since we want to remove the dependency and knowledge about the current execution model from the engine. This will simplify the tests as we can use a simple implementation for the execution and it should also help us to make further changes to the actor scheduler etc.

See `SchedulingService` in https://github.com/camunda/zeebe/issues/9602#issuecomment-1172029736

**Todo:**

- [x] Create a new interface for the ProcessingScheduleService (with narrowed scope)
  - [x] Possibily only two methods, runDelayed and runComplete take a look at the POC #9602 
  - [x] Ideally we use real futures on the runComplete, but might be something we refactor later
  - [x] The interface contains a way to return some records, which will be written later on
  - [x] Support runAfterCommit https://github.com/camunda/zeebe/issues/9723#issuecomment-1177371393 to replace side effects
- [x] Implement the interface, and provide certain guarantees, [take a look at POC for more details ](https://github.com/camunda/zeebe/issues/9602#issuecomment-1172029736)
  - [x] Guarantee 1: We are executed after processing and committing transaction (e.g. if scheduling happened during processing)
  - [x] ~Guarantee 2: We are not executed in parallel with processing (discussable, depends on the Writers and Result implementation)~ We removed this again https://github.com/camunda/zeebe/pull/10355
- [x] ~**Bonus:** We might want to execute multiple delayed tasks on parallel maybe even in parallel during processing, for that we need to make sure that resources are not shared~
  - [x] The above was not easily possible with https://github.com/camunda/zeebe/pull/10428 we removed the shared writer, and the addition submit, but other than that it was not possible to create a new actor for it.
  - [x] ~The consumer of the SchedulingService have only ReadOnly access to the database~ This was not easily possible
- [x] Add unit tests for the implementation
- [x] Before migrating to the new abstraction, migrate the ActorCOntrol#runAtFixedRate consumers to the #runDelayed usage, this means after each run the job needs to be scheduled again
- [x] Integrate the ProcessingScheduler in the ProcessingStateMachine, means if task is executed we can write the result to the log https://github.com/camunda/zeebe/issues/9999
- [x] Migrate step by step the actorControl usage
- [x] Remove the actor control from the ProcessingContext
- [x] Remove LogStreamWriter from the ProcessingContext

**Comment by Zelldon** [comment]
Question raised from Nicolas after the POC:

> https://github.com/camunda/zeebe/issues/9602#issuecomment-1174829534
> Abstracting actor scheduler sounds good. What is the minimal interface? Can we get rid of runUntilDone and the likes, and just go for two capabilities: defer execution (e.g. run or submit) and schedule (e.g. runDelayed)? That would greatly simplify things. The caller can take care of runUntilDone by implementing their own state machine which ensures no other tasks can be completed in between. However if we want to keep the queuing mechanism, then this is not possible. Do we need it, though?

I think this is a bit unrelated to the topic and can be discussed with the PDT regarding the actor scheduler changes. The ProcessingScheduleService will have a really limited interface, which you can see above.

**Comment by npepinpe** [comment]
Do you mean this one?

```java
interface SchedulingService {
  Collection<Records> schedule(Duration d, Runnable r);
}
```

**Comment by Zelldon** [comment]
No sorry. For example in the POC it looked like this: https://github.com/camunda/zeebe/commit/176cfabe3b0997a60604ddb315a9c6607c7b8a40#diff-f27601ec63a23e86b4a992a9cd4ac54192d81fbea9da126a8edeaa3b20123427R483-R487 

 ```
 public interface ProcessingSchedulingService {

    void runWithDelay(Duration duration, Supplier<ProcessingResult> scheduledProcessing);
  }
```

We need to pass in an Supplier otherwise it doesn't work, the method itself can't return this. 

It depends now on #9724 how the result looks like, but this will be then the return of the Supplier or function or what ever is passed in.

**Comment by pihme** [comment]
This comment came up during a discussion: https://github.com/camunda/zeebe/pull/9756#pullrequestreview-1035872193

> Regarding timers, we do return a cancellable ScheduledTimer, which will prevent the execution of the timer. I didn't notice it being used during cancellation. I know we need to do both (since if the timer was added to the actor task queue before it's cancelled, it will be executed regardless), but it may avoid unnecessary runs. If we don't want to expand the API with another interface just yet, we could return something like a CloseableSilently for now. It does mean keeping track of the current timer however 

For now, I didn't follow that suggestion and want to see whether we can do without it.

**Comment by Zelldon** [comment]
With https://github.com/camunda/zeebe/pull/10428 we completed this part of #9600
